OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipclass3connection.c File Reference
src/cip/cipclass3connection.c File Reference
#include <string.h>
#include "cipclass3connection.h"
Functions
EipStatus EstablishClass3Connection (ConnectionObject *RESTRICT const connection_object, EipUint16 *const extended_error)
Check if Class3 connection is available and if yes setup all data.
ConnectionObject * GetFreeExplicitConnection (void)
Searches and returns a free explicit connection slot.
void InitializeClass3ConnectionData (void)
Initializes the explicit connections mechanism.
Variables
ConnectionObject g_explicit_connections [OPENER_CIP_NUM_EXPLICIT_CONNS]
Array of the available explicit connections.
Function Documentation
EipStatus EstablishClass3Connection (ConnectionObject *RESTRICT const connection_object, EipUint16 *const extended_error)
Check if Class3 connection is available and if yes setup all data.
This function can be called after all data has been parsed from the forward open request
Parameters:
connection_object pointer to the connection object structure holding the parsed data from the forward open request
extended_error the extended error code in case an error happened
Returns:
general status on the establishment
kEipStatusOk ... on success
On an error the general status code to be put into the response
Definition at line 19 of file cipclass3connection.c.
References AddNewActiveConnection(), connection_object::cip_produced_connection_id, connection_object::connection_close_function, connection_object::connection_timeout_function, CopyConnectionData(), GeneralConnectionConfiguration(), GetFreeExplicitConnection(), connection_object::instance_type, kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeErrorNoMoreConnectionsAvailable, kConnectionTypeExplicit, kEipStatusOk, RemoveFromActiveConnections(), and connection_object::socket.
Referenced by ConnectionManagerInit().
ConnectionObject * GetFreeExplicitConnection (void)
Searches and returns a free explicit connection slot.
Returns:
Free explicit connection slot, or NULL if no slot is free
Definition at line 60 of file cipclass3connection.c.
References kConnectionStateNonExistent, and OPENER_CIP_NUM_EXPLICIT_CONNS.
Referenced by EstablishClass3Connection().
void InitializeClass3ConnectionData (void)
Initializes the explicit connections mechanism.
Prepares the available explicit connection slots for use at the start of the OpENer
Definition at line 69 of file cipclass3connection.c.
References OPENER_CIP_NUM_EXPLICIT_CONNS.
Referenced by InitializeConnectionManagerData().
Variable Documentation
ConnectionObject g_explicit_connections[OPENER_CIP_NUM_EXPLICIT_CONNS]
Array of the available explicit connections.
Definition at line 16 of file cipclass3connection.c.