OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipconnectionmanager.c File Reference
src/cip/cipconnectionmanager.c File Reference
#include <string.h>
#include <stdbool.h>
#include "cipconnectionmanager.h"
#include "opener_user_conf.h"
#include "cipcommon.h"
#include "cipmessagerouter.h"
#include "ciperror.h"
#include "endianconv.h"
#include "opener_api.h"
#include "encap.h"
#include "cipidentity.h"
#include "trace.h"
#include "cipclass3connection.h"
#include "cipioconnection.h"
#include "cipassembly.h"
#include "cpf.h"
#include "appcontype.h"
#include "generic_networkhandler.h"
#include "cipepath.h"
#include "cipelectronickey.h"
#include "cipqos.h"
Data Structures
struct ConnectionManagementHandling
Defines
#define CIP_CONN_TYPE_MASK 0x6000
#define EQLOGICALPATH(x, y) (((x) & 0xfc)==(y))
Compares the logical path on equality.
Typedefs
typedef EipStatus(* HandleForwardOpenRequestFunction)(ConnectionObject *connection_object, CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response)
Function prototype for all Forward Open handle functions.
Functions
EipStatus AddConnectableObject (EipUint32 class_id, OpenConnectionFunction open_connection_function)
register open functions for an specific object.
void AddNewActiveConnection (ConnectionObject *connection_object)
Insert the given connection object to the list of currently active and managed connections.
void AddNullAddressItem (CipCommonPacketFormatData *common_data_packet_format_data)
Adds a Null Address Item to the common data packet format data.
EipStatus AssembleForwardCloseResponse (EipUint16 connection_serial_number, EipUint16 originatior_vendor_id, EipUint32 originator_serial_number, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response, EipUint16 extended_error_code)
EipStatus AssembleForwardOpenResponse (ConnectionObject *connection_object, CipMessageRouterResponse *message_router_response, EipUint8 general_status, EipUint16 extended_status)
Assembles the Forward Open Response.
EipStatus CheckElectronicKeyData (EipUint8 key_format, CipKeyData *key_data, EipUint16 *extended_status)
Compare the electronic key received with a forward open request with the device's data.
ConnectionObject * CheckForExistingConnection (ConnectionObject *connection_object)
check if the data given in the connection object match with an already established connection
void CloseConnection (ConnectionObject *RESTRICT connection_object)
Close the given connection.
EipStatus ConnectionManagerInit (EipUint16 unique_connection_id)
Initialize the data of the connection manager object.
void CopyConnectionData (ConnectionObject *RESTRICT destination, const ConnectionObject *RESTRICT const source)
Copy the given connection data from source to destination.
EipStatus ForwardClose (CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response, struct sockaddr *originator_address)
EipStatus ForwardOpen (CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response, struct sockaddr *originator_address)
Check if resources for new connection available, generate ForwardOpen Reply message.
void GeneralConnectionConfiguration (ConnectionObject *connection_object)
Generate the ConnectionIDs and set the general configuration parameter in the given connection object.
ConnectionObject * GetConnectedObject (EipUint32 connection_id)
ConnectionObject * GetConnectedOutputAssembly (EipUint32 output_assembly_id)
EipUint32 GetConnectionId (void)
Generate a new connection Id utilizing the Incarnation Id as described in the EIP specs.
ConnectionManagementHandling * GetConnectionManagementEntry (EipUint32 class_id)
EipUint32 GetConnectionObjectInactivityWatchdogTimerValue (ConnectionObject *connection_object)
EipUint32 GetConnectionObjectInitialInactivityWatchdogTimerValue (ConnectionObject *connection_object)
ConnectionObjectFixedVariable GetConnectionObjectTargetToOriginatorFixedOrVariableConnectionSize (const ConnectionObject *const RESTRICT connection_object)
ForwardOpenPriority GetConnectionObjectTToOPriority (const ConnectionObject *const connection_object)
EipStatus GetConnectionOwner (CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response, struct sockaddr *originator_address)
ForwardOpenConnectionType GetConnectionType (EipUint16 network_connection_parameter)
returns the connection type of the supplied network connection parameter
unsigned int GetPaddedLogicalPath (const EipUint8 **logical_path_segment)
gets the padded logical path TODO: enhance documentation
CipUint GetProductionInhibitTime (const ConnectionObject *const connection_object)
ProductionTrigger GetProductionTrigger (const ConnectionObject *const connection_object)
CipUdint GetTargetToOriginatorRequestedPackedInterval (const ConnectionObject *const RESTRICT connection_object)
EipStatus HandleNonNullMatchingForwardOpenRequest (ConnectionObject *connection_object, CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response)
Handles a Non Null Matching Forward Open Request.
EipStatus HandleNonNullNonMatchingForwardOpenRequest (ConnectionObject *connection_object, CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response)
Handles a Non Null Non Matching Forward Open Request.
EipStatus HandleNullMatchingForwardOpenRequest (ConnectionObject *connection_object, CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response)
Handles a Null Matching Forward Open request.
EipStatus HandleNullNonMatchingForwardOpenRequest (ConnectionObject *connection_object, CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response)
Handles a Null Non Matching Forward Open Request.
EipStatus HandleReceivedConnectedData (EipUint8 *data, int data_length, struct sockaddr_in *from_address)
Notify the connection manager that data for a connection has been received.
void InitializeConnectionManager (CipClass *class)
void InitializeConnectionManagerData (void)
EipBool8 IsConnectedOutputAssembly (const EipUint32 instance_number)
EipStatus ManageConnections (MilliSeconds elapsed_time)
Check if any of the connection timers (TransmissionTrigger or WatchdogTimeout) have timed out.
EipUint8 ParseConnectionPath (ConnectionObject *connection_object, CipMessageRouterRequest *message_router_request, EipUint16 *extended_error)
Parse the connection path of a forward open request.
void ReadOutConnectionObjectFromMessage (CipMessageRouterRequest *const message_router_request, ConnectionObject *const connection_object)
void RemoveFromActiveConnections (ConnectionObject *connection_object)
Removes connection from the list of active connections.
void SetProductionInhibitTime (const EipUint16 production_inhibit_time, ConnectionObject *const connection_object)
void SetProductionTrigger (const enum ProductionTrigger production_trigger, ConnectionObject *connection_object)
EipStatus TriggerConnections (unsigned int output_assembly, unsigned int input_assembly)
Trigger the production of an application triggered connection.
Variables
EipUint16 device_type_
ConnectionObject * g_active_connection_list = NULL
List holding all currently active connections.
ConnectionManagementHandling g_connection_management_list [2+OPENER_CIP_NUM_APPLICATION_SPECIFIC_CONNECTABLE_OBJECTS]
ConnectionObject g_dummy_connection_object
EipUint32 g_incarnation_id
Holds the connection ID's "incarnation ID" in the upper 16 bits.
const int g_kForwardOpenHeaderLength = 36
EipUint16 product_code_
CipRevision revision_
EipUint16 vendor_id_
Define Documentation
#define CIP_CONN_TYPE_MASK 0x6000
Bit mask filter on bit 13 & 14
Definition at line 37 of file cipconnectionmanager.c.
#define EQLOGICALPATH (x, y) (((x) & 0xfc)==(y))
Compares the logical path on equality.
Definition at line 42 of file cipconnectionmanager.c.
Referenced by ParseConnectionPath().
Typedef Documentation
typedef EipStatus(* HandleForwardOpenRequestFunction)(ConnectionObject *connection_object, CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response)
Function prototype for all Forward Open handle functions.
Definition at line 474 of file cipconnectionmanager.c.
Function Documentation
void AddNewActiveConnection (ConnectionObject * connection_object)
Insert the given connection object to the list of currently active and managed connections.
By adding a connection to the active connection list the connection manager will perform the supervision and handle the timing (e.g., timeout, production inhibit, etc).
Parameters:
connection_object pointer to the connection object to be added.
Definition at line 1605 of file cipconnectionmanager.c.
References connection_object::first_connection_object, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, and connection_object::state.
Referenced by EstablishClass3Connection(), and EstablishIoConnection().
void AddNullAddressItem (CipCommonPacketFormatData * common_data_packet_format_data)
Adds a Null Address Item to the common data packet format data.
Parameters:
common_data_packet_format_data The CPF data packet where the Null Address Item shall be added
Definition at line 1070 of file cipconnectionmanager.c.
References CipCommonPacketFormatData::address_item, CipCommonPacketFormatData::data_item, kCipItemIdNullAddress, kCipItemIdUnconnectedDataItem, AddressItem::length, AddressItem::type_id, and DataItem::type_id.
Referenced by AssembleForwardCloseResponse(), and AssembleForwardOpenResponse().
EipStatus AssembleForwardCloseResponse (EipUint16 connection_serial_number, EipUint16 originatior_vendor_id, EipUint32 originator_serial_number, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response, EipUint16 extended_error_code)
Definition at line 1096 of file cipconnectionmanager.c.
References AddDintToMessage(), AddIntToMessage(), CipMessageRouterResponse::additional_status, AddNullAddressItem(), CipMessageRouterRequest::data, CipMessageRouterResponse::data, CipCommonPacketFormatData::data_item, CipMessageRouterResponse::data_length, g_common_packet_format_data_item, CipMessageRouterResponse::general_status, CipCommonPacketFormatData::item_count, kCipErrorConnectionFailure, kCipErrorPrivilegeViolation, kCipErrorSuccess, kCipItemIdUnconnectedDataItem, kConnectionManagerExtendedStatusCodeSuccess, kConnectionManagerExtendedStatusWrongCloser, kEipStatusOkSend, CipMessageRouterResponse::reply_service, CipMessageRouterRequest::service, CipMessageRouterResponse::size_of_additional_status, and DataItem::type_id.
Referenced by ForwardClose().
EipStatus AssembleForwardOpenResponse (ConnectionObject * connection_object, CipMessageRouterResponse * message_router_response, EipUint8 general_status, EipUint16 extended_status)
Assembles the Forward Open Response.
Parameters:
connection_object pointer to connection Object
message_router_response pointer to message router response
general_status the general status of the response
extended_status extended status in the case of an error otherwise 0
Returns:
status kEipStatusOk .. no reply need to be sent back kEipStatusOkSend .. need to send reply kEipStatusError .. error
Definition at line 965 of file cipconnectionmanager.c.
References AddDintToMessage(), AddIntToMessage(), CipMessageRouterResponse::additional_status, AddNullAddressItem(), CipCommonPacketFormatData::address_info_item, connection_object::cip_consumed_connection_id, connection_object::cip_produced_connection_id, connection_object::connection_serial_number, CipMessageRouterResponse::data, CipCommonPacketFormatData::data_item, CipMessageRouterResponse::data_length, g_common_packet_format_data_item, CipMessageRouterResponse::general_status, CipCommonPacketFormatData::item_count, kCipErrorNotEnoughData, kCipErrorSuccess, kCipErrorTooMuchData, kCipItemIdUnconnectedDataItem, kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionSize, kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionSize, kConnectionStateNonExistent, kEipStatusOkSend, kForwardOpen, connection_object::o_to_t_requested_packet_interval, OPENER_TRACE_INFO, connection_object::originator_serial_number, connection_object::originator_vendor_id, CipMessageRouterResponse::reply_service, CipMessageRouterResponse::size_of_additional_status, connection_object::state, connection_object::t_to_o_requested_packet_interval, DataItem::type_id, and SocketAddressInfoItem::type_id.
Referenced by ForwardOpen(), HandleNonNullMatchingForwardOpenRequest(), HandleNonNullNonMatchingForwardOpenRequest(), HandleNullMatchingForwardOpenRequest(), and HandleNullNonMatchingForwardOpenRequest().
EipStatus CheckElectronicKeyData (EipUint8 key_format, CipKeyData * key_data, EipUint16 * extended_status)
Compare the electronic key received with a forward open request with the device's data.
Parameters:
key_format format identifier given in the forward open request
key_data pointer to the electronic key data received in the forward open request
extended_status the extended error code in case an error happened
Returns:
general status on the establishment
EIP_OK ... on success
On an error the general status code to be put into the response
Definition at line 1205 of file cipconnectionmanager.c.
References CipKeyData::device_type, device_type_, kConnectionManagerExtendedStatusCodeErrorDeviceTypeError, kConnectionManagerExtendedStatusCodeErrorInvalidSegmentTypeInPath, kConnectionManagerExtendedStatusCodeErrorRevisionMismatch, kConnectionManagerExtendedStatusCodeErrorVendorIdOrProductcodeError, kConnectionManagerExtendedStatusCodeSuccess, kEipStatusError, kEipStatusOk, CipKeyData::major_revision, CipRevision::major_revision, CipKeyData::minor_revision, CipRevision::minor_revision, CipKeyData::product_code, product_code_, CipKeyData::vendor_id, and vendor_id_.
Referenced by ParseConnectionPath().
ConnectionObject * CheckForExistingConnection (ConnectionObject * connection_object)
check if the data given in the connection object match with an already established connection
The comparison is done according to the definitions in the CIP specification Section 3-5.5.2: The following elements have to be equal: Vendor ID, Connection Serial Number, Originator Serial Number
Parameters:
connection_object connection object containing the comparison elements from the forward open request
Returns:
NULL if no equal established connection exists
pointer to the equal connection object
Definition at line 1181 of file cipconnectionmanager.c.
References connection_object::connection_serial_number, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, connection_object::originator_serial_number, connection_object::originator_vendor_id, and connection_object::state.
Referenced by ForwardOpen().
void CloseConnection (ConnectionObject *RESTRICT connection_object)
Close the given connection.
This function will take the data form the connection and correctly closes the connection (e.g., open sockets)
Parameters:
connection_object pointer to the connection object structure to be closed
Definition at line 1582 of file cipconnectionmanager.c.
References CloseUdpSocket(), kConnectionStateNonExistent, kUdpCommuncationDirectionConsuming, kUdpCommuncationDirectionProducing, and RemoveFromActiveConnections().
Referenced by CloseAllConnections().
EipStatus ConnectionManagerInit (EipUint16 unique_connection_id)
Initialize the data of the connection manager object.
Parameters:
A unique connection id
Returns:
kEipStatusOk if successful, otherwise kEipStatusError
Definition at line 281 of file cipconnectionmanager.c.
References AddConnectableObject(), CreateCipClass(), EstablishClass3Connection(), EstablishIoConnection(), ForwardClose(), ForwardOpen(), g_incarnation_id, GetAttributeAll(), GetAttributeSingle(), GetConnectionOwner(), InitializeConnectionManager(), InitializeConnectionManagerData(), InsertService(), kEipStatusError, kEipStatusOk, kForwardClose, kForwardOpen, kGetAttributeAll, kGetAttributeSingle, and kGetConnectionOwner.
Referenced by CipStackInit().
void CopyConnectionData (ConnectionObject *RESTRICT destination, const ConnectionObject *RESTRICT const source)
Copy the given connection data from source to destination.
Parameters:
destination Destination of the copy operation
osurce Source of the copy operation
Definition at line 1598 of file cipconnectionmanager.c.
Referenced by EstablishClass3Connection(), and GetIoConnectionForConnectionData().
EipStatus ForwardClose (CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response, struct sockaddr * originator_address)
Definition at line 796 of file cipconnectionmanager.c.
References CipCommonPacketFormatData::address_info_item, AssembleForwardCloseResponse(), connection_object::connection_close_function, connection_object::connection_serial_number, CipMessageRouterRequest::data, g_active_connection_list, g_common_packet_format_data_item, GetDintFromMessage(), GetIntFromMessage(), kConnectionManagerExtendedStatusCodeErrorConnectionTargetConnectionNotFound, kConnectionManagerExtendedStatusCodeSuccess, kConnectionManagerExtendedStatusWrongCloser, kConnectionStateEstablished, kConnectionStateTimedOut, connection_object::next_connection_object, OPENER_ASSERT, OPENER_TRACE_INFO, connection_object::originator_address, connection_object::originator_serial_number, connection_object::originator_vendor_id, connection_object::state, and SocketAddressInfoItem::type_id.
Referenced by ConnectionManagerInit().
EipStatus ForwardOpen (CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response, struct sockaddr * originator_address)
Check if resources for new connection available, generate ForwardOpen Reply message.
Forward Open four cases Non-Null/Not matching - open a connection Non-Null/Matching - error Null/Not matching - ping a device/configure Null/Matching - reconfigure
Null connection - both O->T and T->O connection parameter field are null Non-Null connection - one or both O->T and T->O connection parameter field are not null Matching - Connection Triad matches an existing connection (Connection Serial Number, Originator Vendor ID and Originator Serial Number)
Parameters:
instance pointer to CIP object instance
message_router_request pointer to Message Router Request.
message_router_response pointer to Message Router Response.
Returns:
>0 .. success, 0 .. no reply to send back -1 .. error
Definition at line 654 of file cipconnectionmanager.c.
References AssembleForwardOpenResponse(), CheckForExistingConnection(), GetConnectionType(), kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionType, kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionType, kForwardOpenConnectionTypeNull, kForwardOpenConnectionTypeReserved, connection_object::o_to_t_network_connection_parameter, OPENER_TRACE_INFO, connection_object::originator_address, ReadOutConnectionObjectFromMessage(), and connection_object::t_to_o_network_connection_parameter.
Referenced by ConnectionManagerInit().
void GeneralConnectionConfiguration (ConnectionObject * connection_object)
Generate the ConnectionIDs and set the general configuration parameter in the given connection object.
Parameters:
connection_object pointer to the connection object that should be set up.
Definition at line 733 of file cipconnectionmanager.c.
References connection_object::cip_consumed_connection_id, connection_object::cip_produced_connection_id, connection_object::consumed_connection_size, connection_object::eip_level_sequence_count_consuming, connection_object::eip_level_sequence_count_producing, connection_object::expected_packet_rate, GetConnectionId(), GetConnectionObjectInitialInactivityWatchdogTimerValue(), connection_object::inactivity_watchdog_timer, kForwardOpenConnectionTypeMulticastConnection, kForwardOpenConnectionTypePointToPointConnection, kWatchdogTimeoutActionAutoDelete, connection_object::o_to_t_network_connection_parameter, connection_object::produced_connection_size, connection_object::production_inhibit_time, connection_object::production_inhibit_timer, connection_object::sequence_count_consuming, connection_object::sequence_count_producing, connection_object::t_to_o_network_connection_parameter, connection_object::transmission_trigger_timer, connection_object::transport_type_class_trigger, and connection_object::watchdog_timeout_action.
Referenced by EstablishClass3Connection(), and EstablishIoConnection().
ConnectionObject* GetConnectedObject (EipUint32 connection_id)
Definition at line 1144 of file cipconnectionmanager.c.
References connection_object::cip_consumed_connection_id, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, and connection_object::state.
Referenced by HandleReceivedConnectedData(), and NotifyConnectedCommonPacketFormat().
ConnectionObject* GetConnectedOutputAssembly (EipUint32 output_assembly_id)
Get a connection object for a given output assembly.
Parameters:
output_assembly_id requested output assembly of requested connection
Returns:
pointer to connected Object 0 .. connection not present in device
Definition at line 1161 of file cipconnectionmanager.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, and connection_object::state.
Referenced by GetExclusiveOwnerConnection().
EipUint32 GetConnectionId (void)
Generate a new connection Id utilizing the Incarnation Id as described in the EIP specs.
A unique connectionID is formed from the boot-time-specified "incarnation ID" and the per-new-connection-incremented connection number/counter.
Returns:
new connection id
Definition at line 251 of file cipconnectionmanager.c.
References g_incarnation_id.
Referenced by GeneralConnectionConfiguration().
ConnectionManagementHandling * GetConnectionManagementEntry (EipUint32 class_id)
Definition at line 1670 of file cipconnectionmanager.c.
Referenced by HandleNonNullNonMatchingForwardOpenRequest().
EipUint32 GetConnectionObjectInactivityWatchdogTimerValue (ConnectionObject * connection_object)
Definition at line 727 of file cipconnectionmanager.c.
References connection_object::connection_timeout_multiplier, and connection_object::o_to_t_requested_packet_interval.
Referenced by GetConnectionObjectInitialInactivityWatchdogTimerValue(), HandleReceivedConnectedData(), and NotifyConnectedCommonPacketFormat().
EipUint32 GetConnectionObjectInitialInactivityWatchdogTimerValue (ConnectionObject * connection_object)
Definition at line 719 of file cipconnectionmanager.c.
References GetConnectionObjectInactivityWatchdogTimerValue().
Referenced by GeneralConnectionConfiguration().
ConnectionObjectFixedVariable GetConnectionObjectTargetToOriginatorFixedOrVariableConnectionSize (const ConnectionObject *const RESTRICT connection_object)
Definition at line 109 of file cipconnectionmanager.c.
References kConnectionObjectFixedConnectionSize, and kConnectionObjectVariableConnectionSize.
Referenced by SetupIoConnectionTargetToOriginatorConnectionPoint().
ForwardOpenPriority GetConnectionObjectTToOPriority (const ConnectionObject *const connection_object)
Definition at line 456 of file cipconnectionmanager.c.
References GetPriorityForSocket(), and connection_object::t_to_o_network_connection_parameter.
Referenced by OpenConsumingPointToPointConnection(), OpenMulticastConnection(), OpenProducingPointToPointConnection(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
EipStatus GetConnectionOwner (CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response, struct sockaddr * originator_address)
Definition at line 868 of file cipconnectionmanager.c.
References kEipStatusOk.
Referenced by ConnectionManagerInit().
ForwardOpenConnectionType GetConnectionType (EipUint16 network_connection_parameter)
returns the connection type of the supplied network connection parameter
Definition at line 442 of file cipconnectionmanager.c.
References OPENER_TRACE_INFO.
Referenced by EstablishIoConnection(), ForwardOpen(), OpenCommunicationChannels(), and ParseConnectionPath().
unsigned int GetPaddedLogicalPath (const EipUint8 ** logical_path_segment)
gets the padded logical path TODO: enhance documentation
Parameters:
logical_path_segment TheLogical Path Segment
Returns:
The padded logical path
Definition at line 229 of file cipconnectionmanager.c.
References OPENER_TRACE_ERR.
Referenced by ParseConnectionPath().
CipUint GetProductionInhibitTime (const ConnectionObject *const connection_object)
Definition at line 91 of file cipconnectionmanager.c.
References connection_object::production_inhibit_time.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
ProductionTrigger GetProductionTrigger (const ConnectionObject *const connection_object)
Definition at line 53 of file cipconnectionmanager.c.
References kProductionTriggerApplicationObjectTriggered, kProductionTriggerChangeOfState, kProductionTriggerCyclic, kProductionTriggerInvalid, and connection_object::transport_type_class_trigger.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
CipUdint GetTargetToOriginatorRequestedPackedInterval (const ConnectionObject *const RESTRICT connection_object)
Definition at line 103 of file cipconnectionmanager.c.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
EipStatus HandleNonNullMatchingForwardOpenRequest (ConnectionObject * connection_object, CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response)
Handles a Non Null Matching Forward Open Request.
Non-Null, Matching request - Return General Status = kCipErrorConnectionFailure, Extended Status = kConnectionManagerExtendedStatusCodeErrorConnectionInUseOrDuplicateForwardOpen
Definition at line 542 of file cipconnectionmanager.c.
References AssembleForwardOpenResponse(), kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeErrorConnectionInUseOrDuplicateForwardOpen, and OPENER_TRACE_INFO.
EipStatus HandleNonNullNonMatchingForwardOpenRequest (ConnectionObject * connection_object, CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response)
Handles a Non Null Non Matching Forward Open Request.
Non-Null, Non-Matching request - Establish a new connection
Definition at line 566 of file cipconnectionmanager.c.
References AssembleForwardOpenResponse(), CipConnectionPath::class_id, connection_object::connection_path, GetConnectionManagementEntry(), kCipErrorConnectionFailure, kCipErrorSuccess, kConnectionManagerExtendedStatusCodeErrorTransportClassAndTriggerCombinationNotSupported, kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo, kConnectionManagerExtendedStatusCodeSuccess, kEipStatusError, kEipStatusOk, ConnectionManagementHandling::open_connection_function, OPENER_TRACE_INFO, ParseConnectionPath(), and connection_object::transport_type_class_trigger.
EipStatus HandleNullMatchingForwardOpenRequest (ConnectionObject * connection_object, CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response)
Handles a Null Matching Forward Open request.
Either reconfigure a target devices application, or return General Status kCipErrorConnectionFailure and Extended Status kConnectionManagerExtendedStatusCodeNullForwardOpenNotSupported
Definition at line 517 of file cipconnectionmanager.c.
References AssembleForwardOpenResponse(), kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeNullForwardOpenNotSupported, and OPENER_TRACE_INFO.
EipStatus HandleNullNonMatchingForwardOpenRequest (ConnectionObject * connection_object, CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response)
Handles a Null Non Matching Forward Open Request.
Null, Non-Matching - Either ping device, or configure a devices application, or return General Status kCipErrorConnectionFailure and Extended Status kConnectionManagerExtendedStatusCodeNullForwardOpenNotSupported
Definition at line 491 of file cipconnectionmanager.c.
References AssembleForwardOpenResponse(), kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeNullForwardOpenNotSupported, and OPENER_TRACE_INFO.
void InitializeConnectionManager (CipClass * class)
Definition at line 257 of file cipconnectionmanager.c.
References cip_instance::cip_class, cip_class::class_instance, cip_class::highest_attribute_number, InsertAttribute(), kCipUint, kGetableSingle, kGetableSingleAndAll, and kNotSetOrGetable.
Referenced by ConnectionManagerInit().
void InitializeConnectionManagerData (void)
Definition at line 1708 of file cipconnectionmanager.c.
References InitializeClass3ConnectionData(), and InitializeIoConnectionData().
Referenced by ConnectionManagerInit().
EipBool8 IsConnectedOutputAssembly (const EipUint32 instance_number)
Definition at line 1633 of file cipconnectionmanager.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, and connection_object::next_connection_object.
Referenced by SetAssemblyAttributeSingle().
EipUint8 ParseConnectionPath (ConnectionObject * connection_object, CipMessageRouterRequest * message_router_request, EipUint16 * extended_error)
Parse the connection path of a forward open request.
This function will take the connection object and the received data stream and parse the connection path.
Parameters:
connection_object pointer to the connection object structure for which the connection should be established
message_router_request pointer to the received request structure. The position of the data stream pointer has to be at the connection length entry
extended_status the extended error code in case an error happened
Returns:
general status on the establishment
EIP_OK ... on success
On an error the general status code to be put into the response
Definition at line 1280 of file cipconnectionmanager.c.
References CheckElectronicKeyData(), CipConnectionPath::class_id, connection_object::connection_path, connection_object::connection_path_size, CipConnectionPath::connection_point, CipMessageRouterRequest::data, CipKeyData::device_type, connection_object::electronic_key, ElectronicKeyFormat4Delete(), ElectronicKeyFormat4GetDeviceType(), ElectronicKeyFormat4GetMajorRevision(), ElectronicKeyFormat4GetMajorRevisionCompatibility(), ElectronicKeyFormat4GetMinorRevision(), ElectronicKeyFormat4GetProductCode(), ElectronicKeyFormat4GetVendorId(), ElectronicKeyFormat4New(), EQLOGICALPATH, g_config_data_buffer, g_config_data_length, g_kForwardOpenHeaderLength, GetCipClass(), GetCipInstance(), GetConnectionType(), GetPaddedLogicalPath(), GetPathDataSegmentSubtype(), GetPathLogicalSegmentElectronicKeyFormat(), GetPathLogicalSegmentElectronicKeyFormat4(), GetPathLogicalSegmentLogicalType(), GetPathLogicalSegmentSpecialTypeLogicalType(), GetPathNetworkSegmentSubtype(), GetPathSegmentType(), kCipErrorConnectionFailure, kCipErrorNotEnoughData, kCipErrorPathSegmentError, kCipErrorTooMuchData, kConnectionManagerExtendedStatusCodeErrorInvalidSegmentTypeInPath, kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo, kConnectionTriggerTypeCyclicConnection, kConnectionTriggerTypeProductionTriggerMask, kDataSegmentSubtypeSimpleData, kEipStatusOk, kElectronicKeySegmentFormatKeyFormat4, CipElectronicKey::key_data, CipElectronicKey::key_format, kForwardOpenConnectionTypeReserved, kLogicalSegmentLogicalTypeSpecial, kLogicalSegmentSpecialTypeLogicalFormatElectronicKey, kNetworkSegmentSubtypeProductionInhibitTimeInMilliseconds, kSegmentTypeDataSegment, kSegmentTypeLogicalSegment, kSegmentTypeNetworkSegment, CipKeyData::major_revision, CipKeyData::minor_revision, connection_object::o_to_t_network_connection_parameter, OPENER_TRACE_ERR, OPENER_TRACE_INFO, OPENER_TRACE_WARN, CipKeyData::product_code, connection_object::production_inhibit_time, CipMessageRouterRequest::request_path_size, CipElectronicKey::segment_type, connection_object::t_to_o_network_connection_parameter, connection_object::transport_type_class_trigger, and CipKeyData::vendor_id.
Referenced by HandleNonNullNonMatchingForwardOpenRequest().
void ReadOutConnectionObjectFromMessage (CipMessageRouterRequest *const message_router_request, ConnectionObject *const connection_object)
Definition at line 381 of file cipconnectionmanager.c.
References connection_object::cip_consumed_connection_id, connection_object::cip_produced_connection_id, connection_object::connection_serial_number, connection_object::connection_timeout_multiplier, CipMessageRouterRequest::data, GetDintFromMessage(), GetIntFromMessage(), kConnectionStateNonExistent, connection_object::o_to_t_network_connection_parameter, connection_object::o_to_t_requested_packet_interval, OPENER_TRACE_INFO, connection_object::originator_serial_number, connection_object::originator_vendor_id, connection_object::priority_timetick, connection_object::sequence_count_producing, connection_object::state, connection_object::t_to_o_network_connection_parameter, connection_object::t_to_o_requested_packet_interval, connection_object::timeout_ticks, and connection_object::transport_type_class_trigger.
Referenced by ForwardOpen().
void RemoveFromActiveConnections (ConnectionObject * connection_object)
Removes connection from the list of active connections.
Parameters:
connection_object Connection object to be removed from the active connection list
Definition at line 1615 of file cipconnectionmanager.c.
References connection_object::first_connection_object, kConnectionStateNonExistent, connection_object::next_connection_object, and connection_object::state.
Referenced by CloseCommunicationChannelsAndRemoveFromActiveConnectionsList(), CloseConnection(), and EstablishClass3Connection().
void SetProductionInhibitTime (const EipUint16 production_inhibit_time, ConnectionObject *const connection_object)
Definition at line 96 of file cipconnectionmanager.c.
References connection_object::production_inhibit_time.
Referenced by ProcessProductionInhibitTime().
void SetProductionTrigger (const enum ProductionTrigger production_trigger, ConnectionObject * connection_object)
< Invalid value
Definition at line 70 of file cipconnectionmanager.c.
References kProductionTriggerApplicationObjectTriggered, kProductionTriggerChangeOfState, kProductionTriggerCyclic, and connection_object::transport_type_class_trigger.
Variable Documentation
EipUint16 device_type_
Attribute 2: Device Type
Definition at line 41 of file cipidentity.c.
Referenced by CheckElectronicKeyData(), CipIdentityInit(), and EncapsulateListIdentyResponseMessage().
ConnectionObject* g_active_connection_list = NULL
List holding all currently active connections.
External globals needed from connectionmanager.c.
An implicit list structure inside the ConnectionObject, so the g_active_connection_list holds the first element of the list
Definition at line 134 of file cipconnectionmanager.c.
Referenced by AddNewActiveConnection(), CheckAndHandleConsumingUdpSockets(), CheckForExistingConnection(), CloseAllConnections(), CloseAllConnectionsForInputWithSameType(), ConnectionWithSameConfigPointExists(), ForwardClose(), GetConnectedObject(), GetConnectedOutputAssembly(), GetExistingProducerMulticastConnection(), GetNextNonControlMasterConnection(), IsConnectedOutputAssembly(), ManageConnections(), SetupIoConnectionTargetToOriginatorConnectionPoint(), and TriggerConnections().
ConnectionManagementHandling g_connection_management_list[2+OPENER_CIP_NUM_APPLICATION_SPECIFIC_CONNECTABLE_OBJECTS]
List holding information on the object classes and open/close function pointers to which connections may be established.
Definition at line 128 of file cipconnectionmanager.c.
ConnectionObject g_dummy_connection_object
buffer connection object needed for forward open
Definition at line 137 of file cipconnectionmanager.c.
EipUint32 g_incarnation_id
Holds the connection ID's "incarnation ID" in the upper 16 bits.
Definition at line 140 of file cipconnectionmanager.c.
Referenced by ConnectionManagerInit(), and GetConnectionId().
const int g_kForwardOpenHeaderLength = 36
the length in bytes of the forward open command specific data till the start of the connection path (including con path size)
Definition at line 39 of file cipconnectionmanager.c.
Referenced by ParseConnectionPath().
EipUint16 product_code_
Attribute 3: Product Code
Definition at line 42 of file cipidentity.c.
Referenced by CheckElectronicKeyData(), CipIdentityInit(), and EncapsulateListIdentyResponseMessage().
CipRevision revision_
Attribute 4: Revision / USINT Major, USINT Minor
Definition at line 43 of file cipidentity.c.
EipUint16 vendor_id_
Attribute 1: Vendor ID
Definition at line 40 of file cipidentity.c.
Referenced by CheckElectronicKeyData(), CipIdentityInit(), and EncapsulateListIdentyResponseMessage().