OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipassembly.h File Reference
cipassembly.h File Reference
#include "typedefs.h"
#include "ciptypes.h"
Macros
#define CIP_ASSEMBLY_CLASS_CODE 0x04
Functions
EIP_STATUS CIP_Assembly_Init (void)
EIP_STATUS notifyAssemblyConnectedDataReceived (S_CIP_Instance *pa_pstInstance, EIP_UINT8 *pa_pnData, EIP_UINT16 pa_nDatalength)
void shutdownAssemblies (void)
clean up the data allocated in the assembly object instances
Macro Definition Documentation
#define CIP_ASSEMBLY_CLASS_CODE 0x04
Definition at line 12 of file cipassembly.h.
Referenced by Connection_Manager_Init(), createAssemblyClass(), createAssemblyObject(), establishIOConnction(), getAttributeSingle(), and shutdownAssemblies().
Function Documentation
EIP_STATUS CIP_Assembly_Init (void)
Setup the Assembly object
Creates the Assembly Class with zero instances and sets up all services.
Definition at line 45 of file cipassembly.c.
References createAssemblyClass(), EIP_ERROR, and EIP_OK.
Referenced by CIP_Init().
EIP_STATUS notifyAssemblyConnectedDataReceived (S_CIP_Instance * pa_pstInstance, EIP_UINT8 * pa_pnData, EIP_UINT16 pa_nDatalength)
notify an Assembly object that data has been received for it.
The data will be copied into the assembly objects attribute 3 and the application will be informed with the IApp_after_assembly_data_received function.
Parameters
pa_pstInstance the assembly object instance for which the data was received
pa_pnData pointer to the data received
pa_nDatalength number of bytes received
Returns
EIP_OK the received data was okay
EIP_ERROR the received data was wrong
Definition at line 106 of file cipassembly.c.
References CIPByteArray::Data, EIP_ERROR, IApp_AfterAssemblyDataReceived(), CIPByteArray::Length, OPENER_TRACE_ERR, CIP_Instance::pstAttributes, and CIPAttributeStruct::pt2data.
Referenced by handleConfigData(), and handleReceivedIOConnData().
void shutdownAssemblies (void)
clean up the data allocated in the assembly object instances
Assembly object instances allocate per instance data to store attribute 3. This will be freed here. The assembly object data given by the application is not freed neither the assembly object instances. These are handled in the main shutdown function.
Definition at line 51 of file cipassembly.c.
References CIP_ASSEMBLY_CLASS_CODE, getAttribute(), getCIPClass(), IApp_CipFree(), CIP_Class::pstInstances, CIP_Instance::pstNext, and CIPAttributeStruct::pt2data.
Referenced by shutdownCIP().