OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipidentity.h File Reference
cipidentity.h File Reference
#include "typedefs.h"
#include "ciptypes.h"
Macros
#define CIP_IDENTITY_CLASS_CODE 0x01
#define CIP_IDENTITY_EXTENDED_STATUS_AT_LEAST_ONE_FAULTED_IO_CONNECTION 0x0020
#define CIP_IDENTITY_EXTENDED_STATUS_AT_LEAST_ONE_IO_CONNECTION_ESTABLISHED_ALL_IN_IDLE_MODE 0x0070
#define CIP_IDENTITY_EXTENDED_STATUS_AT_LEAST_ONE_IO_CONNECTION_IN_RUN_MODE 0x0060
#define CIP_IDENTITY_EXTENDED_STATUS_FIRMEWARE_UPDATE_IN_PROGRESS 0x0010
#define CIP_IDENTITY_EXTENDED_STATUS_MAJOR_FAULT 0x0050
#define CIP_IDENTITY_EXTENDED_STATUS_NO_IO_CONNECTIONS_ESTABLISHED 0x0030
#define CIP_IDENTITY_EXTENDED_STATUS_NON_VOLATILE_CONFIGURATION_BAD 0x0040
#define CIP_IDENTITY_EXTENDED_STATUS_SELFTESTING_UNKNOWN 0x0000
#define CIP_IDENTITY_STATUS_CONFIGURED 0x0004
#define CIP_IDENTITY_STATUS_MAJOR_RECOV_FLT 0x0400
#define CIP_IDENTITY_STATUS_MAJOR_UNRECOV_FLT 0x0800
#define CIP_IDENTITY_STATUS_MINOR_RECOV_FLT 0x0100
#define CIP_IDENTITY_STATUS_MINOR_UNRECOV_FLT 0x0200
#define CIP_IDENTITY_STATUS_OWNED 0x0001
Functions
EIP_STATUS CIP_Identity_Init (void)
Macro Definition Documentation
#define CIP_IDENTITY_CLASS_CODE 0x01
Definition at line 12 of file cipidentity.h.
Referenced by CIP_Identity_Init().
#define CIP_IDENTITY_EXTENDED_STATUS_AT_LEAST_ONE_FAULTED_IO_CONNECTION 0x0020
Definition at line 23 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_AT_LEAST_ONE_IO_CONNECTION_ESTABLISHED_ALL_IN_IDLE_MODE 0x0070
Definition at line 28 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_AT_LEAST_ONE_IO_CONNECTION_IN_RUN_MODE 0x0060
Definition at line 27 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_FIRMEWARE_UPDATE_IN_PROGRESS 0x0010
Definition at line 22 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_MAJOR_FAULT 0x0050
Definition at line 26 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_NO_IO_CONNECTIONS_ESTABLISHED 0x0030
Definition at line 24 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_NON_VOLATILE_CONFIGURATION_BAD 0x0040
Definition at line 25 of file cipidentity.h.
#define CIP_IDENTITY_EXTENDED_STATUS_SELFTESTING_UNKNOWN 0x0000
Definition at line 21 of file cipidentity.h.
#define CIP_IDENTITY_STATUS_CONFIGURED 0x0004
Definition at line 15 of file cipidentity.h.
#define CIP_IDENTITY_STATUS_MAJOR_RECOV_FLT 0x0400
Definition at line 18 of file cipidentity.h.
#define CIP_IDENTITY_STATUS_MAJOR_UNRECOV_FLT 0x0800
Definition at line 19 of file cipidentity.h.
#define CIP_IDENTITY_STATUS_MINOR_RECOV_FLT 0x0100
Definition at line 16 of file cipidentity.h.
#define CIP_IDENTITY_STATUS_MINOR_UNRECOV_FLT 0x0200
Definition at line 17 of file cipidentity.h.
#define CIP_IDENTITY_STATUS_OWNED 0x0001
Definition at line 14 of file cipidentity.h.
Function Documentation
EIP_STATUS CIP_Identity_Init (void)
CIP Identity object contructor
Returns
EIP_ERROR if the class could not be created, otherwise EIP_OK
CIP Identity object constructor
Returns
EIP_ERROR if the class could not be created, otherwise EIP_OK
Definition at line 132 of file cipidentity.c.
References CIP_ATTRIB_GETABLE, CIP_IDENTITY_CLASS_CODE, CIP_RESET, CIP_SHORT_STRING, CIP_UDINT, CIP_UINT, CIP_USINT_USINT, CIP_WORD, createCIPClass(), DeviceType, EIP_ERROR, EIP_OK, getCIPInstance(), ID_Status, insertAttribute(), insertService(), MASK4, MASK7, ProductCode, SerialNumber, and VendorID.
Referenced by CIP_Init().