OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/LM3S8962/sample_application/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <stdlib.h>
#include <math.h>
#include "hw_ints.h"
#include "hw_memmap.h"
#include "hw_nvic.h"
#include "hw_types.h"
#include "driverlib/ethernet.h"
#include "driverlib/flash.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "lwiplib.h"
#include "flashmgr.h"
#include "networkhandler.h"
#include <opener_api.h>
#include "cipcommon.h"
#include "random.h"
#include <trace.h>
Data Structures
struct parm
Macros
#define ETHERNET_INT_PRIORITY 0xC2
#define SYSTICK_INT_PRIORITY 0xF0
#define SYSTICKHZ 100
#define SYSTICKMS (1000 / SYSTICKHZ)
#define SYSTICKNS (1000000000 / SYSTICKHZ)
#define SYSTICKUS (1000000 / SYSTICKHZ)
#define useStaticIP 0
Functions
int _EXFUN (rand,(_VOID))
_VOID _EXFUN (srand,(unsigned __seed))
void lwIPHostTimerHandler (void)
int main (void)
void setCIPaddress (unsigned long addr, unsigned long mask, unsigned long gw)
void SysTickIntHandler (void)
Variables
volatile unsigned long g_ulSystemTimeNanoSeconds
volatile unsigned long g_ulSystemTimeSecfunctiononds
Macro Definition Documentation
#define ETHERNET_INT_PRIORITY 0xC2
Definition at line 95 of file main.c.
Referenced by main().
#define SYSTICK_INT_PRIORITY 0xF0
Definition at line 94 of file main.c.
Referenced by main().
#define SYSTICKHZ 100
Definition at line 82 of file main.c.
Referenced by main().
#define SYSTICKMS (1000 / SYSTICKHZ)
Definition at line 83 of file main.c.
Referenced by SysTickIntHandler().
#define SYSTICKNS (1000000000 / SYSTICKHZ)
Definition at line 85 of file main.c.
Referenced by SysTickIntHandler().
#define SYSTICKUS (1000000 / SYSTICKHZ)
Definition at line 84 of file main.c.
#define useStaticIP 0
Definition at line 62 of file main.c.
Referenced by main().
Function Documentation
int _EXFUN (rand , (_VOID))
Definition at line 307 of file main.c.
References nextXorShiftUInt32().
_VOID _EXFUN (srand , (unsigned __seed))
Definition at line 312 of file main.c.
References setXorShiftSeed().
void lwIPHostTimerHandler (void)
Definition at line 133 of file main.c.
References setCIPaddress().
int main (void)
Definition at line 152 of file main.c.
References CIP_Init(), configureMACAddress(), ETHERNET_INT_PRIORITY, findNextEmptyParameterBlock(), OPENER_TRACE_INFO, setDeviceSerialNumber(), Start_NetworkHandler(), SYSTICK_INT_PRIORITY, SYSTICKHZ, and useStaticIP.
void setCIPaddress (unsigned long addr, unsigned long mask, unsigned long gw)
Definition at line 111 of file main.c.
References configureDomainName(), configureHostName(), and configureNetworkInterface().
Referenced by lwIPHostTimerHandler().
void SysTickIntHandler (void)
Definition at line 325 of file main.c.
References g_ulSystemTimeNanoSeconds, SYSTICKMS, and SYSTICKNS.
Variable Documentation
volatile unsigned long g_ulSystemTimeNanoSeconds
Definition at line 57 of file main.c.
Referenced by SysTickIntHandler().
volatile unsigned long g_ulSystemTimeSecfunctiononds
Definition at line 56 of file main.c.