OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/utils/xorshiftrandom.h File Reference
xorshiftrandom.h File Reference
#include <stdint.h>
Functions
uint32_t nextXorShiftUInt32 (void)
void setXorShiftSeed (uint32_t pa_nSeed)
Detailed Description
The public interface of the XOR shift pseudo-random number generator
Definition in file xorshiftrandom.h.
Function Documentation
uint32_t nextXorShiftUInt32 (void)
Returns the next generated pseudo-random number
Returns
The next pseudo-random number
Definition at line 28 of file xorshiftrandom.c.
References calculateNextSeed().
Referenced by _EXFUN().
void setXorShiftSeed (uint32_t pa_nSeed)
Sets the initial seed for the XOR shift pseudo-random algorithm
Parameters
pa_nSeed The initial seed value
< File-global variable holding the current seed
Definition at line 12 of file xorshiftrandom.c.
Referenced by _EXFUN().