OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/appcontype.h File Reference
src/cip/appcontype.h File Reference
#include "cipconnectionmanager.h"
Functions
void CloseAllConnections (void)
void CloseAllConnectionsForInputWithSameType (const EipUint32 input_point, const ConnectionObjectConnectionType instance_type)
Close all connection producing the same input and have the same type (i.e., listen only or input only).
bool ConnectionWithSameConfigPointExists (const EipUint32 config_point)
Check if there is an established connection that uses the same config point.
CipConnectionObject * GetExistingProducerMulticastConnection (const EipUint32 input_point)
Check if there exists already an exclusive owner or listen only connection which produces the input assembly.
CipConnectionObject * GetIoConnectionForConnectionData (CipConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
check if for the given connection data received in a forward_open request a suitable connection is available.
CipConnectionObject * GetNextNonControlMasterConnection (const EipUint32 input_point)
check if there exists an producing multicast exclusive owner or listen only connection that should produce the same input but is not in charge of the connection.
void InitializeIoConnectionData (void)
Variables
DoublyLinkedList connection_list
Function Documentation
void CloseAllConnections (void)
@ brief close all open connections.
For I/O connections the sockets will be freed. The sockets for explicit connections are handled by the encapsulation layer, and freed there.
Definition at line 374 of file appcontype.c.
References cip_connection_object::connection_close_function, connection_list, doubly_linked_list_node::data, DoublyLinkedListRemoveNode(), and DoublyLinkedList::first.
Referenced by ResetDevice(), and ShutdownCipStack().
void CloseAllConnectionsForInputWithSameType (const EipUint32 input_point, const ConnectionObjectConnectionType instance_type)
Close all connection producing the same input and have the same type (i.e., listen only or input only).
Parameters:
input_point the input point
instance_type the connection application type
Definition at line 349 of file appcontype.c.
References CheckIoConnectionEvent(), cip_connection_object::connection_close_function, connection_list, cip_connection_object::consumed_path, doubly_linked_list_node::data, DoublyLinkedList::first, connection_path_epath::instance_id, cip_connection_object::instance_type, kIoConnectionEventClosed, doubly_linked_list_node::next, and cip_connection_object::produced_path.
Referenced by CloseIoConnection(), and HandleIoConnectionTimeOut().
bool ConnectionWithSameConfigPointExists (const EipUint32 config_point)
Check if there is an established connection that uses the same config point.
Parameters:
config_point The configuration point
Returns:
true if connection was found, otherwise false
Definition at line 389 of file appcontype.c.
References cip_connection_object::configuration_path, connection_list, doubly_linked_list_node::data, DoublyLinkedList::first, connection_path_epath::instance_id, and doubly_linked_list_node::next.
Referenced by HandleConfigData().
CipConnectionObject* GetExistingProducerMulticastConnection (const EipUint32 input_point)
Check if there exists already an exclusive owner or listen only connection which produces the input assembly.
Parameters:
input_point the Input point to be produced
Returns:
if a connection could be found a pointer to this connection if not NULL
Definition at line 293 of file appcontype.c.
References connection_list, ConnectionObjectGetTToOConnectionType(), ConnectionObjectIsTypeIOConnection(), doubly_linked_list_node::data, DoublyLinkedList::first, connection_path_epath::instance_id, kConnectionObjectConnectionTypeMulticast, kUdpCommuncationDirectionProducing, doubly_linked_list_node::next, cip_connection_object::produced_path, and cip_connection_object::socket.
Referenced by GetListenOnlyConnection(), and OpenProducingMulticastConnection().
CipConnectionObject* GetIoConnectionForConnectionData (CipConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
check if for the given connection data received in a forward_open request a suitable connection is available.
If a suitable connection is found the connection data is transfered the application connection type is set (i.e., EConnType).
Parameters:
connection_object connection data to be used
extended_error pointer to the extended_error variable, if an error occurred this value has the according error code for the response
Returns:
on success: A pointer to the connection object already containing the connection data given in connection_object.
on error: NULL
Definition at line 127 of file appcontype.c.
References ConnectionObjectDeepCopy(), ConnectionObjectSetInstanceType(), GetExclusiveOwnerConnection(), GetInputOnlyConnection(), GetListenOnlyConnection(), kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo, kConnectionObjectInstanceTypeIOExclusiveOwner, kConnectionObjectInstanceTypeIOInputOnly, and kConnectionObjectInstanceTypeIOListenOnly.
Referenced by EstablishIoConnection().
CipConnectionObject* GetNextNonControlMasterConnection (const EipUint32 input_point)
check if there exists an producing multicast exclusive owner or listen only connection that should produce the same input but is not in charge of the connection.
Parameters:
input_point the produced input
Returns:
if a connection could be found the pointer to this connection otherwise NULL.
Definition at line 320 of file appcontype.c.
References connection_list, ConnectionObjectGetState(), ConnectionObjectGetTToOConnectionType(), ConnectionObjectIsTypeIOConnection(), doubly_linked_list_node::data, DoublyLinkedList::first, connection_path_epath::instance_id, kConnectionObjectConnectionTypeMulticast, kConnectionObjectStateEstablished, kUdpCommuncationDirectionProducing, doubly_linked_list_node::next, cip_connection_object::produced_path, and cip_connection_object::socket.
Referenced by CloseIoConnection(), and HandleIoConnectionTimeOut().
void InitializeIoConnectionData (void)
Definition at line 402 of file appcontype.c.
References OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS, OPENER_CIP_NUM_INPUT_ONLY_CONNS, and OPENER_CIP_NUM_LISTEN_ONLY_CONNS.
Referenced by InitializeConnectionManagerData().
Variable Documentation
DoublyLinkedList connection_list
Definition at line 53 of file cipconnectionobject.c.
Referenced by CheckAndHandleConsumingUdpSockets(), CloseAllConnections(), CloseAllConnectionsForInputWithSameType(), ConnectionWithSameConfigPointExists(), GetExistingProducerMulticastConnection(), GetNextNonControlMasterConnection(), main(), and SetupIoConnectionTargetToOriginatorConnectionPoint().