OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/LM3S8962/networkhandler.h File Reference
networkhandler.h File Reference
#include "typedefs.h"
Functions
EIP_STATUS Start_NetworkHandler (void)
Function Documentation
EIP_STATUS Start_NetworkHandler (void)
Start a TCP/UDP listening socket, accept connections, receive data in select loop, call manageConnections periodically.
Returns
status EIP_ERROR .. error
Definition at line 267 of file networkhandler.c.
References AF_INET, EIP_OK, INADDR_ANY, my_addr, OPENER_ETHERNET_PORT, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, sockaddr_in::sin_zero, tcp_connection_accept_callback(), and udp_unsolicited_receive_callback().
Referenced by main().