OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipqos.h File Reference
src/cip/cipqos.h File Reference
Public interface of the QoS Object.
#include "typedefs.h"
#include "ciptypes.h"
#include "cipconnectionmanager.h"
Functions
EipStatus CipQoSInit (void)
CipUsint GetPriorityForSocket (ConnectionObjectPriority priority)
Initializing the data structures of the TCP/IP interface object.
Detailed Description
Public interface of the QoS Object.
Definition in file cipqos.h.
Function Documentation
EipStatus CipQoSInit (void)
Definition at line 120 of file cipqos.c.
References CreateCipClass(), dscp_event, dscp_explicit, dscp_general, dscp_high, dscp_low, dscp_scheduled, dscp_urgent, GetAttributeSingleQoS(), GetCipInstance(), InitializeCipQos(), InsertAttribute(), InsertService(), kCipUsint, kEipStatusError, kEipStatusOk, kGetableSingle, kGetAttributeSingle, kNotSetOrGetable, kSetable, kSetAttributeSingle, q_frames_enable, and SetAttributeSingleQoS().
Referenced by CipStackInit().
CipUsint GetPriorityForSocket (ConnectionObjectPriority priority)
Initializing the data structures of the TCP/IP interface object.
Definition at line 90 of file cipqos.c.
References dscp_explicit, dscp_high, dscp_low, dscp_scheduled, dscp_urgent, kConnectionObjectPriorityHigh, kConnectionObjectPriorityLow, kConnectionObjectPriorityScheduled, and kConnectionObjectPriorityUrgent.
Referenced by CheckAndHandleTcpListenerSocket(), and CreateUdpSocket().