OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/WIN32/main.c File Reference
src/ports/WIN32/main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include "generic_networkhandler.h"
#include "opener_api.h"
#include "cipcommon.h"
#include "trace.h"
Functions
void LeaveStack (int pa_nSig)
Signal handler function for ending stack execution.
int main (int argc, char *arg[])
Variables
int g_end_stack = 0
Flag indicating if the stack should end its execution.
int newfd
Function Documentation
void LeaveStack (int pa_nSig)
Signal handler function for ending stack execution.
Parameters:
pa_nSig the signal we received
int main (int argc, char * arg[])
Definition at line 31 of file main.c.
References CipStackInit(), ConfigureDomainName(), ConfigureHostName(), ConfigureMacAddress(), ConfigureNetworkInterface(), g_end_stack, kEipStatusOk, LeaveStack(), NetworkHandlerFinish(), NetworkHandlerInitialize(), NetworkHandlerProcessOnce(), SetDeviceSerialNumber(), and ShutdownCipStack().
Variable Documentation
int g_end_stack = 0
Flag indicating if the stack should end its execution.
Definition at line 28 of file main.c.
int newfd