OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/generic_networkhandler.h File Reference
src/ports/generic_networkhandler.h File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include "opener_api.h"
#include "typedefs.h"
#include "endianconv.h"
#include "cipconnectionmanager.h"
#include "networkhandler.h"
#include "appcontype.h"
#include "socket_timer.h"
Data Structures
struct NetworkStatus
Struct representing the current network status.
Functions
EipBool8 CheckSocketSet (int socket)
check if the given socket is set in the read set
void CloseTcpSocket (int socket_handle)
void CloseUdpSocket (int socket_handle)
int GetMaxSocket (int socket1, int socket2, int socket3, int socket4)
Returns the socket with the highest id.
EipStatus NetworkHandlerFinish (void)
EipStatus NetworkHandlerInitialize (void)
The platform independent part of network handler initialization routine.
EipStatus NetworkHandlerProcessOnce (void)
Variables
ConnectionObject * g_active_connection_list
List holding all currently active connections.
MilliSeconds g_actual_time
int g_current_active_tcp_socket
This variable holds the TCP socket the received to last explicit message. It is needed for opening point to point connection to determine the peer's address.
EipUint8 g_ethernet_communication_buffer [PC_OPENER_ETHERNET_BUFFER_SIZE]
MilliSeconds g_last_time
NetworkStatus g_network_status
struct timeval g_time_value
SocketTimer g_timestamps [OPENER_NUMBER_OF_SUPPORTED_SESSIONS]
int highest_socket_handle
fd_set master_socket
fd_set read_socket
Function Documentation
EipBool8 CheckSocketSet (int socket)
check if the given socket is set in the read set
Parameters:
socket The socket to check
Returns:
true if socket is set
Definition at line 262 of file generic_networkhandler.c.
References master_socket, OPENER_TRACE_INFO, and read_socket.
Referenced by CheckAndHandleConsumingUdpSockets(), CheckAndHandleTcpListenerSocket(), CheckAndHandleUdpGlobalBroadcastSocket(), CheckAndHandleUdpUnicastSocket(), and NetworkHandlerProcessOnce().
void CloseTcpSocket (int socket_handle)
Definition at line 245 of file generic_networkhandler.c.
References CloseSocket(), and RemoveSocketTimerFromList().
Referenced by CheckEncapsulationInactivity(), CloseSession(), EncapsulationShutDown(), HandleReceivedUnregisterSessionCommand(), and NetworkHandlerProcessOnce().
void CloseUdpSocket (int socket_handle)
Definition at line 241 of file generic_networkhandler.c.
References CloseSocket().
Referenced by CloseCommunicationChannelsAndRemoveFromActiveConnectionsList(), and CloseConnection().
int GetMaxSocket (int socket1, int socket2, int socket3, int socket4)
Returns the socket with the highest id.
Parameters:
socket1 First socket
socket2 Second socket
socket3 Third socket
socket4 Fourth socket
Returns:
Highest socket id from the provided sockets
Definition at line 885 of file generic_networkhandler.c.
Referenced by NetworkHandlerInitialize().
EipStatus NetworkHandlerFinish (void)
Definition at line 390 of file generic_networkhandler.c.
References CloseSocket(), g_network_status, kEipStatusOk, NetworkStatus::tcp_listener, NetworkStatus::udp_global_broadcast_listener, and NetworkStatus::udp_unicast_listener.
Referenced by main().
EipStatus NetworkHandlerInitialize (void)
The platform independent part of network handler initialization routine.
Initializes the network handler, shall be implemented by a port-specific networkhandler.
Returns:
Returns the OpENer status after the initialization routine
EipStatus, if initialization failed EipError is returned
The platform independent part of network handler initialization routine.
Returns:
EipStatus, if initialization failed EipError is returned
Definition at line 64 of file generic_networkhandler.c.
References NetworkStatus::elapsed_time, FreeErrorMessage(), g_last_time, g_network_status, g_timestamps, GetErrorMessage(), GetMaxSocket(), GetMilliSeconds(), GetSocketErrorNumber(), highest_socket_handle, interface_configuration_, kEipStatusError, kEipStatusOk, master_socket, MAX_NO_OF_TCP_SOCKETS, NetworkHandlerInitializePlatform(), OPENER_NUMBER_OF_SUPPORTED_SESSIONS, OPENER_TRACE_ERR, read_socket, SetSocketToNonBlocking(), connection_object::socket, SocketTimerArrayInitialize(), NetworkStatus::tcp_listener, NetworkStatus::udp_global_broadcast_listener, and NetworkStatus::udp_unicast_listener.
Referenced by main().
EipStatus NetworkHandlerProcessOnce (void)
Definition at line 322 of file generic_networkhandler.c.
References CheckAndHandleConsumingUdpSockets(), CheckAndHandleTcpListenerSocket(), CheckAndHandleUdpGlobalBroadcastSocket(), CheckAndHandleUdpUnicastSocket(), CheckEncapsulationInactivity(), CheckSocketSet(), CloseTcpSocket(), NetworkStatus::elapsed_time, FreeErrorMessage(), g_actual_time, g_last_time, g_network_status, g_time_value, GetErrorMessage(), GetMilliSeconds(), GetSocketErrorNumber(), HandleDataOnTcpSocket(), highest_socket_handle, kEipStatusError, kEipStatusOk, ManageConnections(), master_socket, OPENER_TRACE_ERR, read_socket, and RemoveSession().
Referenced by main().
Variable Documentation
ConnectionObject* g_active_connection_list
List holding all currently active connections.
External globals needed from connectionmanager.c.
An implicit list structure inside the ConnectionObject, so the g_active_connection_list holds the first element of the list
Definition at line 134 of file cipconnectionmanager.c.
MilliSeconds g_actual_time
Definition at line 49 of file generic_networkhandler.h.
Referenced by CheckEncapsulationInactivity(), HandleDataOnTcpSocket(), HandleReceivedRegisterSessionCommand(), and NetworkHandlerProcessOnce().
int g_current_active_tcp_socket
This variable holds the TCP socket the received to last explicit message. It is needed for opening point to point connection to determine the peer's address.
Definition at line 46 of file generic_networkhandler.h.
Referenced by CreateUdpSocket(), and HandleDataOnTcpSocket().
EipUint8 g_ethernet_communication_buffer[PC_OPENER_ETHERNET_BUFFER_SIZE]
communication buffer
Definition at line 35 of file generic_networkhandler.h.
Referenced by CheckAndHandleConsumingUdpSockets(), CheckAndHandleUdpGlobalBroadcastSocket(), CheckAndHandleUdpUnicastSocket(), and HandleDataOnTcpSocket().
MilliSeconds g_last_time
Definition at line 50 of file generic_networkhandler.h.
Referenced by NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
NetworkStatus g_network_status
Global variable holding the current network status
Definition at line 61 of file generic_networkhandler.h.
Referenced by CheckAndHandleTcpListenerSocket(), CheckAndHandleUdpGlobalBroadcastSocket(), CheckAndHandleUdpUnicastSocket(), NetworkHandlerFinish(), NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
struct timeval g_time_value
Definition at line 48 of file generic_networkhandler.h.
Referenced by NetworkHandlerProcessOnce().
SocketTimer g_timestamps[OPENER_NUMBER_OF_SUPPORTED_SESSIONS]
Definition at line 30 of file generic_networkhandler.h.
Referenced by CheckAndHandleTcpListenerSocket(), CheckEncapsulationInactivity(), HandleDataOnTcpSocket(), HandleReceivedRegisterSessionCommand(), NetworkHandlerInitialize(), and RemoveSocketTimerFromList().
int highest_socket_handle
temporary file descriptor for select()
Definition at line 40 of file generic_networkhandler.h.
Referenced by CheckAndHandleTcpListenerSocket(), CreateUdpSocket(), NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
fd_set master_socket
Definition at line 37 of file generic_networkhandler.h.
Referenced by CheckAndHandleTcpListenerSocket(), CheckSocketSet(), CloseSocket(), CreateUdpSocket(), NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
fd_set read_socket
Definition at line 38 of file generic_networkhandler.h.
Referenced by CheckSocketSet(), NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().