OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/LM3S8962/networkhandler.c File Reference
networkhandler.c File Reference
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <assert.h>
#include "networkhandler.h"
#include "cipcommon.h"
#include "cipconnectionmanager.h"
#include "encap.h"
#include <trace.h>
Macros
#define EIP_TERSE 1
#define EIP_VERBOSE 2
#define EIP_VVERBOSE 3
#define MAX_NO_OF_TCP_SOCKETS 10
#define MAX_RECEIVE_SIZE 512
#define MAX_SEND_SIZE 512
Functions
void CIPtick (int delta)
void dump (unsigned char *p, int size)
void IApp_CloseSocket_tcp (int fd)
void IApp_CloseSocket_udp (int fd)
int IApp_CreateUDPSocket (int pa_nDirection, struct sockaddr_in *pa_pstAddr)
create a producing or consuming UDP socket
EIP_STATUS IApp_SendUDPData (struct sockaddr_in *pa_addr, int sockfd, EIP_UINT8 *pa_data, EIP_UINT16 pa_datalength)
create a producing or consuming UDP socket
EIP_STATUS registerCallbackFunc (int sockfd, struct sockaddr_in *pa_addr, S_CIP_Instance *pa_pstInstance, TCIPServiceFunc pa_ptfuncReceiveData)
EIP_STATUS Start_NetworkHandler ()
err_t tcp_connection_accept_callback (void *arg, struct tcp_pcb *newpcb, err_t err)
err_t tcp_receive_callback (void *arg, struct tcp_pcb *pcb, struct pbuf *pbuf, err_t err)
err_t tcp_sent_callback (void *arg, struct tcp_pcb *tpcb, u16_t len)
void udp_registered_receive_callback (void *arg, struct udp_pcb *pcb, struct pbuf *pbuf, struct ip_addr *addr, u16_t port)
void udp_unsolicited_receive_callback (void *arg, struct udp_pcb *pcb, struct pbuf *p, struct ip_addr *addr, u16_t port)
EIP_STATUS unregisterCallbackFunc (S_CIP_Instance *pa_pstInstance)
Variables
EIP_UINT8 eip_reply_buf [MAX_SEND_SIZE]
struct tcp_pcb * g_pstCurrentTCP_PCB = NULL
struct sockaddr_in my_addr
Macro Definition Documentation
#define EIP_TERSE 1
Definition at line 21 of file networkhandler.c.
#define EIP_VERBOSE 2
Definition at line 19 of file networkhandler.c.
#define EIP_VVERBOSE 3
Definition at line 20 of file networkhandler.c.
Referenced by tcp_receive_callback(), and udp_unsolicited_receive_callback().
#define MAX_NO_OF_TCP_SOCKETS 10
Definition at line 35 of file networkhandler.c.
#define MAX_RECEIVE_SIZE 512
Definition at line 23 of file networkhandler.c.
Referenced by tcp_receive_callback(), and udp_registered_receive_callback().
#define MAX_SEND_SIZE 512
Definition at line 24 of file networkhandler.c.
Function Documentation
void CIPtick (int delta)
Definition at line 298 of file networkhandler.c.
References manageConnections(), and TIMERTICK.
void dump (unsigned char * p, int size)
Definition at line 50 of file stubs.c.
References OPENER_TRACE_INFO.
Referenced by tcp_receive_callback(), and udp_unsolicited_receive_callback().
void IApp_CloseSocket_tcp (int fd)
Definition at line 418 of file networkhandler.c.
References OPENER_TRACE_INFO.
Referenced by closeSession(), encapShutDown(), and handleReceivedUnregisterSessionCmd().
void IApp_CloseSocket_udp (int fd)
Definition at line 409 of file networkhandler.c.
References OPENER_TRACE_INFO.
Referenced by closeCommChannelsAndRemoveFromActiveConnsList(), and closeConnection().
EIP_STATUS registerCallbackFunc (int sockfd, struct sockaddr_in * pa_addr, S_CIP_Instance * pa_pstInstance, TCIPServiceFunc pa_ptfuncReceiveData)
Definition at line 321 of file networkhandler.c.
References EIP_OK.
EIP_STATUS Start_NetworkHandler (void)
Start a TCP/UDP listening socket, accept connections, receive data in select loop, call manageConnections periodically.
Returns
status EIP_ERROR .. error
Definition at line 267 of file networkhandler.c.
References AF_INET, EIP_OK, INADDR_ANY, my_addr, OPENER_ETHERNET_PORT, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, sockaddr_in::sin_zero, tcp_connection_accept_callback(), and udp_unsolicited_receive_callback().
Referenced by main().
err_t tcp_connection_accept_callback (void * arg, struct tcp_pcb * newpcb, err_t err)
Definition at line 246 of file networkhandler.c.
References OPENER_TRACE_INFO, tcp_receive_callback(), and tcp_sent_callback().
Referenced by Start_NetworkHandler().
err_t tcp_receive_callback (void * arg, struct tcp_pcb * pcb, struct pbuf * pbuf, err_t err)
Definition at line 163 of file networkhandler.c.
References dump(), EIP_ERROR, eip_reply_buf, EIP_UINT8, EIP_VVERBOSE, ENCAPSULATION_HEADER_LENGTH, g_pstCurrentTCP_PCB, handleReceivedExplictTCPData(), ltohs(), MAX_RECEIVE_SIZE, OPENER_TRACE_ERR, and OPENER_TRACE_INFO.
Referenced by tcp_connection_accept_callback().
err_t tcp_sent_callback (void * arg, struct tcp_pcb * tpcb, u16_t len)
Definition at line 151 of file networkhandler.c.
Referenced by tcp_connection_accept_callback().
void udp_registered_receive_callback (void * arg, struct udp_pcb * pcb, struct pbuf * pbuf, struct ip_addr * addr, u16_t port)
Definition at line 108 of file networkhandler.c.
References AF_INET, EIP_UINT8, handleReceivedConnectedData(), MAX_RECEIVE_SIZE, OPENER_TRACE_ERR, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, and sockaddr_in::sin_zero.
Referenced by IApp_CreateUDPSocket().
void udp_unsolicited_receive_callback (void * arg, struct udp_pcb * pcb, struct pbuf * p, struct ip_addr * addr, u16_t port)
Definition at line 45 of file networkhandler.c.
References AF_INET, dump(), eip_reply_buf, EIP_UINT8, EIP_VVERBOSE, handleReceivedExplictUDPData(), OPENER_TRACE_INFO, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, and sockaddr_in::sin_zero.
Referenced by Start_NetworkHandler().
EIP_STATUS unregisterCallbackFunc (S_CIP_Instance * pa_pstInstance)
Definition at line 328 of file networkhandler.c.
References EIP_OK.
Variable Documentation
EIP_UINT8 eip_reply_buf[MAX_SEND_SIZE]
Definition at line 27 of file networkhandler.c.
Referenced by tcp_receive_callback(), and udp_unsolicited_receive_callback().
struct tcp_pcb* g_pstCurrentTCP_PCB = NULL
Definition at line 39 of file networkhandler.c.
Referenced by IApp_CreateUDPSocket(), and tcp_receive_callback().
struct sockaddr_in my_addr
Definition at line 37 of file networkhandler.c.
Referenced by Start_NetworkHandler().