OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/udp_protocol.c File Reference
udp_protocol.c File Reference
#include "udp_protocol.h"
Functions
uint16_t UDPHeaderCalculateChecksum (const void *udp_packet, const size_t udp_packet_length, const in_addr_t source_addr, const in_addr_t destination_addr)
Calculates the checksum based on the set UDP packet data and pseudo IP header.
void UDPHeaderGenerate (const UDPHeader *header, char *message)
Generate the UDP header in the message according to the header.
uint16_t UDPHeaderGetChecksum (const UDPHeader *const header)
Gets checksum field.
uint16_t UDPHeaderGetDestinationPort (const UDPHeader *const header)
Gets destination port field.
uint16_t UDPHeaderGetPacketLength (const UDPHeader *const header)
Gets packet length field.
uint16_t UDPHeaderGetSourcePort (const UDPHeader *const header)
Gets source port field.
void UDPHeaderSetChecksum (UDPHeader *const header, const uint16_t checksum)
Sets checksum field.
void UDPHeaderSetDestinationPort (UDPHeader *const header, const uint16_t destination_port)
Sets destination port field.
void UDPHeaderSetPacketLength (UDPHeader *const header, const uint16_t packet_length)
Sets packet length field.
void UDPHeaderSetSourcePort (UDPHeader *const header, const uint16_t source_port)
Sets source port field.
Function Documentation
uint16_t UDPHeaderCalculateChecksum (const void * udp_packet, const size_t udp_packet_length, const in_addr_t source_addr, const in_addr_t destination_addr)
Calculates the checksum based on the set UDP packet data and pseudo IP header.
Parameters
udp_packet the UDP packet including the UDP header
udp_packet_length UPD packet length
source_addr The IP source address
destination_addr The IP destination address
Returns
The calculated checksum
Definition at line 57 of file udp_protocol.c.
Referenced by SendUdpData().
void UDPHeaderGenerate (const UDPHeader * header, char * message)
Generate the UDP header in the message according to the header.
The function generates the UDP header according to the header struct overwriting the first 8 bytes
Parameters
header The UDP header struct instance
message The message buffer
Definition at line 45 of file udp_protocol.c.
References UDPHeaderGetChecksum(), UDPHeaderGetDestinationPort(), UDPHeaderGetPacketLength(), and UDPHeaderGetSourcePort().
Referenced by SendUdpData().
uint16_t UDPHeaderGetChecksum (const UDPHeader *const header)
Gets checksum field.
Parameters
header The UDP header struct instance
Returns
The packet length
Definition at line 41 of file udp_protocol.c.
References UDPHeader::checksum.
Referenced by UDPHeaderGenerate().
uint16_t UDPHeaderGetDestinationPort (const UDPHeader *const header)
Gets destination port field.
Parameters
header The header struct instance
Returns
The destination port
Definition at line 23 of file udp_protocol.c.
References UDPHeader::destination_port.
Referenced by UDPHeaderGenerate().
uint16_t UDPHeaderGetPacketLength (const UDPHeader *const header)
Gets packet length field.
Parameters
header The header struct instance
Returns
The packet length
Definition at line 32 of file udp_protocol.c.
References UDPHeader::packet_length.
Referenced by UDPHeaderGenerate().
uint16_t UDPHeaderGetSourcePort (const UDPHeader *const header)
Gets source port field.
Parameters
header The header struct instance
Returns
The source port
Definition at line 14 of file udp_protocol.c.
References UDPHeader::source_port.
Referenced by UDPHeaderGenerate().
void UDPHeaderSetChecksum (UDPHeader *const header, const uint16_t checksum)
Sets checksum field.
Parameters
header The UDP header struct instance
checksum Checksum value to be set
Definition at line 36 of file udp_protocol.c.
References UDPHeader::checksum.
Referenced by SendUdpData().
void UDPHeaderSetDestinationPort (UDPHeader *const header, const uint16_t destination_port)
Sets destination port field.
Parameters
header The UDP header struct instance
destination_port Destination port value to be set
Definition at line 18 of file udp_protocol.c.
References UDPHeader::destination_port.
void UDPHeaderSetPacketLength (UDPHeader *const header, const uint16_t packet_length)
Sets packet length field.
Parameters
header The UDP header struct instance
packet_length Length value to be set
Definition at line 27 of file udp_protocol.c.
References UDPHeader::packet_length.
void UDPHeaderSetSourcePort (UDPHeader *const header, const uint16_t source_port)
Sets source port field.
Parameters
header The UDP header struct instance
source_port Source port value to be set
Definition at line 9 of file udp_protocol.c.
References UDPHeader::source_port.