OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipelectronickey.h File Reference
src/cip/cipelectronickey.h File Reference
#include <stdbool.h>
#include "typedefs.h"
Data Structures
struct CipElectronicKey
CIP Electronic Key Segment struct.
Typedefs
typedef struct
electronic_key_format_4 ElectronicKeyFormat4
Declaration of the electronic key format 4 data struct for the class.
Functions
void ElectronicKeyFormat4Delete (ElectronicKeyFormat4 **electronic_key)
Destructor for the electroic key format 4 class.
CipUint ElectronicKeyFormat4GetDeviceType (const ElectronicKeyFormat4 *const electronic_key)
Gets the device type from a format 4 electronic key.
CipByte ElectronicKeyFormat4GetMajorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the major revision from an format 4 electronic key.
bool ElectronicKeyFormat4GetMajorRevisionCompatibility (const ElectronicKeyFormat4 *const electronic_key)
Gets the Compatibility flag from the format 4 electronic key.
CipUsint ElectronicKeyFormat4GetMinorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the minor revision from an format 4 electronic key.
CipUint ElectronicKeyFormat4GetProductCode (const ElectronicKeyFormat4 *const electronic_key)
Gets the product code from an format 4 electronic key.
CipUint ElectronicKeyFormat4GetVendorId (const ElectronicKeyFormat4 *const electronic_key)
Gets the vendor ID form the electronic key.
ElectronicKeyFormat4 * ElectronicKeyFormat4New ()
Constructor for the electroic key format 4 class.
void ElectronicKeyFormat4SetDeviceType (ElectronicKeyFormat4 *const electronic_key, const CipUint device_type)
Sets the device type in the electronic key.
void ElectronicKeyFormat4SetMajorRevisionCompatibility (ElectronicKeyFormat4 *const electronic_key, const CipByte major_revision_compatibility)
Sets the major revision byte including the compatibility flag.
void ElectronicKeyFormat4SetMinorRevision (ElectronicKeyFormat4 *const electronic_key, const CipUsint minor_revision)
Sets the devices minor revision in an format 4 electronic key.
void ElectronicKeyFormat4SetProductCode (ElectronicKeyFormat4 *const electronic_key, const CipUint product_code)
Set product code in the electronic key.
void ElectronicKeyFormat4SetVendorId (ElectronicKeyFormat4 *const electronic_key, const CipUint vendor_id)
Sets vendor ID in the electronic key.
void * ElectronicKeyGetKeyData (const CipElectronicKey *const electronic_key)
CipUint ElectronicKeyGetKeyFormat (const CipElectronicKey *const electronic_key)
CipUsint ElectronicKeyGetSegmentType (const CipElectronicKey *const electronic_key)
void ElectronicKeySetKeyData (CipElectronicKey *const electronic_key, void *key_data)
void ElectronicKeySetKeyFormat (CipElectronicKey *const electronic_key, const CipUsint key_format)
void ElectronicKeySetSegmentType (CipElectronicKey *const electronic_key, const CipUsint segment_type)
Variables
const size_t kElectronicKeyFormat4Size
Typedef Documentation
typedef struct electronic_key_format_4 ElectronicKeyFormat4
Declaration of the electronic key format 4 data struct for the class.
Definition at line 39 of file cipelectronickey.h.
Function Documentation
void ElectronicKeyFormat4Delete (ElectronicKeyFormat4 ** electronic_key)
Destructor for the electroic key format 4 class.
Safe destructor/free, nulls the pointer after freeing it
Parameters:
electronic_key A format 4 electronic key
Definition at line 41 of file cipelectronickey.c.
Referenced by ParseConnectionPath().
CipUint ElectronicKeyFormat4GetDeviceType (const ElectronicKeyFormat4 *const electronic_key)
Gets the device type from a format 4 electronic key.
Parameters:
The format 4 electronic key from which the device type will be extracted
Returns:
The device type
Definition at line 59 of file cipelectronickey.c.
References electronic_key_format_4::device_type.
Referenced by CheckElectronicKeyData(), and ParseConnectionPath().
CipByte ElectronicKeyFormat4GetMajorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the major revision from an format 4 electronic key.
Parameters:
electronic_key An format 4 electronic key
Returns:
The device's major revision
Definition at line 80 of file cipelectronickey.c.
References electronic_key_format_4::major_revision_compatibility.
Referenced by CheckElectronicKeyData(), and ParseConnectionPath().
bool ElectronicKeyFormat4GetMajorRevisionCompatibility (const ElectronicKeyFormat4 *const electronic_key)
Gets the Compatibility flag from the format 4 electronic key.
Parameters:
electronic_key The format 4 electronic key to be read
Returns:
True if compatibility bit is set, false if otherwise
Definition at line 86 of file cipelectronickey.c.
References electronic_key_format_4::major_revision_compatibility.
Referenced by CheckElectronicKeyData().
CipUsint ElectronicKeyFormat4GetMinorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the minor revision from an format 4 electronic key.
Parameters:
electronic_key The format 4 electronic key to be read
Returns:
The device's minor revision
Definition at line 100 of file cipelectronickey.c.
References electronic_key_format_4::minor_revision.
Referenced by CheckElectronicKeyData(), and ParseConnectionPath().
CipUint ElectronicKeyFormat4GetProductCode (const ElectronicKeyFormat4 *const electronic_key)
Gets the product code from an format 4 electronic key.
Parameters:
electronic_key The format 4 electronic key to be read
Returns:
The product code
Definition at line 69 of file cipelectronickey.c.
References electronic_key_format_4::product_code.
Referenced by CheckElectronicKeyData(), and ParseConnectionPath().
CipUint ElectronicKeyFormat4GetVendorId (const ElectronicKeyFormat4 *const electronic_key)
Gets the vendor ID form the electronic key.
Parameters:
electronic_key The format 4 electronic key from which the vendor ID will be extracted
Returns:
The vendor ID
Definition at line 50 of file cipelectronickey.c.
References electronic_key_format_4::vendor_id.
Referenced by CheckElectronicKeyData(), and ParseConnectionPath().
ElectronicKeyFormat4* ElectronicKeyFormat4New ()
Constructor for the electroic key format 4 class.
Returns:
A new unset electronic key
Definition at line 37 of file cipelectronickey.c.
Referenced by ParseConnectionPath().
void ElectronicKeyFormat4SetDeviceType (ElectronicKeyFormat4 *const electronic_key, const CipUint device_type)
Sets the device type in the electronic key.
Parameters:
device_type The device type which shall be inserted into the electronic key
electronic_key A format 4 electronic key
Definition at line 55 of file cipelectronickey.c.
References electronic_key_format_4::device_type.
Referenced by GetElectronicKeyFormat4FromMessage().
void ElectronicKeyFormat4SetMajorRevisionCompatibility (ElectronicKeyFormat4 *const electronic_key, const CipByte major_revision_compatibility)
Sets the major revision byte including the compatibility flag.
Parameters:
major_revision_compatibility The major revision byte including the compatibility flag
electronic_key The electronic key to be modified
Definition at line 74 of file cipelectronickey.c.
References electronic_key_format_4::major_revision_compatibility.
Referenced by GetElectronicKeyFormat4FromMessage().
void ElectronicKeyFormat4SetMinorRevision (ElectronicKeyFormat4 *const electronic_key, const CipUsint minor_revision)
Sets the devices minor revision in an format 4 electronic key.
Parameters:
minor_revision The minor revision to be set in the electronic key
electronic_key The electronic key to be modified
Definition at line 96 of file cipelectronickey.c.
References electronic_key_format_4::minor_revision.
Referenced by GetElectronicKeyFormat4FromMessage().
void ElectronicKeyFormat4SetProductCode (ElectronicKeyFormat4 *const electronic_key, const CipUint product_code)
Set product code in the electronic key.
Parameters:
product_code The product code to be inserted
electronic_key The electronic key to be modified
Definition at line 64 of file cipelectronickey.c.
References electronic_key_format_4::product_code.
Referenced by GetElectronicKeyFormat4FromMessage().
void ElectronicKeyFormat4SetVendorId (ElectronicKeyFormat4 *const electronic_key, const CipUint vendor_id)
Sets vendor ID in the electronic key.
Parameters:
vendor_id The vendor ID to be set into the electronic key
electronic_key The electronic key to be set - will be modified
Definition at line 46 of file cipelectronickey.c.
References electronic_key_format_4::vendor_id.
Referenced by GetElectronicKeyFormat4FromMessage().
void* ElectronicKeyGetKeyData (const CipElectronicKey *const electronic_key)
Definition at line 23 of file cipelectronickey.c.
References CipElectronicKey::key_data.
CipUint ElectronicKeyGetKeyFormat (const CipElectronicKey *const electronic_key)
Definition at line 15 of file cipelectronickey.c.
References CipElectronicKey::key_format.
CipUsint ElectronicKeyGetSegmentType (const CipElectronicKey *const electronic_key)
void ElectronicKeySetKeyData (CipElectronicKey *const electronic_key, void * key_data)
Definition at line 19 of file cipelectronickey.c.
References CipElectronicKey::key_data.
void ElectronicKeySetKeyFormat (CipElectronicKey *const electronic_key, const CipUsint key_format)
Definition at line 11 of file cipelectronickey.c.
References CipElectronicKey::key_format.
void ElectronicKeySetSegmentType (CipElectronicKey *const electronic_key, const CipUsint segment_type)
Variable Documentation
const size_t kElectronicKeyFormat4Size
Definition at line 35 of file cipelectronickey.c.