OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/POSIX/networkhandler.c File Reference
src/ports/POSIX/networkhandler.c File Reference
#include <unistd.h>
#include <sys/time.h>
#include <time.h>
#include <fcntl.h>
#include "networkhandler.h"
#include "encap.h"
Functions
void CloseSocketPlatform (int socket_handle)
Platform dependent code to close a socket.
MicroSeconds GetMicroSeconds (void)
This function shall return the current time in microseconds relative to epoch, and shall be implemented in a port specific networkhandler.
MilliSeconds GetMilliSeconds (void)
This function shall return the current time in milliseconds relative to epoch, and shall be implemented in a port specific networkhandler.
EipStatus NetworkHandlerInitializePlatform (void)
Executes platform dependent network handler initialization code.
int SetSocketToNonBlocking (int socket_handle)
Function Documentation
void CloseSocketPlatform (int socket_handle)
Platform dependent code to close a socket.
Parameters:
socket_handle The socket handle to be closed
Definition at line 33 of file networkhandler.c.
Referenced by CloseSocket().
MicroSeconds GetMicroSeconds (void)
This function shall return the current time in microseconds relative to epoch, and shall be implemented in a port specific networkhandler.
Returns:
Current time relative to epoch as MicroSeconds
Definition at line 15 of file networkhandler.c.
Referenced by GetMilliSeconds().
MilliSeconds GetMilliSeconds (void)
This function shall return the current time in milliseconds relative to epoch, and shall be implemented in a port specific networkhandler.
Returns:
Current time relative to epoch as MilliSeconds
Definition at line 24 of file networkhandler.c.
Referenced by NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
EipStatus NetworkHandlerInitializePlatform (void)
Executes platform dependent network handler initialization code.
Returns:
EipStatusOk if initialization was successful, otherwise EipStatusError
Definition at line 28 of file networkhandler.c.
Referenced by NetworkHandlerInitialize().
int SetSocketToNonBlocking (int socket_handle)
Definition at line 38 of file networkhandler.c.
Referenced by CreateUdpSocket(), and NetworkHandlerInitialize().