OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/WIN32/networkhandler.c File Reference
networkhandler.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <sys/time.h>
#include <opener_api.h>
#include "networkhandler.h"
#include <encap.h>
#include <cipconnectionmanager.h>
#include <endianconv.h>
#include <trace.h>
#include <ciptcpipinterface.h>
Data Structures
struct NetworkStatus
Macros
#define MAX_NO_OF_TCP_SOCKETS 10
Typedefs
typedef unsigned long long MICROSECONDS
typedef long MILLISECONDS
Functions
void checkAndHandleConsumingUDPSockets ()
check if on one of the udp consuming sockets data has been received and if yes handle it correctly
void checkAndHandleTCPListenerSocket ()
handle any connection request coming in the TCP server socket.
void checkAndHandleUDPBroadCastSocket ()
check if data has been received on the udp broadcast socket and if yes handle it correctly
EIP_BOOL8 checkSocketSet (int pa_nSocket)
check if the given socket is set in the read set
EIP_STATUS handleDataOnTCPSocket (int pa_nSocket)
void IApp_CloseSocket (int pa_nSockFd)
Close the given socket and clean up the stack.
void IApp_CloseSocket_tcp (int pa_nSockFd)
void IApp_CloseSocket_udp (int pa_nSockFd)
int IApp_CreateUDPSocket (int pa_nDirection, struct sockaddr_in *pa_pstAddr)
create a producing or consuming UDP socket
EIP_STATUS IApp_SendUDPData (struct sockaddr_in *pa_pstAddr, int pa_nSockFd, EIP_UINT8 *pa_acData, EIP_UINT16 pa_nDataLength)
create a producing or consuming UDP socket
EIP_STATUS NetworkHandler_Finish (void)
EIP_STATUS NetworkHandler_Init (void)
EIP_STATUS NetworkHandler_ProcessOnce (void)
Variables
int fdmax
EIP_UINT8 g_acPCEthernetCommBuffer [PC_OPENER_ETHERNET_BUFFER_SIZE]
int g_nCurrentActiveTCPSocket
S_CIP_ConnectionObject * g_pstActiveConnectionList
fd_set master
struct NetworkStatus PACKED
fd_set read_fds
struct NetworkStatus TheNetworkStatus
Macro Definition Documentation
#define MAX_NO_OF_TCP_SOCKETS 10
Definition at line 32 of file networkhandler.c.
Referenced by NetworkHandler_Init().
Typedef Documentation
typedef unsigned long long MICROSECONDS
Definition at line 35 of file networkhandler.c.
typedef long MILLISECONDS
Definition at line 34 of file networkhandler.c.
Function Documentation
void checkAndHandleConsumingUDPSockets ()
check if on one of the udp consuming sockets data has been received and if yes handle it correctly
Definition at line 665 of file networkhandler.c.
References checkSocketSet(), CONSUMING, g_acPCEthernetCommBuffer, g_pstActiveConnectionList, handleReceivedConnectedData(), CIP_ConnectionObject::m_pfCloseFunc, CIP_ConnectionObject::m_pstNext, OPENER_TRACE_ERR, OPENER_TRACE_STATE, PC_OPENER_ETHERNET_BUFFER_SIZE, CIP_ConnectionObject::sockfd, and socklen_t.
void checkAndHandleTCPListenerSocket ()
handle any connection request coming in the TCP server socket.
Definition at line 570 of file networkhandler.c.
References checkSocketSet(), fdmax, master, newfd, NetworkStatus::nTCPListener, OPENER_TRACE_ERR, OPENER_TRACE_INFO, OPENER_TRACE_STATE, and TheNetworkStatus.
void checkAndHandleUDPBroadCastSocket ()
check if data has been received on the udp broadcast socket and if yes handle it correctly
Definition at line 599 of file networkhandler.c.
References checkSocketSet(), EIP_UINT8, g_acPCEthernetCommBuffer, handleReceivedExplictUDPData(), NetworkStatus::nUDPListener, OPENER_TRACE_ERR, OPENER_TRACE_INFO, OPENER_TRACE_STATE, PC_OPENER_ETHERNET_BUFFER_SIZE, socklen_t, and TheNetworkStatus.
EIP_BOOL8 checkSocketSet (int pa_nSocket)
check if the given socket is set in the read set
Definition at line 292 of file networkhandler.c.
References EIP_BOOL8, master, OPENER_TRACE_INFO, and read_fds.
EIP_STATUS handleDataOnTCPSocket (int pa_nSocket)
Definition at line 336 of file networkhandler.c.
References EIP_ERROR, EIP_OK, EIP_UINT8, ENCAPSULATION_HEADER_LENGTH, g_acPCEthernetCommBuffer, g_nCurrentActiveTCPSocket, handleReceivedExplictTCPData(), ltohs(), OPENER_TRACE_ERR, OPENER_TRACE_INFO, OPENER_TRACE_WARN, and PC_OPENER_ETHERNET_BUFFER_SIZE.
void IApp_CloseSocket_tcp (int pa_nSockFd)
Definition at line 547 of file networkhandler.c.
References IApp_CloseSocket().
void IApp_CloseSocket_udp (int pa_nSockFd)
Definition at line 541 of file networkhandler.c.
References IApp_CloseSocket().
EIP_STATUS NetworkHandler_Finish (void)
Definition at line 284 of file networkhandler.c.
References EIP_OK, IApp_CloseSocket(), NetworkStatus::nTCPListener, NetworkStatus::nUDPListener, and TheNetworkStatus.
EIP_STATUS NetworkHandler_Init (void)
Start a TCP/UDP listening socket, accept connections, receive data in select loop, call manageConnections periodically.
Returns
status EIP_ERROR .. error
Definition at line 119 of file networkhandler.c.
References AF_INET, EIP_ERROR, EIP_OK, NetworkStatus::elapsedtime, fdmax, INADDR_ANY, master, MAX_NO_OF_TCP_SOCKETS, NetworkStatus::nTCPListener, NetworkStatus::nUDPListener, OPENER_ETHERNET_PORT, OPENER_TRACE_ERR, PF_INET, read_fds, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, sockaddr_in::sin_zero, SO_BROADCAST, SOCK_DGRAM, SOCK_STREAM, SOL_SOCKET, and TheNetworkStatus.
EIP_STATUS NetworkHandler_ProcessOnce (void)
Definition at line 218 of file networkhandler.c.
References checkAndHandleConsumingUDPSockets(), checkAndHandleTCPListenerSocket(), checkAndHandleUDPBroadCastSocket(), checkSocketSet(), closeSession(), EIP_ERROR, EIP_OK, NetworkStatus::elapsedtime, fdmax, handleDataOnTCPSocket(), IApp_CloseSocket(), manageConnections(), master, OPENER_TIMER_TICK, OPENER_TRACE_ERR, read_fds, and TheNetworkStatus.
Variable Documentation
int fdmax
This var holds the TCP socket the received to last explicit message. It is needed for opening point to point connection to determine the peer's address.
Definition at line 40 of file networkhandler.c.
EIP_UINT8 g_acPCEthernetCommBuffer[PC_OPENER_ETHERNET_BUFFER_SIZE]
Definition at line 30 of file networkhandler.c.
int g_nCurrentActiveTCPSocket
Definition at line 46 of file networkhandler.c.
S_CIP_ConnectionObject* g_pstActiveConnectionList
List holding all currently active connections
Definition at line 63 of file cipconnectionmanager.c.
Referenced by addNewActiveConnection(), checkForExistingConnection(), ForwardClose(), getConnectedObject(), getConnectedOutputAssembly(), isConnectedOutputAssembly(), manageConnections(), and triggerConnections().
fd_set master
Definition at line 36 of file networkhandler.c.
struct NetworkStatus PACKED
fd_set read_fds
Definition at line 37 of file networkhandler.c.
struct NetworkStatus TheNetworkStatus
Definition at line 116 of file networkhandler.c.