OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipconnectionmanager.h File Reference
src/cip/cipconnectionmanager.h File Reference
#include "opener_user_conf.h"
#include "opener_api.h"
#include "typedefs.h"
#include "ciptypes.h"
Data Structures
struct connection_object
struct LinkConsumer
struct LinkObject
struct LinkProducer
Defines
#define SEQ_GEQ16(a, b) ((short)((a) - (b)) >= 0)
#define SEQ_GEQ32(a, b) ((int)((a) - (b)) >= 0)
#define SEQ_GT32(a, b) ((int)((a) - (b)) > 0)
#define SEQ_LEQ16(a, b) ((short)((a) - (b)) <= 0)
similar macros for comparing 16 bit sequence numbers SEQ_LEQ16(a, b) Checks if sequence number a is less or equal than b SEQ_GEQ16(a, b) Checks if sequence number a is greater or equal than b
#define SEQ_LEQ32(a, b) ((int)((a) - (b)) <= 0)
macros for comparing sequence numbers according to CIP spec vol 2 3-4.2 for int type variables SEQ_LEQ32(a, b) Checks if sequence number a is less or equal than b SEQ_GEQ32(a, b) Checks if sequence number a is greater or equal than b SEQ_GT32(a, b) Checks if sequence number a is greater than b
Typedefs
typedef struct connection_object ConnectionObject
typedef enum ProductionTrigger ProductionTrigger
Enumerations
enum ConnectionManagerExtendedStatusCode {
kConnectionManagerExtendedStatusCodeSuccess = 0x00, kConnectionManagerExtendedStatusCodeErrorConnectionInUseOrDuplicateForwardOpen = 0x0100, kConnectionManagerExtendedStatusCodeErrorTransportClassAndTriggerCombinationNotSupported = 0x0103, kConnectionManagerExtendedStatusCodeErrorOwnershipConflict = 0x0106,
kConnectionManagerExtendedStatusCodeErrorConnectionTargetConnectionNotFound, kConnectionManagerExtendedStatusCodeErrorTargetForConnectionNotConfigured, kConnectionManagerExtendedStatusCodeRpiNotSupported = 0x0111, kConnectionManagerExtendedStatusCodeErrorRpiValuesNotAcceptable = 0x0112,
kConnectionManagerExtendedStatusCodeErrorNoMoreConnectionsAvailable = 0x0113, kConnectionManagerExtendedStatusCodeErrorVendorIdOrProductcodeError = 0x0114, kConnectionManagerExtendedStatusCodeErrorDeviceTypeError = 0x0115, kConnectionManagerExtendedStatusCodeErrorRevisionMismatch = 0x0116,
kConnectionManagerExtendedStatusCodeNonListenOnlyConnectionNotOpened = 0x0119, kConnectionManagerExtendedStatusCodeTargetObjectOutOfConnections = 0x011A, kConnectionManagerExtendedStatusCodeProductionInhibitTimerGreaterThanRpi, kConnectionManagerExtendedStatusCodeTransportClassNotSupported = 0x011C,
kConnectionManagerExtendedStatusCodeProductionTriggerNotSuppoerted = 0x011D, kConnectionManagerExtendedStatusCodeDirectionNotSupported = 0x011E, kConnectionManagerExtendedStatusCodeInvalidOToTNetworkConnectionFixVar, kConnectionManagerExtendedStatusCodeInvalidTToONetworkConnectionFixVar,
kConnectionManagerExtendedStatusCodeInvalidOToTNetworkConnectionPriority, kConnectionManagerExtendedStatusCodeInvalidTToONetworkConnectionPriority, kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionType = 0x0123, kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionType = 0x0124,
kConnectionManagerExtendedStatusCodeInvalidOToTNetworkConnectionRedundantOwner = 0x0125, kConnectionManagerExtendedStatusCodeInvalidConfigurationSize = 0x0126, kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionSize = 0x0127, kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionSize = 0x0128,
kConnectionManagerExtendedStatusCodeInvalidConfigurationApplicationPath, kConnectionManagerExtendedStatusCodeInvalidConsumingApplicationPath = 0x012A, kConnectionManagerExtendedStatusCodeInvalidProducingApplicationPath = 0x012B, kConnectionManagerExtendedStatusCodeConfigurationSymbolDoesNotExist = 0x012C,
kConnectionManagerExtendedStatusCodeConsumingSymbolDoesNotExist = 0x012D, kConnectionManagerExtendedStatusCodeProducingSymbolDoesNotExist = 0x012E, kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo = 0x012F, kConnectionManagerExtendedStatusCodeInconsistentConsumeDataFormat = 0x0130,
kConnectionManagerExtendedStatusCodeInconsistentProduceDataFormat = 0x0131, kConnectionManagerExtendedStatusCodeNullForwardOpenNotSupported = 0x0132, kConnectionManagerExtendedStatusCodeConnectionTimeoutMultiplierNotAcceptable, kConnectionManagerExtendedStatusCodeMismatchedTToONetworkConnectionFixVar,
kConnectionManagerExtendedStatusCodeMismatchedTToONetworkConnectionPriority, kConnectionManagerExtendedStatusCodeMismatchedTransportClass = 0x0137, kConnectionManagerExtendedStatusCodeMismatchedTToOProductionTrigger = 0x0138, kConnectionManagerExtendedStatusCodeMismatchedTToOProductionInhibitTimeSegment = 0x0139,
kConnectionManagerExtendedStatusCodeConnectionTimedOut = 0x0203, kConnectionManagerExtendedStatusCodeUnconnectedRequestTimedOut = 0x0204, kConnectionManagerExtendedStatusCodeErrorParameterErrorInUnconnectedSendService = 0x0205, kConnectionManagerExtendedStatusCodeMessageToLargeForUnconnectedSendService,
kConnectionManagerExtendedStatusCodeUnconnectedAcknowledgeWithoutReply, kConnectionManagerExtendedStatusCodeNoBufferMemoryAvailable = 0x0301, kConnectionManagerExtendedStatusCodeNetworkBandwithNotAvailableForData, kConnectionManagerExtendedStatusCodeNoConsumedConnectionIdFilterAvailable,
kConnectionManagerExtendedStatusCodeNotConfiguredToSendScheduledPriorityData, kConnectionManagerExtendedStatusCodeScheduleSignatureMismatch = 0x0305, kConnectionManagerExtendedStatusCodeScheduleSignatureValidationNotPossible, kConnectionManagerExtendedStatusCodePortNotAvailable = 0x0311,
kConnectionManagerExtendedStatusCodeLinkAddressNotValid = 0x0312, kConnectionManagerExtendedStatusCodeErrorInvalidSegmentTypeInPath = 0x0315, kConnectionManagerExtendedStatusCodeForwardCloseServiceConnectionPathMismatch = 0x0316, kConnectionManagerExtendedStatusCodeSchedulingNotSpecified = 0x0317,
kConnectionManagerExtendedStatusCodeLinkAddressToSelfInvalid = 0x0318, kConnectionManagerExtendedStatusCodeSecondaryResourcesUnavailable = 0x0319, kConnectionManagerExtendedStatusCodeRackConnectionAlreadyEstablished = 0x031A, kConnectionManagerExtendedStatusCodeModuleConnectionAlreadyEstablished,
kConnectionManagerExtendedStatusCodeMiscellaneous = 0x031C, kConnectionManagerExtendedStatusCodeRedundantConnectionMismatch = 0x031D, kConnectionManagerExtendedStatusCodeNoMoreUserConfigurableLinkConsumerResourcesAvailableInTheProducingModule = 0x031E, kConnectionManagerExtendedStatusCodeNoUserConfigurableLinkConsumerResourcesConfiguredInTheProducingModule = 0x031F,
kConnectionManagerExtendedStatusCodeNetworkLinkOffline = 0x0800, kConnectionManagerExtendedStatusCodeNoTargetApplicationDataAvailable = 0x0810, kConnectionManagerExtendedStatusCodeNoOriginatorApplicationDataAvailable, kConnectionManagerExtendedStatusCodeNodeAddressHasChangedSinceTheNetworkWasScheduled = 0x0812,
kConnectionManagerExtendedStatusCodeNotConfiguredForOffSubnetMulticast, kConnectionManagerExtendedStatusCodeInvalidProduceConsumeDataFormat = 0x0814, kConnectionManagerExtendedStatusWrongCloser
}
Connection Manager Error codes.
enum ConnectionManagerGeneralStatus {
kConnectionManagerGeneralStatusSuccess = 0x00, kConnectionManagerGeneralStatusExtendedStatus = 0x01, kConnectionManagerGeneralStatusResourceUnavailableForUnconnectedSend = 0x02, kConnectionManagerGeneralStatusPathSegmentErrorInUnconnectedSend = 0x04,
kConnectionManagerGeneralStatusErrorInDataSegment = 0x09, kConnectionManagerGeneralStatusObjectStateError = 0x0C, kConnectionManagerGeneralStatusDeviceStateError = 0x10, kConnectionManagerGeneralStatusNotEnoughData = 0x13,
kConnectionManagerGeneralStatusTooMuchData = 0x15
}
enum ConnectionObjectFixedVariable { kConnectionObjectFixedConnectionSize, kConnectionObjectVariableConnectionSize }
enum ConnectionState {
kConnectionStateNonExistent = 0, kConnectionStateConfiguring = 1, kConnectionStateWaitingForConnectionId = 2, kConnectionStateEstablished = 3,
kConnectionStateTimedOut = 4, kConnectionStateDeferredDelete = 5, kConnectionStateClosing
}
States of a connection.
enum ConnectionTriggerType { kConnectionTriggerTypeProductionTriggerMask = 0x70, kConnectionTriggerTypeCyclicConnection = 0x0, kConnectionTriggerTypeChangeOfStateTriggeredConnection = 0x10, kConnectionTriggerTypeApplicationTriggeredConnection = 0x20 }
enum ConnectionType { kConnectionTypeExplicit = 0, kConnectionTypeIoExclusiveOwner = 0x01, kConnectionTypeIoInputOnly = 0x11, kConnectionTypeIoListenOnly = 0x21 }
instance_type attributes
enum ForwardOpenConnectionType { kForwardOpenConnectionTypeNull = 0x0000, kForwardOpenConnectionTypePointToPointConnection = 0x4000, kForwardOpenConnectionTypeMulticastConnection = 0x2000, kForwardOpenConnectionTypeReserved = 0x6000 }
Connection Type constants of the Forward Open service request Indicates either a.
enum ForwardOpenPriority { kForwardOpenPriorityLow = 0x000, kForwardOpenPriorityHigh = 0x400, kForwardOpenPriorityScheduled = 0x800, kForwardOpenPriorityUrgent = 0xC00 }
enum ProductionTrigger { kProductionTriggerInvalid = -1, kProductionTriggerCyclic = 0, kProductionTriggerChangeOfState = 1, kProductionTriggerApplicationObjectTriggered = 2 }
enum WatchdogTimeoutAction { kWatchdogTimeoutActionTransitionToTimedOut = 0, kWatchdogTimeoutActionAutoDelete = 1, kWatchdogTimeoutActionAutoReset = 2, kWatchdogTimeoutActionDeferredDelete = 3 }
Possible values for the watch dog time out action of a connection.
Functions
void AddNewActiveConnection (ConnectionObject *connection_object)
Insert the given connection object to the list of currently active and managed connections.
void CloseConnection (ConnectionObject *RESTRICT connection_object)
Close the given connection.
EipStatus ConnectionManagerInit (EipUint16 unique_connection_id)
Initialize the data of the connection manager object.
void CopyConnectionData (ConnectionObject *RESTRICT destination, const ConnectionObject *RESTRICT const source)
Copy the given connection data from source to destination.
void GeneralConnectionConfiguration (ConnectionObject *connection_object)
Generate the ConnectionIDs and set the general configuration parameter in the given connection object.
ConnectionObject * GetConnectedObject (EipUint32 connection_id)
ConnectionObject * GetConnectedOutputAssembly (EipUint32 output_assembly_id)
EipUint32 GetConnectionObjectInactivityWatchdogTimerValue (ConnectionObject *connection_object)
ConnectionObjectFixedVariable GetConnectionObjectTargetToOriginatorFixedOrVariableConnectionSize (const ConnectionObject *const RESTRICT connection_object)
ForwardOpenPriority GetConnectionObjectTToOPriority (const ConnectionObject *const connection_object)
ForwardOpenConnectionType GetConnectionType (EipUint16 network_connection_parameter)
returns the connection type of the supplied network connection parameter
CipUint GetProductionInhibitTime (const ConnectionObject *const connection_object)
ProductionTrigger GetProductionTrigger (const ConnectionObject *const connection_object)
CipUdint GetTargetToOriginatorRequestedPackedInterval (const ConnectionObject *const connection_object)
CipUdint GetTargetToOriginatorRequestedPackedInterval (const ConnectionObject *const RESTRICT connection_object)
EipBool8 IsConnectedOutputAssembly (const EipUint32 instance_number)
void RemoveFromActiveConnections (ConnectionObject *connection_object)
Removes connection from the list of active connections.
void SetProductionInhibitTime (const EipUint16 production_inhibit_time, ConnectionObject *const connection_object)
void SetProductionTrigger (const ProductionTrigger production_trigger, ConnectionObject *connection_object)
Define Documentation
#define SEQ_GEQ16 (a, b) ((short)((a) - (b)) >= 0)
Definition at line 204 of file cipconnectionmanager.h.
#define SEQ_GEQ32 (a, b) ((int)((a) - (b)) >= 0)
Definition at line 195 of file cipconnectionmanager.h.
#define SEQ_GT32 (a, b) ((int)((a) - (b)) > 0)
Definition at line 196 of file cipconnectionmanager.h.
Referenced by HandleReceivedConnectedData().
#define SEQ_LEQ16 (a, b) ((short)((a) - (b)) <= 0)
similar macros for comparing 16 bit sequence numbers SEQ_LEQ16(a, b) Checks if sequence number a is less or equal than b SEQ_GEQ16(a, b) Checks if sequence number a is greater or equal than b
Definition at line 203 of file cipconnectionmanager.h.
Referenced by HandleReceivedIoConnectionData().
#define SEQ_LEQ32 (a, b) ((int)((a) - (b)) <= 0)
macros for comparing sequence numbers according to CIP spec vol 2 3-4.2 for int type variables SEQ_LEQ32(a, b) Checks if sequence number a is less or equal than b SEQ_GEQ32(a, b) Checks if sequence number a is greater or equal than b SEQ_GT32(a, b) Checks if sequence number a is greater than b
Definition at line 194 of file cipconnectionmanager.h.
Typedef Documentation
typedef struct connection_object ConnectionObject
The data needed for handling connections. This data is strongly related to the connection object defined in the CIP-specification. However the full functionality of the connection object is not implemented. Therefore this data can not be accessed with CIP means.
typedef enum ProductionTrigger ProductionTrigger
Enumeration Type Documentation
enum ConnectionManagerExtendedStatusCode
Connection Manager Error codes.
Enumerator:
kConnectionManagerExtendedStatusCodeSuccess
Obsolete code, should be General Status - Everything is ok
kConnectionManagerExtendedStatusCodeErrorConnectionInUseOrDuplicateForwardOpen
General Status has to be 0x01, Connection is already in use, or a duplicate Forward Open was received
kConnectionManagerExtendedStatusCodeErrorTransportClassAndTriggerCombinationNotSupported
General Status has to be 0x01, A Transport class and trigger combination has been specified, which is not supported by the target application
kConnectionManagerExtendedStatusCodeErrorOwnershipConflict
General Status has to be 0x01, Another connection has already reserved some needed resources
kConnectionManagerExtendedStatusCodeErrorConnectionTargetConnectionNotFound
General Status has to be 0x01, Forward Close error message, if connection to be closed is not found at the target
kConnectionManagerExtendedStatusCodeErrorTargetForConnectionNotConfigured
General Status has to be 0x01, Target application not configured and connection request does not contain data segment for configuration
kConnectionManagerExtendedStatusCodeRpiNotSupported
kConnectionManagerExtendedStatusCodeErrorRpiValuesNotAcceptable
General Status has to be 0x01, Requested RPI parameters outside of range, needs 6 16-bit extended status words, see Vol.1 Table 3-5.33
kConnectionManagerExtendedStatusCodeErrorNoMoreConnectionsAvailable
General Status has to be 0x01, No free connection slots available
kConnectionManagerExtendedStatusCodeErrorVendorIdOrProductcodeError
General Status has to be 0x01, The Product Code or Vendor ID in the electronic key logical segment does not match the Product Code or Vendor ID of the device, or if the compatibility bit is set and one or both are zero, or cannot be emulated.
kConnectionManagerExtendedStatusCodeErrorDeviceTypeError
General Status has to be 0x01, Device Type specified in the electronic key logical segment does not match the Device Type, or if the compatibility bit is set and Device Type is zero, or cannot be emulated.
kConnectionManagerExtendedStatusCodeErrorRevisionMismatch
General Status has to be 0x01, Major and minor revision specified in the electronic key logical segment is not a valid revision of the device, or if the compatibility bit is set and the requested Major Revision and/or Minor Revision is 0 or the device cannot emulate the specified revision.
kConnectionManagerExtendedStatusCodeNonListenOnlyConnectionNotOpened
General Status has to be 0x01, listen-only connection cannot be established, if no non-listen only connections are established
kConnectionManagerExtendedStatusCodeTargetObjectOutOfConnections
Maximum number of connections supported by the instance of the target object exceeded
kConnectionManagerExtendedStatusCodeProductionInhibitTimerGreaterThanRpi
The Production Inhibit Time is greater than the Target to Originator RPI
kConnectionManagerExtendedStatusCodeTransportClassNotSupported
The transport class requested in the Transport Type/Trigger parameter is not supported.
kConnectionManagerExtendedStatusCodeProductionTriggerNotSuppoerted
The production trigger requested in the Transport Type/Trigger parameter is not supported.
kConnectionManagerExtendedStatusCodeDirectionNotSupported
The direction requested in the Transport Type/Trigger parameter is not supported
kConnectionManagerExtendedStatusCodeInvalidOToTNetworkConnectionFixVar
Shall be returned as the result of specifying an O->T fixed / variable flag that is not supported.
kConnectionManagerExtendedStatusCodeInvalidTToONetworkConnectionFixVar
Shall be returned as the result of specifying an T->O fixed / variable flag that is not supported.
kConnectionManagerExtendedStatusCodeInvalidOToTNetworkConnectionPriority
Shall be returned as the result of specifying an O->T priority code that is not supported.
kConnectionManagerExtendedStatusCodeInvalidTToONetworkConnectionPriority
Shall be returned as the result of specifying an T->O priority code that is not supported.
kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionType
Shall be returned as the result of specifying an O->T connection type that is not supported
kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionType
Shall be returned as the result of specifying a T->O connection type that is not supported
kConnectionManagerExtendedStatusCodeInvalidOToTNetworkConnectionRedundantOwner
Shall be returned as the result of specifying an O->T Redundant Owner flag that is not supported.
kConnectionManagerExtendedStatusCodeInvalidConfigurationSize
The data segment provided in the Connection_Path parameter did not contain an acceptable number of 16-bit words for the the configuration application path requested. Two additional status words shall follow, the error code plus the max size in words
kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionSize
The size of the consuming object declared in the Forward_Open request and available on the target does not match the size declared in the O->T Network Connection Parameter. Two additional status words shall follow, the error code plus the max size in words
kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionSize
The size of the consuming object declared in the Forward_Open request and available on the target does not match the size declared in the T->O Network Connection Parameter. Two additional status words shall follow, the error code plus the max size in words
kConnectionManagerExtendedStatusCodeInvalidConfigurationApplicationPath
Configuration application path specified does not correspond to a valid configuration application path within the target application. This error could also be returned if a configuration application path was required, but not provided by a connection request.
kConnectionManagerExtendedStatusCodeInvalidConsumingApplicationPath
Consumed application path specified does not correspond to a valid consumed application path within the target application. This error could also be returned if a consumed application path was required, but not provided by a connection request.
kConnectionManagerExtendedStatusCodeInvalidProducingApplicationPath
Produced application path specified does not correspond to a valid produced application path within the target application. This error could also be returned if a produced application path was required, but not provided by a connection request.
kConnectionManagerExtendedStatusCodeConfigurationSymbolDoesNotExist
kConnectionManagerExtendedStatusCodeConsumingSymbolDoesNotExist
kConnectionManagerExtendedStatusCodeProducingSymbolDoesNotExist
kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo
kConnectionManagerExtendedStatusCodeInconsistentConsumeDataFormat
kConnectionManagerExtendedStatusCodeInconsistentProduceDataFormat
kConnectionManagerExtendedStatusCodeNullForwardOpenNotSupported
kConnectionManagerExtendedStatusCodeConnectionTimeoutMultiplierNotAcceptable
kConnectionManagerExtendedStatusCodeMismatchedTToONetworkConnectionFixVar
kConnectionManagerExtendedStatusCodeMismatchedTToONetworkConnectionPriority
kConnectionManagerExtendedStatusCodeMismatchedTransportClass
kConnectionManagerExtendedStatusCodeMismatchedTToOProductionTrigger
kConnectionManagerExtendedStatusCodeMismatchedTToOProductionInhibitTimeSegment
kConnectionManagerExtendedStatusCodeConnectionTimedOut
kConnectionManagerExtendedStatusCodeUnconnectedRequestTimedOut
kConnectionManagerExtendedStatusCodeErrorParameterErrorInUnconnectedSendService
kConnectionManagerExtendedStatusCodeMessageToLargeForUnconnectedSendService
kConnectionManagerExtendedStatusCodeUnconnectedAcknowledgeWithoutReply
kConnectionManagerExtendedStatusCodeNoBufferMemoryAvailable
kConnectionManagerExtendedStatusCodeNetworkBandwithNotAvailableForData
kConnectionManagerExtendedStatusCodeNoConsumedConnectionIdFilterAvailable
kConnectionManagerExtendedStatusCodeNotConfiguredToSendScheduledPriorityData
kConnectionManagerExtendedStatusCodeScheduleSignatureMismatch
kConnectionManagerExtendedStatusCodeScheduleSignatureValidationNotPossible
kConnectionManagerExtendedStatusCodePortNotAvailable
kConnectionManagerExtendedStatusCodeLinkAddressNotValid
kConnectionManagerExtendedStatusCodeErrorInvalidSegmentTypeInPath
kConnectionManagerExtendedStatusCodeForwardCloseServiceConnectionPathMismatch
kConnectionManagerExtendedStatusCodeSchedulingNotSpecified
kConnectionManagerExtendedStatusCodeLinkAddressToSelfInvalid
kConnectionManagerExtendedStatusCodeSecondaryResourcesUnavailable
kConnectionManagerExtendedStatusCodeRackConnectionAlreadyEstablished
kConnectionManagerExtendedStatusCodeModuleConnectionAlreadyEstablished
kConnectionManagerExtendedStatusCodeMiscellaneous
kConnectionManagerExtendedStatusCodeRedundantConnectionMismatch
kConnectionManagerExtendedStatusCodeNoMoreUserConfigurableLinkConsumerResourcesAvailableInTheProducingModule
kConnectionManagerExtendedStatusCodeNoUserConfigurableLinkConsumerResourcesConfiguredInTheProducingModule
kConnectionManagerExtendedStatusCodeNetworkLinkOffline
kConnectionManagerExtendedStatusCodeNoTargetApplicationDataAvailable
kConnectionManagerExtendedStatusCodeNoOriginatorApplicationDataAvailable
kConnectionManagerExtendedStatusCodeNodeAddressHasChangedSinceTheNetworkWasScheduled
kConnectionManagerExtendedStatusCodeNotConfiguredForOffSubnetMulticast
kConnectionManagerExtendedStatusCodeInvalidProduceConsumeDataFormat
kConnectionManagerExtendedStatusWrongCloser
Definition at line 47 of file cipconnectionmanager.h.
enum ConnectionManagerGeneralStatus
Enumerator:
kConnectionManagerGeneralStatusSuccess
General Status - Everything is ok
kConnectionManagerGeneralStatusExtendedStatus
Indicates that extended status is set
kConnectionManagerGeneralStatusResourceUnavailableForUnconnectedSend
kConnectionManagerGeneralStatusPathSegmentErrorInUnconnectedSend
kConnectionManagerGeneralStatusErrorInDataSegment
kConnectionManagerGeneralStatusObjectStateError
kConnectionManagerGeneralStatusDeviceStateError
kConnectionManagerGeneralStatusNotEnoughData
kConnectionManagerGeneralStatusTooMuchData
Definition at line 35 of file cipconnectionmanager.h.
enum ConnectionObjectFixedVariable
Enumerator:
kConnectionObjectFixedConnectionSize
kConnectionObjectVariableConnectionSize
Definition at line 225 of file cipconnectionmanager.h.
enum ConnectionState
States of a connection.
Enumerator:
kConnectionStateNonExistent
kConnectionStateConfiguring
kConnectionStateWaitingForConnectionId
only used in DeviceNet
kConnectionStateEstablished
kConnectionStateTimedOut
kConnectionStateDeferredDelete
only used in DeviceNet
kConnectionStateClosing
Definition at line 207 of file cipconnectionmanager.h.
enum ConnectionTriggerType
Enumerator:
kConnectionTriggerTypeProductionTriggerMask
kConnectionTriggerTypeCyclicConnection
kConnectionTriggerTypeChangeOfStateTriggeredConnection
kConnectionTriggerTypeApplicationTriggeredConnection
Definition at line 156 of file cipconnectionmanager.h.
enum ConnectionType
instance_type attributes
Enumerator:
kConnectionTypeExplicit
kConnectionTypeIoExclusiveOwner
kConnectionTypeIoInputOnly
kConnectionTypeIoListenOnly
Definition at line 218 of file cipconnectionmanager.h.
enum ForwardOpenConnectionType
Connection Type constants of the Forward Open service request Indicates either a.
Null Request
Point-to-point connection request (unicast)
Multicast connection request
Enumerator:
kForwardOpenConnectionTypeNull
kForwardOpenConnectionTypePointToPointConnection
kForwardOpenConnectionTypeMulticastConnection
kForwardOpenConnectionTypeReserved
Reserved and therefore invalid type
Definition at line 21 of file cipconnectionmanager.h.
enum ForwardOpenPriority
Enumerator:
kForwardOpenPriorityLow
kForwardOpenPriorityHigh
kForwardOpenPriorityScheduled
kForwardOpenPriorityUrgent
Definition at line 28 of file cipconnectionmanager.h.
enum ProductionTrigger
Enumerator:
kProductionTriggerInvalid
kProductionTriggerCyclic
kProductionTriggerChangeOfState
kProductionTriggerApplicationObjectTriggered
Definition at line 163 of file cipconnectionmanager.h.
enum WatchdogTimeoutAction
Possible values for the watch dog time out action of a connection.
Enumerator:
kWatchdogTimeoutActionTransitionToTimedOut
, invalid for explicit message connections
kWatchdogTimeoutActionAutoDelete
Default for explicit message connections, default for I/O connections on EIP
kWatchdogTimeoutActionAutoReset
Invalid for explicit message connections
kWatchdogTimeoutActionDeferredDelete
Only valid for DeviceNet, invalid for I/O connections
Definition at line 231 of file cipconnectionmanager.h.
Function Documentation
void AddNewActiveConnection (ConnectionObject * connection_object)
Insert the given connection object to the list of currently active and managed connections.
By adding a connection to the active connection list the connection manager will perform the supervision and handle the timing (e.g., timeout, production inhibit, etc).
Parameters:
connection_object pointer to the connection object to be added.
Definition at line 1605 of file cipconnectionmanager.c.
References connection_object::first_connection_object, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, and connection_object::state.
Referenced by EstablishClass3Connection(), and EstablishIoConnection().
void CloseConnection (ConnectionObject *RESTRICT connection_object)
Close the given connection.
This function will take the data form the connection and correctly closes the connection (e.g., open sockets)
Parameters:
connection_object pointer to the connection object structure to be closed
Definition at line 1582 of file cipconnectionmanager.c.
References CloseUdpSocket(), kConnectionStateNonExistent, kUdpCommuncationDirectionConsuming, kUdpCommuncationDirectionProducing, and RemoveFromActiveConnections().
Referenced by CloseAllConnections().
EipStatus ConnectionManagerInit (EipUint16 unique_connection_id)
Initialize the data of the connection manager object.
Parameters:
A unique connection id
Returns:
kEipStatusOk if successful, otherwise kEipStatusError
Definition at line 281 of file cipconnectionmanager.c.
References AddConnectableObject(), CreateCipClass(), EstablishClass3Connection(), EstablishIoConnection(), ForwardClose(), ForwardOpen(), g_incarnation_id, GetAttributeAll(), GetAttributeSingle(), GetConnectionOwner(), InitializeConnectionManager(), InitializeConnectionManagerData(), InsertService(), kEipStatusError, kEipStatusOk, kForwardClose, kForwardOpen, kGetAttributeAll, kGetAttributeSingle, and kGetConnectionOwner.
Referenced by CipStackInit().
void CopyConnectionData (ConnectionObject *RESTRICT destination, const ConnectionObject *RESTRICT const source)
Copy the given connection data from source to destination.
Parameters:
destination Destination of the copy operation
osurce Source of the copy operation
Definition at line 1598 of file cipconnectionmanager.c.
Referenced by EstablishClass3Connection(), and GetIoConnectionForConnectionData().
void GeneralConnectionConfiguration (ConnectionObject * connection_object)
Generate the ConnectionIDs and set the general configuration parameter in the given connection object.
Parameters:
connection_object pointer to the connection object that should be set up.
Definition at line 733 of file cipconnectionmanager.c.
References connection_object::cip_consumed_connection_id, connection_object::cip_produced_connection_id, connection_object::consumed_connection_size, connection_object::eip_level_sequence_count_consuming, connection_object::eip_level_sequence_count_producing, connection_object::expected_packet_rate, GetConnectionId(), GetConnectionObjectInitialInactivityWatchdogTimerValue(), connection_object::inactivity_watchdog_timer, kForwardOpenConnectionTypeMulticastConnection, kForwardOpenConnectionTypePointToPointConnection, kWatchdogTimeoutActionAutoDelete, connection_object::o_to_t_network_connection_parameter, connection_object::produced_connection_size, connection_object::production_inhibit_time, connection_object::production_inhibit_timer, connection_object::sequence_count_consuming, connection_object::sequence_count_producing, connection_object::t_to_o_network_connection_parameter, connection_object::transmission_trigger_timer, connection_object::transport_type_class_trigger, and connection_object::watchdog_timeout_action.
Referenced by EstablishClass3Connection(), and EstablishIoConnection().
ConnectionObject* GetConnectedObject (EipUint32 connection_id)
Definition at line 1144 of file cipconnectionmanager.c.
References connection_object::cip_consumed_connection_id, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, and connection_object::state.
Referenced by HandleReceivedConnectedData(), and NotifyConnectedCommonPacketFormat().
ConnectionObject* GetConnectedOutputAssembly (EipUint32 output_assembly_id)
Get a connection object for a given output assembly.
Parameters:
output_assembly_id requested output assembly of requested connection
Returns:
pointer to connected Object 0 .. connection not present in device
Definition at line 1161 of file cipconnectionmanager.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, kConnectionStateEstablished, connection_object::next_connection_object, and connection_object::state.
Referenced by GetExclusiveOwnerConnection().
EipUint32 GetConnectionObjectInactivityWatchdogTimerValue (ConnectionObject * connection_object)
Definition at line 727 of file cipconnectionmanager.c.
References connection_object::connection_timeout_multiplier, and connection_object::o_to_t_requested_packet_interval.
Referenced by GetConnectionObjectInitialInactivityWatchdogTimerValue(), HandleReceivedConnectedData(), and NotifyConnectedCommonPacketFormat().
ConnectionObjectFixedVariable GetConnectionObjectTargetToOriginatorFixedOrVariableConnectionSize (const ConnectionObject *const RESTRICT connection_object)
Definition at line 109 of file cipconnectionmanager.c.
References kConnectionObjectFixedConnectionSize, and kConnectionObjectVariableConnectionSize.
Referenced by SetupIoConnectionTargetToOriginatorConnectionPoint().
ForwardOpenPriority GetConnectionObjectTToOPriority (const ConnectionObject *const connection_object)
Definition at line 456 of file cipconnectionmanager.c.
References GetPriorityForSocket(), and connection_object::t_to_o_network_connection_parameter.
Referenced by OpenConsumingPointToPointConnection(), OpenMulticastConnection(), OpenProducingPointToPointConnection(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
ForwardOpenConnectionType GetConnectionType (EipUint16 network_connection_parameter)
returns the connection type of the supplied network connection parameter
Definition at line 442 of file cipconnectionmanager.c.
References OPENER_TRACE_INFO.
Referenced by EstablishIoConnection(), ForwardOpen(), OpenCommunicationChannels(), and ParseConnectionPath().
CipUint GetProductionInhibitTime (const ConnectionObject *const connection_object)
Definition at line 91 of file cipconnectionmanager.c.
References connection_object::production_inhibit_time.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
ProductionTrigger GetProductionTrigger (const ConnectionObject *const connection_object)
Definition at line 53 of file cipconnectionmanager.c.
References kProductionTriggerApplicationObjectTriggered, kProductionTriggerChangeOfState, kProductionTriggerCyclic, kProductionTriggerInvalid, and connection_object::transport_type_class_trigger.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
CipUdint GetTargetToOriginatorRequestedPackedInterval (const ConnectionObject *const connection_object)
CipUdint GetTargetToOriginatorRequestedPackedInterval (const ConnectionObject *const RESTRICT connection_object)
Definition at line 103 of file cipconnectionmanager.c.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
EipBool8 IsConnectedOutputAssembly (const EipUint32 instance_number)
Definition at line 1633 of file cipconnectionmanager.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, and connection_object::next_connection_object.
Referenced by SetAssemblyAttributeSingle().
void RemoveFromActiveConnections (ConnectionObject * connection_object)
Removes connection from the list of active connections.
Parameters:
connection_object Connection object to be removed from the active connection list
Definition at line 1615 of file cipconnectionmanager.c.
References connection_object::first_connection_object, kConnectionStateNonExistent, connection_object::next_connection_object, and connection_object::state.
Referenced by CloseCommunicationChannelsAndRemoveFromActiveConnectionsList(), CloseConnection(), and EstablishClass3Connection().
void SetProductionInhibitTime (const EipUint16 production_inhibit_time, ConnectionObject *const connection_object)
Definition at line 96 of file cipconnectionmanager.c.
References connection_object::production_inhibit_time.
Referenced by ProcessProductionInhibitTime().
void SetProductionTrigger (const ProductionTrigger production_trigger, ConnectionObject * connection_object)
< Invalid value
Definition at line 70 of file cipconnectionmanager.c.
References kProductionTriggerApplicationObjectTriggered, kProductionTriggerChangeOfState, kProductionTriggerCyclic, and connection_object::transport_type_class_trigger.