OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/enet_encap/endianconv.h File Reference
endianconv.h File Reference
Responsible for Endianess conversion.
#include "typedefs.h"
Enumerations
enum OpenerEndianess { kOpenerEndianessUnknown = -1, kOpENerEndianessLittle = 0, kOpENerEndianessBig = 1 }
Functions
int AddDintToMessage (const EipUint32 data, EipUint8 **const buffer)
Write an 32Bit integer to the network buffer.
int AddIntToMessage (const EipUint16 data, EipUint8 **const buffer)
Write an 16Bit integer to the network buffer.
int AddSintToMessage (const EipUint8 data, EipUint8 **const buffer)
converts UINT8 data from host to little endian an writes it to buffer.
void DetermineEndianess (void)
Detects Endianess of the platform and sets global g_nOpENerPlatformEndianess variable accordingly.
int EncapsulateIpAddress (EipUint16 port, EipUint32 address, EipByte **communication_buffer)
Encapsulate the sockaddr information as necessary for the Common Packet Format data items.
int FillNextNMessageOctetsWith (CipOctet value, unsigned int n, CipOctet **message)
int FillNextNMessageOctetsWithValueAndMoveToNextPosition (CipOctet value, unsigned int n, CipOctet **message)
CipByte GetByteFromMessage (const CipOctet **const buffer_address)
EipUint32 GetDintFromMessage (const EipUint8 **const buffer)
Get an 32Bit integer from the network buffer.
int GetEndianess (void)
Return the endianess identified on system startup.
EipUint16 GetIntFromMessage (const EipUint8 **const buffer)
Get an 16Bit integer from the network buffer, and moves pointer beyond the 16 bit value.
EipUint8 GetSintFromMessage (const EipUint8 **const buffer)
Reads EIP_UINT8 from *buffer and converts little endian to host.
CipUdint GetUdintFromMessage (const CipOctet **const buffer_address)
CipUint GetUintFromMessage (const CipOctet **const buffer_address)
CipUsint GetUsintFromMessage (const CipOctet **const buffer_address)
CipWord GetWordFromMessage (const CipOctet **const buffer_address)
void MoveMessageNOctets (int n, const CipOctet **message_runner)
Detailed Description
Responsible for Endianess conversion.
Definition in file endianconv.h.
Enumeration Type Documentation
enum OpenerEndianess
Enumerator
kOpenerEndianessUnknown
kOpENerEndianessLittle
kOpENerEndianessBig
Definition at line 15 of file endianconv.h.
Function Documentation
void DetermineEndianess (void)
Detects Endianess of the platform and sets global g_nOpENerPlatformEndianess variable accordingly.
Identify if we are running on a big or little endian system and set variable.
Detects Endianess of the platform and sets global variable g_nOpENerPlatformEndianess accordingly, whereas 0 equals little endian and 1 equals big endian
Definition at line 239 of file endianconv.c.
References g_opener_platform_endianess, kOpENerEndianessBig, and kOpENerEndianessLittle.
Referenced by EncapsulationInit().
int EncapsulateIpAddress (EipUint16 port, EipUint32 address, EipByte ** communication_buffer)
Encapsulate the sockaddr information as necessary for the Common Packet Format data items.
Converts and adds the provided port and IP address into an common packet format message
Parameters
port Port of the socket, has to be provided in big-endian
address IP address of the socket, has to be provided in big-endian
communcation_buffer The message buffer for sending the message
Definition at line 197 of file endianconv.c.
References AddDintToMessage(), AddIntToMessage(), g_opener_platform_endianess, kOpENerEndianessBig, and kOpENerEndianessLittle.
Referenced by AssembleLinearMessage(), and EncapsulateListIdentyResponseMessage().
int FillNextNMessageOctetsWith (CipOctet value, unsigned int n, CipOctet ** message)
Definition at line 263 of file endianconv.c.
Referenced by FillNextNMessageOctetsWithValueAndMoveToNextPosition().
int FillNextNMessageOctetsWithValueAndMoveToNextPosition (CipOctet value, unsigned int n, CipOctet ** message)
Definition at line 270 of file endianconv.c.
References FillNextNMessageOctetsWith(), and MoveMessageNOctets().
Referenced by AssembleLinearMessage().
CipByte GetByteFromMessage (const CipOctet **const buffer_address)
Definition at line 36 of file endianconv.c.
int GetEndianess (void)
Return the endianess identified on system startup.
Returns
-1 endianess has not been identified up to now
0 little endian system
1 big endian system
Return the endianess identified on system startup.
Returns
0 equals little endian and 1 equals big endian
Definition at line 254 of file endianconv.c.
References g_opener_platform_endianess.
CipUdint GetUdintFromMessage (const CipOctet **const buffer_address)
Definition at line 90 of file endianconv.c.
CipUint GetUintFromMessage (const CipOctet **const buffer_address)
Definition at line 64 of file endianconv.c.
CipUsint GetUsintFromMessage (const CipOctet **const buffer_address)
Definition at line 43 of file endianconv.c.
CipWord GetWordFromMessage (const CipOctet **const buffer_address)
Definition at line 71 of file endianconv.c.
void MoveMessageNOctets (int n, const CipOctet ** message_runner)
Definition at line 258 of file endianconv.c.
Referenced by CipEpathEncodeConnectionEpath(), CipEpathGetLogicalValue(), CipEpathSetLogicalValue(), ConnectionObjectInitializeFromMessage(), DetermineDelayTime(), EncapsulateData(), EncapsulateListIdentyResponseMessage(), FillNextNMessageOctetsWithValueAndMoveToNextPosition(), and GetElectronicKeyFormat4FromMessage().