OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/socket_timer.h File Reference
src/ports/socket_timer.h File Reference
#include "typedefs.h"
Data Structures
struct socket_timer
Data structure to store last usage times for sockets.
Typedefs
typedef struct socket_timer SocketTimer
Data structure to store last usage times for sockets.
Functions
SocketTimer * SocketTimerArrayGetEmptySocketTimer (SocketTimer *const array_of_socket_timers, const size_t array_length)
Get an empty Socket Timer entry.
SocketTimer * SocketTimerArrayGetSocketTimer (SocketTimer *const array_of_socket_timers, const size_t array_length, const int socket)
Get the Socket Timer entry with the spezified socket value.
void SocketTimerArrayInitialize (SocketTimer *const array_of_socket_timers, const size_t array_length)
Initializes an array of Socket Timer entries.
void SocketTimerClear (SocketTimer *const socket_timer)
Clears a Socket Timer entry.
MilliSeconds SocketTimerGetLastUpdate (SocketTimer *const socket_timer)
Gets time stamp of the last update.
void SocketTimerSetLastUpdate (SocketTimer *const socket_timer, const MilliSeconds actual_time)
Sets time stamp entry of the Socket Timer.
void SocketTimerSetSocket (SocketTimer *const socket_timer, const int socket)
Sets socket of a Socket Timer.
Typedef Documentation
typedef struct socket_timer SocketTimer
Data structure to store last usage times for sockets.
Function Documentation
SocketTimer* SocketTimerArrayGetEmptySocketTimer (SocketTimer *const array_of_socket_timers, const size_t array_length)
Get an empty Socket Timer entry.
Parameters:
array_of_socket_timers The Socket Timer array
array_length The Socket Timer array length
Returns:
An empty Socket Timer entry, or NULL if non is available
Definition at line 52 of file socket_timer.c.
References SocketTimerArrayGetSocketTimer().
Referenced by CheckAndHandleTcpListenerSocket(), and HandleReceivedRegisterSessionCommand().
SocketTimer* SocketTimerArrayGetSocketTimer (SocketTimer *const array_of_socket_timers, const size_t array_length, const int socket)
Get the Socket Timer entry with the spezified socket value.
Parameters:
array_of_socket_timers The Socket Timer array
array_length The Socket Timer array length
socket The socket value to be searched for
Returns:
The Socket Timer of found, otherwise NULL
Definition at line 40 of file socket_timer.c.
Referenced by CheckEncapsulationInactivity(), HandleDataOnTcpSocket(), RemoveSocketTimerFromList(), and SocketTimerArrayGetEmptySocketTimer().
void SocketTimerArrayInitialize (SocketTimer *const array_of_socket_timers, const size_t array_length)
Initializes an array of Socket Timer entries.
Parameters:
array_of_socket_timers The array of Socket Timer entries to be initialized
array_length the length of the array
Definition at line 33 of file socket_timer.c.
References SocketTimerClear().
Referenced by NetworkHandlerInitialize().
void SocketTimerClear (SocketTimer *const socket_timer)
Clears a Socket Timer entry.
Parameters:
socket_timer Socket Timer to be cleared
Definition at line 28 of file socket_timer.c.
References socket_timer::last_update, and socket_timer::socket.
Referenced by RemoveSocketTimerFromList(), and SocketTimerArrayInitialize().
MilliSeconds SocketTimerGetLastUpdate (SocketTimer *const socket_timer)
Gets time stamp of the last update.
Parameters:
socket_timer Socket Timer to be set
Returns:
Last update field value
Definition at line 24 of file socket_timer.c.
References socket_timer::last_update.
Referenced by CheckEncapsulationInactivity().
void SocketTimerSetLastUpdate (SocketTimer *const socket_timer, const MilliSeconds actual_time)
Sets time stamp entry of the Socket Timer.
Parameters:
socket_timer Socket Timer to be set
actual_time Time stamp
Definition at line 16 of file socket_timer.c.
References socket_timer::last_update, OPENER_TRACE_INFO, and socket_timer::socket.
Referenced by HandleDataOnTcpSocket(), and HandleReceivedRegisterSessionCommand().
void SocketTimerSetSocket (SocketTimer *const socket_timer, const int socket)
Sets socket of a Socket Timer.
Parameters:
socket_timer Socket Timer to be set
Socket value
Definition at line 11 of file socket_timer.c.
References OPENER_TRACE_INFO, and socket_timer::socket.
Referenced by HandleReceivedRegisterSessionCommand().