OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipelectronickey.c File Reference
src/cip/cipelectronickey.c File Reference
#include <stdlib.h>
#include "cipelectronickey.h"
Data Structures
struct electronic_key_format_4
Typedefs
typedef struct
electronic_key_format_4 ElectronicKeyFormat4
Functions
void ElectronicKeyFormat4Delete (ElectronicKeyFormat4 **electronic_key)
Destructor for the electroic key format 4 class.
CipUint ElectronicKeyFormat4GetDeviceType (const ElectronicKeyFormat4 *const electronic_key)
Gets the device type from a format 4 electronic key.
CipByte ElectronicKeyFormat4GetMajorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the major revision from an format 4 electronic key.
bool ElectronicKeyFormat4GetMajorRevisionCompatibility (const ElectronicKeyFormat4 *const electronic_key)
Gets the Compatibility flag from the format 4 electronic key.
CipUsint ElectronicKeyFormat4GetMinorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the minor revision from an format 4 electronic key.
CipUint ElectronicKeyFormat4GetProductCode (const ElectronicKeyFormat4 *const electronic_key)
Gets the product code from an format 4 electronic key.
CipUint ElectronicKeyFormat4GetVendorId (const ElectronicKeyFormat4 *const electronic_key)
Gets the vendor ID form the electronic key.
ElectronicKeyFormat4 * ElectronicKeyFormat4New ()
Constructor for the electroic key format 4 class.
void ElectronicKeyFormat4SetDeviceType (const CipUint device_type, ElectronicKeyFormat4 *const electronic_key)
Sets the device type in the electronic key.
void ElectronicKeyFormat4SetMajorRevisionCompatibility (const CipByte major_revision_compatibility, ElectronicKeyFormat4 *const electronic_key)
Sets the major revision byte including the compatibility flag.
void ElectronicKeyFormat4SetMinorRevision (const CipUsint minor_revision, ElectronicKeyFormat4 *const electronic_key)
Sets the devices minor revision in an format 4 electronic key.
void ElectronicKeyFormat4SetProductCode (const CipUint product_code, ElectronicKeyFormat4 *const electronic_key)
Set product code in the electronic key.
void ElectronicKeyFormat4SetVendorId (const CipUint vendor_id, ElectronicKeyFormat4 *const electronic_key)
Sets vendor ID in the electronic key.
Variables
const size_t kElectronicKeyFormat4Size = sizeof(ElectronicKeyFormat4)
Typedef Documentation
typedef struct electronic_key_format_4 ElectronicKeyFormat4
Function Documentation
void ElectronicKeyFormat4Delete (ElectronicKeyFormat4 ** electronic_key)
Destructor for the electroic key format 4 class.
Safe destructor/free, nulls the pointer after freeing it
Parameters:
electronic_key A format 4 electronic key
Definition at line 25 of file cipelectronickey.c.
Referenced by ParseConnectionPath().
CipUint ElectronicKeyFormat4GetDeviceType (const ElectronicKeyFormat4 *const electronic_key)
Gets the device type from a format 4 electronic key.
Parameters:
The format 4 electronic key from which the device type will be extracted
Returns:
The device type
Definition at line 47 of file cipelectronickey.c.
References electronic_key_format_4::device_type.
Referenced by ParseConnectionPath().
CipByte ElectronicKeyFormat4GetMajorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the major revision from an format 4 electronic key.
Parameters:
electronic_key An format 4 electronic key
Returns:
The device's major revision
Definition at line 69 of file cipelectronickey.c.
References electronic_key_format_4::major_revision_compatibility.
Referenced by ParseConnectionPath().
bool ElectronicKeyFormat4GetMajorRevisionCompatibility (const ElectronicKeyFormat4 *const electronic_key)
Gets the Compatibility flag from the format 4 electronic key.
Parameters:
electronic_key The format 4 electronic key to be read
Returns:
True if compatibility bit is set, false if otherwise
Definition at line 75 of file cipelectronickey.c.
References electronic_key_format_4::major_revision_compatibility.
Referenced by ParseConnectionPath().
CipUsint ElectronicKeyFormat4GetMinorRevision (const ElectronicKeyFormat4 *const electronic_key)
Gets the minor revision from an format 4 electronic key.
Parameters:
electronic_key The format 4 electronic key to be read
Returns:
The device's minor revision
Definition at line 90 of file cipelectronickey.c.
References electronic_key_format_4::minor_revision.
Referenced by ParseConnectionPath().
CipUint ElectronicKeyFormat4GetProductCode (const ElectronicKeyFormat4 *const electronic_key)
Gets the product code from an format 4 electronic key.
Parameters:
electronic_key The format 4 electronic key to be read
Returns:
The product code
Definition at line 58 of file cipelectronickey.c.
References electronic_key_format_4::product_code.
Referenced by ParseConnectionPath().
CipUint ElectronicKeyFormat4GetVendorId (const ElectronicKeyFormat4 *const electronic_key)
Gets the vendor ID form the electronic key.
Parameters:
electronic_key The format 4 electronic key from which the vendor ID will be extracted
Returns:
The vendor ID
Definition at line 36 of file cipelectronickey.c.
References electronic_key_format_4::vendor_id.
Referenced by ParseConnectionPath().
ElectronicKeyFormat4* ElectronicKeyFormat4New ()
Constructor for the electroic key format 4 class.
Returns:
A new unset electronic key
Definition at line 21 of file cipelectronickey.c.
Referenced by ParseConnectionPath().
void ElectronicKeyFormat4SetDeviceType (const CipUint device_type, ElectronicKeyFormat4 *const electronic_key)
Sets the device type in the electronic key.
Parameters:
device_type The device type which shall be inserted into the electronic key
electronic_key A format 4 electronic key
Definition at line 41 of file cipelectronickey.c.
References electronic_key_format_4::device_type.
Referenced by GetPathLogicalSegmentElectronicKeyFormat4().
void ElectronicKeyFormat4SetMajorRevisionCompatibility (const CipByte major_revision_compatibility, ElectronicKeyFormat4 *const electronic_key)
Sets the major revision byte including the compatibility flag.
Parameters:
major_revision_compatibility The major revision byte including the compatibility flag
electronic_key The electronic key to be modified
Definition at line 63 of file cipelectronickey.c.
References electronic_key_format_4::major_revision_compatibility.
Referenced by GetPathLogicalSegmentElectronicKeyFormat4().
void ElectronicKeyFormat4SetMinorRevision (const CipUsint minor_revision, ElectronicKeyFormat4 *const electronic_key)
Sets the devices minor revision in an format 4 electronic key.
Parameters:
minor_revision The minor revision to be set in the electronic key
electronic_key The electronic key to be modified
Definition at line 85 of file cipelectronickey.c.
References electronic_key_format_4::minor_revision.
Referenced by GetPathLogicalSegmentElectronicKeyFormat4().
void ElectronicKeyFormat4SetProductCode (const CipUint product_code, ElectronicKeyFormat4 *const electronic_key)
Set product code in the electronic key.
Parameters:
product_code The product code to be inserted
electronic_key The electronic key to be modified
Definition at line 52 of file cipelectronickey.c.
References electronic_key_format_4::product_code.
Referenced by GetPathLogicalSegmentElectronicKeyFormat4().
void ElectronicKeyFormat4SetVendorId (const CipUint vendor_id, ElectronicKeyFormat4 *const electronic_key)
Sets vendor ID in the electronic key.
Parameters:
vendor_id The vendor ID to be set into the electronic key
electronic_key The electronic key to be set - will be modified
Definition at line 30 of file cipelectronickey.c.
References electronic_key_format_4::vendor_id.
Referenced by GetPathLogicalSegmentElectronicKeyFormat4().
Variable Documentation
const size_t kElectronicKeyFormat4Size = sizeof(ElectronicKeyFormat4)
Definition at line 19 of file cipelectronickey.c.