OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/enet_encap/cpf.c File Reference
cpf.c File Reference
#include <string.h>
#include "cpf.h"
#include "opener_api.h"
#include "cipcommon.h"
#include "cipmessagerouter.h"
#include "endianconv.h"
#include "ciperror.h"
#include "cipconnectionmanager.h"
#include "trace.h"
#include "encap.h"
Functions
int AssembleIOMessage (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
int AssembleLinearMessage (const CipMessageRouterResponse *const message_router_response, const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Copy data from message_router_response struct and common_packet_format_data_item into linear memory in pa_msg for transmission over in encapsulation.
EipStatus CreateCommonPacketFormatStructure (const EipUint8 *data, size_t data_length, CipCommonPacketFormatData *common_packet_format_data)
Creates Common Packet Format structure out of data.
int EncodeConnectedAddressItem (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
int EncodeConnectedDataItemLength (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the Connected Data item length.
int EncodeDataItemData (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
int EncodeDataItemLength (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
int EncodeDataItemType (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
int EncodeExtendedStatus (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the extended status (length and data) into the message.
int EncodeExtendedStatusDataItems (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the extended status data items.
int EncodeExtendedStatusLength (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the length of the extended status data part.
int EncodeGeneralStatus (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the general status of a Router Response.
int EncodeItemCount (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Adds the item count to the message frame.
int EncodeMessageRouterResponseData (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the Message Router Response data.
int EncodeNullAddressItem (ENIPMessage *const outgoing_message)
Encodes a Null Address Item into the message frame.
int EncodeReplyService (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the reply service code for the requested service.
int EncodeReservedFieldOfLengthByte (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the reserved byte in the message router response.
int EncodeSequencedAddressItem (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes a sequenced address item into the message.
int EncodeSequenceNumber (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes a sequence number into the message.
int EncodeSockaddrInfoItemTypeId (int item_type, const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes the sockaddr info type id into the message.
int EncodeSockaddrInfoLength (int item_type, const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes the sockaddr info length into the message.
int EncodeUnconnectedDataItemLength (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encode the data item length of the unconnected data segment.
int NotifyCommonPacketFormat (EncapsulationData *const receive_data, const struct sockaddr *const originator_address, ENIPMessage *const outgoing_message)
int NotifyConnectedCommonPacketFormat (const EncapsulationData *const received_data, const struct sockaddr *const originator_address, ENIPMessage *const outgoing_message)
Variables
CipCommonPacketFormatData g_common_packet_format_data_item
Data storage for the any CPF data Currently we are single threaded and need only one CPF at the time. For future extensions towards multithreading maybe more CPF data items may be necessary.
const size_t item_count_field_size = 2
const size_t item_data_type_id_field_length = 2
const size_t sequenced_address_item_length = 8
Function Documentation
int EncodeConnectedAddressItem (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes a Connected Address Item into the message frame
Parameters
message The message frame
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
size The actual size of the message frame
Returns
The new size of the message frame after encoding
Definition at line 315 of file cpf.c.
References AddDintToMessage(), AddIntToMessage(), CipCommonPacketFormatData::address_item, AddressData::connection_identifier, enip_message::current_message_position, AddressItem::data, kCipItemIdConnectionAddress, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeConnectedDataItemLength (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the Connected Data item length.
Parameters
message_router_response The Router Response message which shall be answered
message Message frame to which the data is added
size Current size of the message buffer
Returns
The new size of the message buffer
Definition at line 443 of file cpf.c.
References AddIntToMessage(), enip_message::current_message_position, CipMessageRouterResponse::data_length, CipMessageRouterResponse::size_of_additional_status, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeDataItemData (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Adds the data items to the message frame
Parameters
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
message Message frame to which the data is added
size The actual size of the message frame
Returns
The new size of the message frame after encoding
Definition at line 421 of file cpf.c.
References AddSintToMessage(), enip_message::current_message_position, DataItem::data, CipCommonPacketFormatData::data_item, DataItem::length, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeDataItemLength (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Adds the data item section length to the message frame
Parameters
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
message The message frame
size The actual size of the message frame
Returns
The new size of the message frame after encoding
Definition at line 403 of file cpf.c.
References AddIntToMessage(), enip_message::current_message_position, CipCommonPacketFormatData::data_item, DataItem::length, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeDataItemType (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Adds the data item type to the message frame
Parameters
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
message The message frame
size The actual size of the message frame
Returns
The new size of the message frame after encoding
Definition at line 385 of file cpf.c.
References AddIntToMessage(), enip_message::current_message_position, CipCommonPacketFormatData::data_item, DataItem::type_id, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeExtendedStatus (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the extended status (length and data) into the message.
This function uses EncodeExtendedStatusLength and EncodeExtendedStatusDataItems to encode the complete extended status information into the message
Parameters
size Current size of the message buffer
message Message frame to which the data is added
message_router_response Router Response message to be processed
Returns
New size of the message buffer
Definition at line 581 of file cpf.c.
References EncodeExtendedStatusDataItems(), EncodeExtendedStatusLength(), and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeExtendedStatusDataItems (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the extended status data items.
Parameters
size Current size of the message buffer
message_router_response Router Response message to be processed
message Message frame to which the data is added
Returns
New size of the message buffer
Definition at line 555 of file cpf.c.
References AddIntToMessage(), CipMessageRouterResponse::additional_status, enip_message::current_message_position, CipMessageRouterResponse::size_of_additional_status, and enip_message::used_message_length.
Referenced by EncodeExtendedStatus().
int EncodeExtendedStatusLength (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the length of the extended status data part.
Parameters
size Current size of the message buffer
message Message frame to which the data is added
message_router_response Router Response message to be processed
Returns
New size of the message buffer
Definition at line 537 of file cpf.c.
References AddSintToMessage(), enip_message::current_message_position, CipMessageRouterResponse::size_of_additional_status, and enip_message::used_message_length.
Referenced by EncodeExtendedStatus().
int EncodeGeneralStatus (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the general status of a Router Response.
Parameters
size Current size of the message buffer
message Message frame to which the data is added
message_router_response Router Response message to be processed
Returns
New size of the message buffer
Definition at line 518 of file cpf.c.
References AddSintToMessage(), enip_message::current_message_position, CipMessageRouterResponse::general_status, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeItemCount (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Adds the item count to the message frame.
Parameters
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
message The message frame
size The actual size of the message frame
Returns
The new size of the message frame after encoding
Definition at line 367 of file cpf.c.
References AddIntToMessage(), enip_message::current_message_position, CipCommonPacketFormatData::item_count, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeMessageRouterResponseData (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the Message Router Response data.
Parameters
size Current size of the message buffer
message_router_response Router Response message to be processed
message Message frame to which the data is added
Definition at line 616 of file cpf.c.
References AddSintToMessage(), enip_message::current_message_position, CipMessageRouterResponse::data, CipMessageRouterResponse::data_length, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeNullAddressItem (ENIPMessage *const outgoing_message)
Encodes a Null Address Item into the message frame.
Parameters
message The message frame
size The actual size of the message frame
Returns
The new size of the message frame after encoding
Definition at line 297 of file cpf.c.
References AddIntToMessage(), enip_message::current_message_position, kCipItemIdNullAddress, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeReplyService (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the reply service code for the requested service.
Parameters
size The current size of the message buffer
message Message frame to which the data is added
message_rounter_response The router response message data structure to be processed
Returns
The new size of the message buffer
Definition at line 482 of file cpf.c.
References AddSintToMessage(), enip_message::current_message_position, CipMessageRouterResponse::reply_service, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeReservedFieldOfLengthByte (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encodes the reserved byte in the message router response.
Parameters
size Current size of the message buffer
message Message frame to which the data is added
message_router_response Router Response message to be processed
Returns
New size of the message buffer
Definition at line 500 of file cpf.c.
References AddSintToMessage(), enip_message::current_message_position, CipMessageRouterResponse::reserved, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeSequencedAddressItem (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes a sequenced address item into the message.
Parameters
message Pointer to the message memory start
common_packet_format_data_item Common Packet Format item which is used in the encoding
size Size of the message at the start of the function
Returns
New message size after encoding
Definition at line 339 of file cpf.c.
References AddDintToMessage(), AddIntToMessage(), CipCommonPacketFormatData::address_item, AddressData::connection_identifier, enip_message::current_message_position, AddressItem::data, kCipItemIdSequencedAddressItem, AddressData::sequence_number, sequenced_address_item_length, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeSequenceNumber (const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes a sequence number into the message.
Parameters
size The current size of the message buffer
common_packet_format_data_item
message Message frame to which the data is added
Returns
The new size of the message buffer
Definition at line 463 of file cpf.c.
References AddIntToMessage(), CipCommonPacketFormatData::address_item, enip_message::current_message_position, AddressItem::data, AddressData::sequence_number, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeSockaddrInfoItemTypeId (int item_type, const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes the sockaddr info type id into the message.
Parameters
size Current size of the message buffer
item_type
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
message Message frame to which the encoded data is added
Returns
New size of the message buffer
Definition at line 637 of file cpf.c.
References AddIntToMessage(), CipCommonPacketFormatData::address_info_item, enip_message::current_message_position, OPENER_ASSERT, SocketAddressInfoItem::type_id, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeSockaddrInfoLength (int item_type, const CipCommonPacketFormatData *const common_packet_format_data_item, ENIPMessage *const outgoing_message)
Encodes the sockaddr info length into the message.
Parameters
size Current size of the message buffer
item_type
common_packet_format_data_item The Common Packet Format data structure from which the message is constructed
message Message frame to which the encoded data is added
Returns
New size of the message buffer
Definition at line 659 of file cpf.c.
References AddIntToMessage(), CipCommonPacketFormatData::address_info_item, enip_message::current_message_position, SocketAddressInfoItem::length, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
int EncodeUnconnectedDataItemLength (const CipMessageRouterResponse *const message_router_response, ENIPMessage *const outgoing_message)
Encode the data item length of the unconnected data segment.
Parameters
size Current size of the message buffer
message_router_response Router Response message to be processed
message Message frame to which the data is added
Returns
New size of the message buffer
Definition at line 599 of file cpf.c.
References AddIntToMessage(), enip_message::current_message_position, CipMessageRouterResponse::data_length, CipMessageRouterResponse::size_of_additional_status, and enip_message::used_message_length.
Referenced by AssembleLinearMessage().
Variable Documentation
const size_t item_count_field_size = 2
The size of the item count field in the message
Definition at line 19 of file cpf.c.
const size_t item_data_type_id_field_length = 2
The size of the item count field in the message
Definition at line 20 of file cpf.c.
const size_t sequenced_address_item_length = 8
Definition at line 22 of file cpf.c.
Referenced by EncodeSequencedAddressItem().