OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/ciptcpipinterface.h File Reference
ciptcpipinterface.h File Reference
Public interface of the TCP/IP Interface Object.
#include "typedefs.h"
#include "ciptypes.h"
Data Structures
struct multicast_address_configuration
Multicast Configuration struct, called Mcast config.
Typedefs
typedef struct
multicast_address_configuration MulticastAddressConfiguration
Multicast Configuration struct, called Mcast config.
Functions
EipStatus CipTcpIpInterfaceInit (void)
Initializing the data structures of the TCP/IP interface object.
EipUint16 GetEncapsulationInactivityTimeout (CipInstance *instance)
Public Method to get Encapsulation Inactivity Timeout Value.
void ShutdownTcpIpInterface (void)
Clean up the allocated data of the TCP/IP interface object.
Variables
CipUint g_encapsulation_inactivity_timeout
#13 Number of seconds of inactivity before TCP connection is closed
MulticastAddressConfiguration g_multicast_configuration
#9 The multicast configuration for this device
CipUsint g_time_to_live_value
#8 the time to live value to be used for multi-cast connections
CipString hostname_
CipTcpIpNetworkInterfaceConfiguration interface_configuration_
Detailed Description
Public interface of the TCP/IP Interface Object.
Definition in file ciptcpipinterface.h.
Typedef Documentation
typedef struct multicast_address_configuration MulticastAddressConfiguration
Multicast Configuration struct, called Mcast config.
Function Documentation
EipStatus CipTcpIpInterfaceInit (void)
Initializing the data structures of the TCP/IP interface object.
Returns
kEipStatusOk on success, otherwise kEipStatusError
Definition at line 165 of file ciptcpipinterface.c.
References configuration_capability_, configuration_control_, CreateCipClass(), g_encapsulation_inactivity_timeout, g_time_to_live_value, GetAttributeAllTcpIpInterface(), GetAttributeSingleTcpIpInterface(), GetCipInstance(), InsertAttribute(), InsertService(), kCipAny, kCipDword, kCipEpath, kCipString, kCipUdintUdintUdintUdintUdintString, kCipUint, kCipUsint, kEipStatusError, kEipStatusOk, kGetableSingleAndAll, kGetAttributeAll, kGetAttributeSingle, kSetAndGetAble, kSetAttributeSingle, SetAttributeSingleTcp(), and tcp_status_.
Referenced by CipStackInit().
EipUint16 GetEncapsulationInactivityTimeout (CipInstance * instance)
Public Method to get Encapsulation Inactivity Timeout Value.
Definition at line 384 of file ciptcpipinterface.c.
References CipAttributeStruct::data, GetCipAttribute(), and OPENER_ASSERT.
void ShutdownTcpIpInterface (void)
Clean up the allocated data of the TCP/IP interface object.
Currently this is the host name string and the domain name string.
Definition at line 215 of file ciptcpipinterface.c.
References CipFree(), CipTcpIpNetworkInterfaceConfiguration::domain_name, and CipString::string.
Referenced by ShutdownCipStack().
Variable Documentation
CipUint g_encapsulation_inactivity_timeout
#13 Number of seconds of inactivity before TCP connection is closed
Number of seconds of inactivity before TCP connection is closed, Default is 120
Currently we implemented with the default value of 120 seconds.
Definition at line 63 of file ciptcpipinterface.c.
MulticastAddressConfiguration g_multicast_configuration
#9 The multicast configuration for this device
Multicast configuration
Currently we implement it non set-able and use the default allocation algorithm
Definition at line 53 of file ciptcpipinterface.c.
Referenced by ConfigureIpMacAddress(), ConfigureNetworkInterface(), CreateUdpSocket(), OpenMulticastConnection(), and OpenProducingMulticastConnection().
CipUsint g_time_to_live_value
#8 the time to live value to be used for multi-cast connections
Time-to-live value for IP multicast packets. Default is 1; Minimum is 1; Maximum is 255
Currently we implement it non set-able and with the default value of 1.
Definition at line 46 of file ciptcpipinterface.c.
Referenced by CipTcpIpInterfaceInit(), and CreateUdpSocket().
CipString hostname_
#6 Hostname
Definition at line 40 of file ciptcpipinterface.c.
Referenced by ConfigureHostName().
CipTcpIpNetworkInterfaceConfiguration interface_configuration_
#5 IP, network mask, gateway, name server 1 & 2, domain name
Definition at line 30 of file ciptcpipinterface.c.