OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipcommon.c File Reference
src/cip/cipcommon.c File Reference
#include <string.h>
#include "cipcommon.h"
#include "opener_user_conf.h"
#include "opener_api.h"
#include "cipidentity.h"
#include "ciptcpipinterface.h"
#include "cipethernetlink.h"
#include "cipconnectionmanager.h"
#include "endianconv.h"
#include "encap.h"
#include "ciperror.h"
#include "cipassembly.h"
#include "cipmessagerouter.h"
#include "cipqos.h"
#include "cpf.h"
#include "trace.h"
#include "appcontype.h"
#include "cipepath.h"
#include "stdlib.h"
Functions
CipInstance * AddCIPInstance (CipClass *RESTRICT const class, const EipUint32 instance_id)
Create one instance of a given class with a certain instance number.
CipInstance * AddCipInstances (CipClass *RESTRICT const cip_class, const int number_of_instances)
Add a number of CIP instances to a given CIP class.
void AllocateAttributeMasks (CipClass *target_class)
Allocates Attribute bitmasks.
size_t CalculateIndex (EipUint16 attribute_number)
Calculates Byte-Index of Attribute.
void CipStackInit (const EipUint16 unique_connection_id)
Initialize and setup the CIP-stack.
CipClass * CreateCipClass (const EipUint32 class_id, const int number_of_class_attributes, const EipUint32 highest_class_attribute_number, const int number_of_class_services, const int number_of_instance_attributes, const EipUint32 highest_instance_attribute_number, const int number_of_instance_services, const int number_of_instances, char *name, const EipUint16 revision, void(*InitializeCipClass)(CipClass *))
Allocate memory for new CIP Class and attributes.
int DecodeData (const EipUint8 cip_type, void *const data, const EipUint8 **const message)
Retrieve the given data according to CIP encoding from the message buffer.
int DecodePaddedEPath (CipEpath *epath, const EipUint8 **message)
Decodes padded EPath.
int EncodeData (const EipUint8 cip_type, const void *const cip_data, EipUint8 **cip_message)
Produce the data according to CIP encoding onto the message buffer.
int EncodeEPath (CipEpath *epath, EipUint8 **message)
EipStatus GetAttributeAll (CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response, struct sockaddr *originator_address)
Generic implementation of the GetAttributeAll CIP service.
EipStatus GetAttributeSingle (CipInstance *RESTRICT const instance, CipMessageRouterRequest *const message_router_request, CipMessageRouterResponse *const message_router_response, struct sockaddr *originator_address)
Generic implementation of the GetAttributeSingle CIP service.
CipAttributeStruct * GetCipAttribute (const CipInstance *const instance, const EipUint16 attribute_number)
Get a pointer to an instance's attribute.
void InsertAttribute (CipInstance *const instance, const EipUint16 attribute_number, const EipUint8 cip_type, void *const data, const EipByte cip_flags)
Insert an attribute in an instance of a CIP class.
void InsertService (const CipClass *const class, const EipUint8 service_number, const CipServiceFunction service_function, char *const service_name)
Insert a service in an instance of a CIP object.
EipStatus NotifyClass (const CipClass *RESTRICT const cip_class, CipMessageRouterRequest *const message_router_request, CipMessageRouterResponse *const message_router_response, struct sockaddr *originator_address)
Check if requested service present in class/instance and call appropriate service.
void ShutdownCipStack (void)
Shutdown of the CIP stack.
Variables
EipUint8 g_message_data_reply_buffer [OPENER_MESSAGE_DATA_REPLY_BUFFER]
Function Documentation
int DecodePaddedEPath (CipEpath * epath, const EipUint8 ** data)
Decodes padded EPath.
Parameters:
epath EPath to the receiving element
message CIP Message to decode
Returns:
Number of decoded bytes
Definition at line 802 of file cipcommon.c.
References CipEpath::attribute_number, CipEpath::class_id, GetIntFromMessage(), CipEpath::instance_number, kEipStatusError, kSegmentTypeReserved, LOGICAL_SEGMENT_FORMAT_EIGHT_BIT, LOGICAL_SEGMENT_FORMAT_SIXTEEN_BIT, LOGICAL_SEGMENT_TYPE_ATTRIBUTE_ID, LOGICAL_SEGMENT_TYPE_CLASS_ID, LOGICAL_SEGMENT_TYPE_INSTANCE_ID, OPENER_TRACE_ERR, CipEpath::path_size, and SEGMENT_TYPE_LOGICAL_SEGMENT.
Referenced by CreateMessageRouterRequestStructure().
int EncodeEPath (CipEpath * epath, EipUint8 ** message)
Definition at line 746 of file cipcommon.c.
References AddIntToMessage(), CipEpath::attribute_number, CipEpath::class_id, CipEpath::instance_number, and CipEpath::path_size.
Referenced by EncodeData().
EipStatus GetAttributeAll (CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response, struct sockaddr * originator_address)
Generic implementation of the GetAttributeAll CIP service.
Copy all attributes from Object into the global message buffer.
Parameters:
instance pointer to object instance with data.
message_router_request pointer to MR request.
message_router_response pointer for MR response.
Returns:
length of data stream >0 .. success 0 .. no reply to send
Definition at line 688 of file cipcommon.c.
References CipEpath::attribute_number, CipAttributeStruct::attribute_number, cip_instance::attributes, CalculateIndex(), cip_instance::cip_class, CipMessageRouterResponse::data, CipMessageRouterResponse::data_length, CipMessageRouterResponse::general_status, cip_class::get_all_bit_mask, cip_instance::instance_number, kCipErrorServiceNotSupported, kEipStatusError, kEipStatusOk, kEipStatusOkSend, kGetAttributeSingle, cip_class::number_of_attributes, cip_class::number_of_services, OPENER_TRACE_INFO, CipMessageRouterResponse::reply_service, CipMessageRouterRequest::request_path, cip_service_struct::service_function, cip_service_struct::service_number, cip_class::services, and CipMessageRouterResponse::size_of_additional_status.
Referenced by CipEthernetLinkInit(), CipIdentityInit(), ConnectionManagerInit(), and CreateCipClass().
EipStatus GetAttributeSingle (CipInstance *RESTRICT const instance, CipMessageRouterRequest *const message_router_request, CipMessageRouterResponse *const message_router_response, struct sockaddr * originator_address)
Generic implementation of the GetAttributeSingle CIP service.
Check from classID which Object requests an attribute, search if object has the appropriate attribute implemented.
Parameters:
instance pointer to instance.
message_router_request pointer to request.
message_router_response pointer to response.
Returns:
status >0 .. success -1 .. requested attribute not available
Definition at line 387 of file cipcommon.c.
References CipEpath::attribute_number, BeforeAssemblyDataSend(), CalculateIndex(), CipMessageRouterResponse::data, CipAttributeStruct::data, CipMessageRouterResponse::data_length, EncodeData(), CipMessageRouterResponse::general_status, GetCipAttribute(), kCipByteArray, kCipErrorAttributeNotSupported, kCipErrorSuccess, kEipStatusOkSend, kGetAttributeAll, OPENER_ASSERT, OPENER_TRACE_INFO, CipMessageRouterResponse::reply_service, CipMessageRouterRequest::request_path, CipMessageRouterRequest::service, CipMessageRouterResponse::size_of_additional_status, and CipAttributeStruct::type.
Referenced by CipEthernetLinkInit(), CipIdentityInit(), CipMessageRouterInit(), ConnectionManagerInit(), CreateAssemblyClass(), CreateCipClass(), and GetAttributeSingleQoS().
EipStatus NotifyClass (const CipClass *const RESTRICT cip_class, CipMessageRouterRequest *const message_router_request, CipMessageRouterResponse *const message_router_response, struct sockaddr * originator_address)
Check if requested service present in class/instance and call appropriate service.
Parameters:
class class receiving the message
message_router_request request message
message_router_response reply message
Returns:
kEipStatusOkSend ... success
kEipStatusOk ... no reply to send back
kEipStatusError ... error
Definition at line 73 of file cipcommon.c.
References cip_instance::cip_class, CipMessageRouterResponse::data_length, CipMessageRouterResponse::general_status, GetCipInstance(), CipEpath::instance_number, kCipErrorPathDestinationUnknown, kCipErrorServiceNotSupported, kEipStatusOkSend, cip_service_struct::name, cip_class::number_of_services, OPENER_ASSERT, OPENER_TRACE_INFO, OPENER_TRACE_WARN, CipMessageRouterResponse::reply_service, CipMessageRouterRequest::request_path, CipMessageRouterRequest::service, cip_service_struct::service_function, cip_service_struct::service_number, cip_class::services, and CipMessageRouterResponse::size_of_additional_status.
Referenced by NotifyMessageRouter().
Variable Documentation
EipUint8 g_message_data_reply_buffer[OPENER_MESSAGE_DATA_REPLY_BUFFER]
Reply buffer
Definition at line 29 of file cipcommon.c.
Referenced by AssembleIOMessage(), CipMessageRouterInit(), NotifyMessageRouter(), and SendConnectedData().