OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/WIN32/networkhandler.h File Reference
src/ports/WIN32/networkhandler.h File Reference
#include "typedefs.h"
Defines
#define OPENER_SOCKET_WOULD_BLOCK WSAEWOULDBLOCK
Typedefs
typedef unsigned long socklen_t
Functions
void CloseSocketPlatform (int socket_handle)
Platform dependent code to close a socket.
MicroSeconds GetMicroSeconds (void)
This function shall return the current time in microseconds relative to epoch, and shall be implemented in a port specific networkhandler.
MilliSeconds GetMilliSeconds (void)
This function shall return the current time in milliseconds relative to epoch, and shall be implemented in a port specific networkhandler.
EipStatus NetworkHandlerInitializePlatform (void)
Executes platform dependent network handler initialization code.
int SetSocketToNonBlocking (int socket_handle)
Define Documentation
#define OPENER_SOCKET_WOULD_BLOCK WSAEWOULDBLOCK
Definition at line 11 of file networkhandler.h.
Typedef Documentation
typedef unsigned long socklen_t
Definition at line 13 of file networkhandler.h.
Function Documentation
void CloseSocketPlatform (int socket_handle)
Platform dependent code to close a socket.
Parameters:
socket_handle The socket handle to be closed
Definition at line 35 of file networkhandler.c.
Referenced by CloseSocket().
MicroSeconds GetMicroSeconds (void)
This function shall return the current time in microseconds relative to epoch, and shall be implemented in a port specific networkhandler.
Returns:
Current time relative to epoch as MicroSeconds
Definition at line 16 of file networkhandler.c.
References OPENER_ASSERT.
Referenced by GetMilliSeconds().
MilliSeconds GetMilliSeconds (void)
This function shall return the current time in milliseconds relative to epoch, and shall be implemented in a port specific networkhandler.
Returns:
Current time relative to epoch as MilliSeconds
Definition at line 26 of file networkhandler.c.
References GetMicroSeconds(), and getMicroSeconds().
Referenced by NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
EipStatus NetworkHandlerInitializePlatform (void)
Executes platform dependent network handler initialization code.
Returns:
EipStatusOk if initialization was successful, otherwise EipStatusError
Definition at line 30 of file networkhandler.c.
References kEipStatusOk.
Referenced by NetworkHandlerInitialize().
int SetSocketToNonBlocking (int socket_handle)
Definition at line 40 of file networkhandler.c.
Referenced by CreateUdpSocket(), and NetworkHandlerInitialize().