OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipclass3connection.h File Reference
src/cip/cipclass3connection.h File Reference
CIP Class 3 connection * Explicit Connection Object State Transition Diagram.
#include "opener_api.h"
#include "cipconnectionmanager.h"
#include "cipconnectionobject.h"
Typedefs
typedef EipStatus(* CipConnectionStateHandler)(CipConnectionObject *RESTRICT const connection_object, ConnectionObjectState new_state)
Functions
EipStatus CipClass3ConnectionObjectStateEstablishedHandler (CipConnectionObject *RESTRICT const connection_object, ConnectionObjectState new_state)
EipStatus EstablishClass3Connection (CipConnectionObject *RESTRICT const connection_object, EipUint16 *const extended_error)
Check if Class3 connection is available and if yes setup all data.
void InitializeClass3ConnectionData (void)
Initializes the explicit connections mechanism.
Detailed Description
CIP Class 3 connection * Explicit Connection Object State Transition Diagram.
----------------------------------------------
Definition in file cipclass3connection.h.
Typedef Documentation
typedef EipStatus(* CipConnectionStateHandler)(CipConnectionObject *RESTRICT const connection_object, ConnectionObjectState new_state)
Definition at line 35 of file cipclass3connection.h.
Function Documentation
EipStatus CipClass3ConnectionObjectStateEstablishedHandler (CipConnectionObject *RESTRICT const connection_object, ConnectionObjectState new_state)
Definition at line 71 of file cipclass3connection.c.
References ConnectionObjectInitializeEmpty(), ConnectionObjectSetState(), kConnectionObjectStateNonExistent, kEipStatusError, and kEipStatusOk.
EipStatus EstablishClass3Connection (CipConnectionObject *RESTRICT const connection_object, EipUint16 *const extended_error)
Check if Class3 connection is available and if yes setup all data.
This function can be called after all data has been parsed from the forward open request
Parameters:
connection_object pointer to the connection object structure holding the parsed data from the forward open request
extended_error the extended error code in case an error happened
Returns:
general status on the establishment
kEipStatusOk ... on success
On an error the general status code to be put into the response
Definition at line 18 of file cipclass3connection.c.
References AddNewActiveConnection(), CloseConnection(), cip_connection_object::connection_close_function, cip_connection_object::connection_timeout_function, ConnectionObjectDeepCopy(), ConnectionObjectGeneralConfiguration(), ConnectionObjectSetInstanceType(), GetFreeExplicitConnection(), kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeErrorNoMoreConnectionsAvailable, kConnectionObjectInstanceTypeExplicitMessaging, and kEipStatusOk.
Referenced by ConnectionManagerInit().
void InitializeClass3ConnectionData (void)
Initializes the explicit connections mechanism.
Prepares the available explicit connection slots for use at the start of the OpENer
Definition at line 66 of file cipclass3connection.c.
References OPENER_CIP_NUM_EXPLICIT_CONNS.
Referenced by InitializeConnectionManagerData().