OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/POSIX/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <sys/capability.h>
#include "generic_networkhandler.h"
#include "opener_api.h"
#include "cipcommon.h"
#include "trace.h"
#include "networkconfig.h"
#include "doublylinkedlist.h"
#include "cipconnectionobject.h"
Functions
void LeaveStack (int signal)
Signal handler function for ending stack execution.
int main (int argc, char *arg[])
Variables
int g_end_stack = 0
Flag indicating if the stack should end its execution.
Function Documentation
void LeaveStack (int signal)
Signal handler function for ending stack execution.
Parameters
signal the signal we received
Definition at line 119 of file main.c.
References g_end_stack, and OPENER_TRACE_STATE.
Referenced by main().
int main (int argc, char * arg[])
Definition at line 32 of file main.c.
References CipConnectionObjectListArrayAllocator(), CipConnectionObjectListArrayFree(), CipStackInit(), ConfigureDomainName(), ConfigureHostName(), ConfigureMacAddress(), ConfigureNetworkInterface(), connection_list, DoublyLinkedListInitialize(), g_end_stack, kEipStatusError, kEipStatusOk, LeaveStack(), NetworkHandlerFinish(), NetworkHandlerInitialize(), NetworkHandlerProcessOnce(), OPENER_TRACE_ERR, SetDeviceSerialNumber(), and ShutdownCipStack().
Variable Documentation
int g_end_stack = 0
Flag indicating if the stack should end its execution.
Definition at line 29 of file main.c.
Referenced by LeaveStack(), and main().