OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipethernetlink.h File Reference
cipethernetlink.h File Reference
#include "typedefs.h"
#include "ciptypes.h"
Data Structures
struct CipEthernetLinkObject
Data of an CIP Ethernet Link object.
Macros
#define CIP_ETHERNETLINK_CLASS_CODE 0xF6
Functions
EipStatus CipEthernetLinkInit (void)
Initialize the Ethernet Link Objects data.
int EncodeInterfaceCapability (EipUint8 **pa_acMsg)
int EncodeInterfaceControl (EipUint8 **pa_acMsg)
int EncodeInterfaceCounters (EipUint8 **pa_acMsg)
int EncodeMediaCounters (EipUint8 **pa_acMsg)
EipStatus GetAttributeSingleEthernetLink (CipInstance *RESTRICT const instance, CipMessageRouterRequest *const message_router_request, CipMessageRouterResponse *const message_router_response, struct sockaddr *originator_address, const int encapsulation_session)
Variables
CipEthernetLinkObject g_ethernet_link
Macro Definition Documentation
#define CIP_ETHERNETLINK_CLASS_CODE 0xF6
Definition at line 12 of file cipethernetlink.h.
Referenced by CipEthernetLinkInit().
Function Documentation
EipStatus CipEthernetLinkInit (void)
Initialize the Ethernet Link Objects data.
Returns
kEipStatusOk if initialization was successful, otherwise kEipStatusError
Definition at line 68 of file cipethernetlink.c.
References CIP_ETHERNETLINK_CLASS_CODE, CreateCipClass(), dummy_attribute_udint, dummy_attribute_usint, g_ethernet_link, GetAttributeAll(), GetAttributeSingleEthernetLink(), GetCipInstance(), InsertAttribute(), InsertService(), CipEthernetLinkObject::interface_flags, CipEthernetLinkObject::interface_speed, kCip6Usint, kCipAny, kCipDword, kCipShortString, kCipUdint, kCipUsint, kEipStatusError, kEipStatusOk, kGetableAll, kGetableSingleAndAll, kGetAttributeAll, kGetAttributeSingle, and CipEthernetLinkObject::physical_address.
Referenced by CipStackInit().
int EncodeInterfaceCapability (EipUint8 ** pa_acMsg)
Definition at line 149 of file cipethernetlink.c.
References CipEthernetLinkInterfaceCapability::capability_bits, EncodeData(), speed_duplex_array_entry::interface_duplex_mode, speed_duplex_array_entry::interface_speed, kCipDword, kCipUint, kCipUsint, speed_duplex_options::speed_duplex_array, speed_duplex_options::speed_duplex_array_count, and CipEthernetLinkInterfaceCapability::speed_duplex_options.
Referenced by GetAttributeSingleEthernetLink().
int EncodeInterfaceControl (EipUint8 ** pa_acMsg)
Definition at line 138 of file cipethernetlink.c.
References CipEthernetLinkInterfaceControl::control_bits, EncodeData(), CipEthernetLinkInterfaceControl::forced_interface_speed, kCipUint, and kCipWord.
Referenced by GetAttributeSingleEthernetLink().
int EncodeInterfaceCounters (EipUint8 ** pa_acMsg)
Definition at line 120 of file cipethernetlink.c.
References dummy_attribute_udint, EncodeData(), and kCipUdint.
Referenced by GetAttributeSingleEthernetLink().
int EncodeMediaCounters (EipUint8 ** pa_acMsg)
Definition at line 129 of file cipethernetlink.c.
References dummy_attribute_udint, EncodeData(), and kCipUdint.
Referenced by GetAttributeSingleEthernetLink().
EipStatus GetAttributeSingleEthernetLink (CipInstance *RESTRICT const instance, CipMessageRouterRequest *const message_router_request, CipMessageRouterResponse *const message_router_response, struct sockaddr * originator_address, const int encapsulation_session)
Definition at line 175 of file cipethernetlink.c.
References CipEpath::attribute_number, CalculateIndex(), CipMessageRouterResponse::data, CipAttributeStruct::data, CipMessageRouterResponse::data_length, EncodeInterfaceCapability(), EncodeInterfaceControl(), EncodeInterfaceCounters(), EncodeMediaCounters(), CipMessageRouterResponse::general_status, GetAttributeSingle(), GetCipAttribute(), kCipErrorAttributeNotSupported, kCipErrorSuccess, kEipStatusOkSend, kGetAttributeAll, OPENER_TRACE_INFO, CipMessageRouterResponse::reply_service, CipMessageRouterRequest::request_path, CipMessageRouterRequest::service, and CipMessageRouterResponse::size_of_additional_status.
Referenced by CipEthernetLinkInit().
Variable Documentation
CipEthernetLinkObject g_ethernet_link
Definition at line 45 of file cipethernetlink.h.
Referenced by CipEthernetLinkInit(), ConfigureIpMacAddress(), and ConfigureMacAddress().