OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/appcontype.c File Reference
src/cip/appcontype.c File Reference
#include <string.h>
#include "appcontype.h"
#include "cipconnectionmanager.h"
#include "opener_api.h"
#include "assert.h"
#include "trace.h"
Data Structures
struct ExclusiveOwnerConnection
Exclusive Owner connection data.
struct InputOnlyConnection
Input Only connection data.
struct ListenOnlyConnection
Listen Only connection data.
Functions
void CloseAllConnections (void)
void CloseAllConnectionsForInputWithSameType (const EipUint32 input_point, const ConnectionType instance_type)
Close all connection producing the same input and have the same type (i.e., listen only or input only).
void ConfigureExclusiveOwnerConnectionPoint (const unsigned int connection_number, const unsigned int output_assembly, const unsigned int input_assembly, const unsigned int config_assembly)
Configures the connection point for an exclusive owner connection.
void ConfigureInputOnlyConnectionPoint (const unsigned int connection_number, const unsigned int output_assembly, const unsigned int input_assembly, const unsigned int config_assembly)
Configures the connection point for an input only connection.
void ConfigureListenOnlyConnectionPoint (const unsigned int connection_number, const unsigned int output_assembly, const unsigned int input_assembly, const unsigned int config_assembly)
Configures the connection point for a listen only connection.
EipBool8 ConnectionWithSameConfigPointExists (const EipUint32 config_point)
Check if there is an established connection that uses the same config point.
ConnectionObject * GetExclusiveOwnerConnection (const ConnectionObject *RESTRICT connection_object, EipUint16 *const extended_error)
Takes an ConnectionObject and searches and returns an Exclusive Owner Connection based on the ConnectionObject, if there is non it returns NULL.
ConnectionObject * GetExistingProducerMulticastConnection (const EipUint32 input_point)
Check if there exists already an exclusive owner or listen only connection which produces the input assembly.
ConnectionObject * GetInputOnlyConnection (const ConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
Takes an ConnectionObject and searches and returns an Input Only Connection based on the ConnectionObject, if there is non it returns NULL.
ConnectionObject * GetIoConnectionForConnectionData (ConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
check if for the given connection data received in a forward_open request a suitable connection is available.
ConnectionObject * GetListenOnlyConnection (const ConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
Takes an ConnectionObject and searches and returns an Listen Only Connection based on the ConnectionObject, if there is non it returns NULL.
ConnectionObject * GetNextNonControlMasterConnection (const EipUint32 input_point)
check if there exists an producing multicast exclusive owner or listen only connection that should produce the same input but is not in charge of the connection.
void InitializeIoConnectionData (void)
Variables
ConnectionObject * g_active_connection_list
External globals needed from connectionmanager.c.
ExclusiveOwnerConnection g_exlusive_owner_connections [OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS]
InputOnlyConnection g_input_only_connections [OPENER_CIP_NUM_INPUT_ONLY_CONNS]
ListenOnlyConnection g_listen_only_connections [OPENER_CIP_NUM_LISTEN_ONLY_CONNS]
Function Documentation
void CloseAllConnections (void)
@ brief close all open connections.
For I/O connections the sockets will be freed. The sockets for explicit connections are handled by the encapsulation layer, and freed there.
Definition at line 372 of file appcontype.c.
References CloseConnection(), connection_object::connection_close_function, and g_active_connection_list.
Referenced by ResetDevice(), and ShutdownCipStack().
void CloseAllConnectionsForInputWithSameType (const EipUint32 input_point, const ConnectionType instance_type)
Close all connection producing the same input and have the same type (i.e., listen only or input only).
Parameters:
input_point the input point
instance_type the connection application type
Definition at line 349 of file appcontype.c.
References CheckIoConnectionEvent(), connection_object::connection_close_function, connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, connection_object::instance_type, kIoConnectionEventClosed, and connection_object::next_connection_object.
Referenced by CloseIoConnection(), and HandleIoConnectionTimeOut().
EipBool8 ConnectionWithSameConfigPointExists (const EipUint32 config_point)
Check if there is an established connection that uses the same config point.
Parameters:
config_point The configuration point
Returns:
true if connection was found, otherwise false
Definition at line 385 of file appcontype.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, and connection_object::next_connection_object.
Referenced by HandleConfigData().
ConnectionObject * GetExclusiveOwnerConnection (const ConnectionObject *RESTRICT connection_object, EipUint16 *const extended_error)
Takes an ConnectionObject and searches and returns an Exclusive Owner Connection based on the ConnectionObject, if there is non it returns NULL.
Parameters:
connection_object Connection Object which will be searched for in the Exclusive Owner Connections
extended_error Pointer to the extended error variable, will be written if an error occurs
Returns:
The corresponding Exclusive Owner Connection or NULL if there is non
Definition at line 169 of file appcontype.c.
References ExclusiveOwnerConnection::config_assembly, ExclusiveOwnerConnection::connection_data, GetConnectedOutputAssembly(), ExclusiveOwnerConnection::input_assembly, kConnectionManagerExtendedStatusCodeErrorOwnershipConflict, OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS, and OPENER_TRACE_INFO.
Referenced by GetIoConnectionForConnectionData().
ConnectionObject* GetExistingProducerMulticastConnection (const EipUint32 input_point)
Check if there exists already an exclusive owner or listen only connection which produces the input assembly.
Parameters:
input_point the Input point to be produced
Returns:
if a connection could be found a pointer to this connection if not NULL
Definition at line 286 of file appcontype.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, connection_object::instance_type, kConnectionTypeIoExclusiveOwner, kConnectionTypeIoInputOnly, kForwardOpenConnectionTypeMulticastConnection, kUdpCommuncationDirectionProducing, connection_object::next_connection_object, connection_object::socket, and connection_object::t_to_o_network_connection_parameter.
Referenced by GetListenOnlyConnection(), and OpenProducingMulticastConnection().
ConnectionObject * GetInputOnlyConnection (const ConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
Takes an ConnectionObject and searches and returns an Input Only Connection based on the ConnectionObject, if there is non it returns NULL.
Parameters:
connection_object Connection Object which will be searched for in the Input Only Connections
extended_error Pointer to the extended error variable, will be written if an error occurs
Returns:
The corresponding Exclusive Owner Connection or NULL if there is non
Definition at line 199 of file appcontype.c.
References InputOnlyConnection::connection_data, kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo, kConnectionManagerExtendedStatusCodeInvalidProducingApplicationPath, kConnectionManagerExtendedStatusCodeTargetObjectOutOfConnections, kConnectionStateNonExistent, OPENER_CIP_NUM_INPUT_ONLY_CONNS, and OPENER_CIP_NUM_INPUT_ONLY_CONNS_PER_CON_PATH.
Referenced by GetIoConnectionForConnectionData().
ConnectionObject* GetIoConnectionForConnectionData (ConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
check if for the given connection data received in a forward_open request a suitable connection is available.
If a suitable connection is found the connection data is transfered the application connection type is set (i.e., EConnType).
Parameters:
connection_object connection data to be used
extended_error pointer to the extended_error variable, if an error occurred this value has the according error code for the response
Returns:
on success: A pointer to the connection object already containing the connection data given in connection_object.
on error: NULL
Definition at line 127 of file appcontype.c.
References CopyConnectionData(), GetExclusiveOwnerConnection(), GetInputOnlyConnection(), GetListenOnlyConnection(), kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo, kConnectionTypeIoExclusiveOwner, kConnectionTypeIoInputOnly, and kConnectionTypeIoListenOnly.
Referenced by EstablishIoConnection().
ConnectionObject * GetListenOnlyConnection (const ConnectionObject *const RESTRICT connection_object, EipUint16 *const extended_error)
Takes an ConnectionObject and searches and returns an Listen Only Connection based on the ConnectionObject, if there is non it returns NULL.
Parameters:
connection_object Connection Object which will be searched for in the Listen Only Connections
extended_error Pointer to the extended error variable, will be written if an error occurs
Returns:
The corresponding Exclusive Owner Connection or NULL if there is non
Definition at line 234 of file appcontype.c.
References ListenOnlyConnection::connection_data, GetExistingProducerMulticastConnection(), kConnectionManagerExtendedStatusCodeInconsistentApplicationPathCombo, kConnectionManagerExtendedStatusCodeInvalidProducingApplicationPath, kConnectionManagerExtendedStatusCodeNonListenOnlyConnectionNotOpened, kConnectionManagerExtendedStatusCodeTargetObjectOutOfConnections, kConnectionStateNonExistent, kForwardOpenConnectionTypeMulticastConnection, OPENER_CIP_NUM_LISTEN_ONLY_CONNS, and OPENER_CIP_NUM_LISTEN_ONLY_CONNS_PER_CON_PATH.
Referenced by GetIoConnectionForConnectionData().
ConnectionObject* GetNextNonControlMasterConnection (const EipUint32 input_point)
check if there exists an producing multicast exclusive owner or listen only connection that should produce the same input but is not in charge of the connection.
Parameters:
input_point the produced input
Returns:
if a connection could be found the pointer to this connection otherwise NULL.
Definition at line 317 of file appcontype.c.
References connection_object::connection_path, CipConnectionPath::connection_point, g_active_connection_list, connection_object::instance_type, kConnectionTypeIoExclusiveOwner, kConnectionTypeIoInputOnly, kForwardOpenConnectionTypeMulticastConnection, kUdpCommuncationDirectionProducing, connection_object::next_connection_object, connection_object::socket, and connection_object::t_to_o_network_connection_parameter.
Referenced by CloseIoConnection(), and HandleIoConnectionTimeOut().
void InitializeIoConnectionData (void)
Definition at line 397 of file appcontype.c.
References OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS, OPENER_CIP_NUM_INPUT_ONLY_CONNS, and OPENER_CIP_NUM_LISTEN_ONLY_CONNS.
Referenced by InitializeConnectionManagerData().
Variable Documentation
ConnectionObject* g_active_connection_list
External globals needed from connectionmanager.c.
External globals needed from connectionmanager.c.
An implicit list structure inside the ConnectionObject, so the g_active_connection_list holds the first element of the list
Definition at line 134 of file cipconnectionmanager.c.
Referenced by AddNewActiveConnection(), CheckAndHandleConsumingUdpSockets(), CheckForExistingConnection(), CloseAllConnections(), CloseAllConnectionsForInputWithSameType(), ConnectionWithSameConfigPointExists(), ForwardClose(), GetConnectedObject(), GetConnectedOutputAssembly(), GetExistingProducerMulticastConnection(), GetNextNonControlMasterConnection(), IsConnectedOutputAssembly(), ManageConnections(), SetupIoConnectionTargetToOriginatorConnectionPoint(), and TriggerConnections().
ExclusiveOwnerConnection g_exlusive_owner_connections[OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS]
Exclusive Owner connections
Definition at line 46 of file appcontype.c.
InputOnlyConnection g_input_only_connections[OPENER_CIP_NUM_INPUT_ONLY_CONNS]
Input Only connections
Definition at line 48 of file appcontype.c.
ListenOnlyConnection g_listen_only_connections[OPENER_CIP_NUM_LISTEN_ONLY_CONNS]
Listen Only connections
Definition at line 50 of file appcontype.c.