OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipconnectionobject.h File Reference
cipconnectionobject.h File Reference
#include "typedefs.h"
#include "ciptypes.h"
#include "opener_user_conf.h"
#include "opener_api.h"
#include "doublylinkedlist.h"
#include "cipelectronickey.h"
#include "cipepath.h"
Data Structures
struct cip_connection_object
Macros
#define CIP_CONNECTION_OBJECT_CODE 0x05
Typedefs
typedef struct
cip_connection_object CipConnectionObject
typedef EipStatus(* CipConnectionStateHandler)(CipConnectionObject *RESTRICT const connection_object, ConnectionObjectState new_state)
Enumerations
enum ConnectionObjectConnectionSizeType { kConnectionObjectConnectionSizeTypeFixed, kConnectionObjectConnectionSizeTypeVariable }
enum ConnectionObjectConnectionType { kConnectionObjectConnectionTypeNull = 0, kConnectionObjectConnectionTypeMulticast, kConnectionObjectConnectionTypePointToPoint, kConnectionObjectConnectionTypeInvalid }
enum ConnectionObjectInstanceType {
kConnectionObjectInstanceTypeInvalid = -1, kConnectionObjectInstanceTypeExplicitMessaging = 0, kConnectionObjectInstanceTypeIO, kConnectionObjectInstanceTypeIOExclusiveOwner,
kConnectionObjectInstanceTypeIOInputOnly, kConnectionObjectInstanceTypeIOListenOnly, kConnectionObjectInstanceTypeCipBridged
}
enum ConnectionObjectPriority { kConnectionObjectPriorityLow = 0, kConnectionObjectPriorityHigh, kConnectionObjectPriorityScheduled, kConnectionObjectPriorityUrgent }
enum ConnectionObjectSocketType { kConnectionObjectSocketTypeProducing = 0, kConnectionObjectSocketTypeConsuming = 1 }
enum ConnectionObjectState {
kConnectionObjectStateNonExistent = 0, kConnectionObjectStateConfiguring, kConnectionObjectStateWaitingForConnectionID, kConnectionObjectStateEstablished,
kConnectionObjectStateTimedOut, kConnectionObjectStateDeferredDelete, kConnectionObjectStateClosing, kConnectionObjectStateInvalid
}
enum ConnectionObjectTransportClassTriggerDirection { kConnectionObjectTransportClassTriggerDirectionClient = 0, kConnectionObjectTransportClassTriggerDirectionServer }
enum ConnectionObjectTransportClassTriggerProductionTrigger { kConnectionObjectTransportClassTriggerProductionTriggerInvalid = -1, kConnectionObjectTransportClassTriggerProductionTriggerCyclic = 0, kConnectionObjectTransportClassTriggerProductionTriggerChangeOfState, kConnectionObjectTransportClassTriggerProductionTriggerApplicationObject }
enum ConnectionObjectTransportClassTriggerTransportClass {
kConnectionObjectTransportClassTriggerTransportClassInvalid = -1, kConnectionObjectTransportClassTriggerTransportClass0 = 0, kConnectionObjectTransportClassTriggerTransportClass1, kConnectionObjectTransportClassTriggerTransportClass2,
kConnectionObjectTransportClassTriggerTransportClass3
}
enum ConnectionObjectWatchdogTimeoutAction {
kConnectionObjectWatchdogTimeoutActionTransitionToTimedOut = 0, kConnectionObjectWatchdogTimeoutActionAutoDelete, kConnectionObjectWatchdogTimeoutActionAutoReset, kConnectionObjectWatchdogTimeoutActionDeferredDelete,
kConnectionObjectWatchdogTimeoutActionInvalid
}
Possible values for the watch dog time out action of a connection.
Functions
CipConnectionObject * CipConnectionObjectCreate (const CipOctet *message)
Array allocator.
void CipConnectionObjectDelete (CipConnectionObject **connection_object)
Array deallocator.
DoublyLinkedListNode * CipConnectionObjectListArrayAllocator ()
void CipConnectionObjectListArrayFree (DoublyLinkedListNode **node)
void ConnectionObjectDeepCopy (CipConnectionObject *RESTRICT destination, const CipConnectionObject *RESTRICT const source)
Copy the given connection data from source to destination.
bool ConnectionObjectEqualOriginator (const CipConnectionObject *const object1, const CipConnectionObject *const object2)
void ConnectionObjectGeneralConfiguration (CipConnectionObject *const connection_object)
Generate the ConnectionIDs and set the general configuration parameter in the given connection object.
CipUdint ConnectionObjectGetCipConsumedConnectionID (const CipConnectionObject *const connection_object)
CipUdint ConnectionObjectGetCipProducedConnectionID (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetConnectionSerialNumber (const CipConnectionObject *const connection_object)
CipUsint ConnectionObjectGetConnectionTimeoutMultiplier (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetConsumedConnectionPathLength (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetConsumedConnectionSize (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetExpectedPacketRate (const CipConnectionObject *const connection_object)
ConnectionObjectInstanceType ConnectionObjectGetInstanceType (const CipConnectionObject *const connection_object)
CipUsint ConnectionObjectGetInstanceTypeForAttribute (const CipConnectionObject *const connection_object)
CipUdint ConnectionObjectGetOriginatorSerialNumber (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetOriginatorVendorId (const CipConnectionObject *const connection_object)
size_t ConnectionObjectGetOToTConnectionSize (const CipConnectionObject *const connection_object)
ConnectionObjectConnectionSizeType ConnectionObjectGetOToTConnectionSizeType (const CipConnectionObject *const connection_object)
ConnectionObjectConnectionType ConnectionObjectGetOToTConnectionType (const CipConnectionObject *const connection_object)
ConnectionObjectPriority ConnectionObjectGetOToTPriority (const CipConnectionObject *const connection_object)
CipUdint ConnectionObjectGetOToTRequestedPacketInterval (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetProducedConnectionPathLength (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetProducedConnectionSize (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetProductionInhibitTime (const CipConnectionObject *const connection_object)
CipUint ConnectionObjectGetRequestedPacketInterval (const CipConnectionObject *const connection_object)
ConnectionObjectState ConnectionObjectGetState (const CipConnectionObject *const connection_object)
ConnectionObjectTransportClassTriggerDirection ConnectionObjectGetTransportClassTriggerDirection (const CipConnectionObject *const connection_object)
ConnectionObjectTransportClassTriggerProductionTrigger ConnectionObjectGetTransportClassTriggerProductionTrigger (const CipConnectionObject *const connection_object)
ConnectionObjectTransportClassTriggerTransportClass ConnectionObjectGetTransportClassTriggerTransportClass (const CipConnectionObject *const connection_object)
size_t ConnectionObjectGetTToOConnectionSize (const CipConnectionObject *const connection_object)
ConnectionObjectConnectionSizeType ConnectionObjectGetTToOConnectionSizeType (const CipConnectionObject *const connection_object)
ConnectionObjectConnectionType ConnectionObjectGetTToOConnectionType (const CipConnectionObject *const connection_object)
ConnectionObjectPriority ConnectionObjectGetTToOPriority (const CipConnectionObject *const connection_object)
CipUdint ConnectionObjectGetTToORequestedPacketInterval (const CipConnectionObject *const connection_object)
ConnectionObjectWatchdogTimeoutAction ConnectionObjectGetWatchdogTimeoutAction (const CipConnectionObject *const connection_object)
void ConnectionObjectInitializeEmpty (CipConnectionObject *const connection_object)
void ConnectionObjectInitializeFromMessage (const CipOctet **message, CipConnectionObject *const connection_object)
bool ConnectionObjectIsOToTRedundantOwner (const CipConnectionObject *const connection_object)
bool ConnectionObjectIsTToORedundantOwner (const CipConnectionObject *const connection_object)
bool ConnectionObjectIsTypeIOConnection (const CipConnectionObject *const connection_object)
void ConnectionObjectResetInactivityWatchdogTimerValue (CipConnectionObject *const connection_object)
void ConnectionObjectResetLastPackageInactivityTimerValue (CipConnectionObject *const connection_object)
void ConnectionObjectResetProductionInhibitTimer (CipConnectionObject *const connection_object)
void ConnectionObjectSetCipConsumedConnectionID (CipConnectionObject *const connection_object, const CipUdint cip_consumed_connection_id)
void ConnectionObjectSetCipProducedConnectionID (CipConnectionObject *const connection_object, const CipUdint cip_produced_connection_id)
void ConnectionObjectSetConnectionSerialNumber (CipConnectionObject *connection_object, const CipUint connection_serial_number)
void ConnectionObjectSetConnectionTimeoutMultiplier (CipConnectionObject *const connection_object, const CipUsint connection_timeout_multiplier)
void ConnectionObjectSetConsumedConnectionPathLength (CipConnectionObject *const connection_object, const CipUint consumed_connection_path_length)
void ConnectionObjectSetConsumedConnectionSize (CipConnectionObject *const connection_object, const CipUint consumed_connection_size)
void ConnectionObjectSetExpectedPacketRate (CipConnectionObject *const connection_object)
Sets the expected packet rate according to the rules of the CIP specification.
void ConnectionObjectSetInstanceType (CipConnectionObject *const connection_object, const ConnectionObjectInstanceType instance_type)
void ConnectionObjectSetOriginatorSerialNumber (CipConnectionObject *connection_object, CipUdint originator_serial_number)
void ConnectionObjectSetOriginatorVendorId (CipConnectionObject *connection_object, const CipUint vendor_id)
void ConnectionObjectSetOToTRequestedPacketInterval (CipConnectionObject *connection_object, const CipUdint requested_packet_interval)
void ConnectionObjectSetProducedConnectionPathLength (CipConnectionObject *const connection_object, const CipUint produced_connection_path_length)
void ConnectionObjectSetProducedConnectionSize (CipConnectionObject *const connection_object, const CipUint produced_connection_size)
void ConnectionObjectSetProductionInhibitTime (CipConnectionObject *const connection_object, const CipUint production_inhibit_time)
void ConnectionObjectSetState (CipConnectionObject *const connection_object, const ConnectionObjectState state)
void ConnectionObjectSetTToORequestedPacketInterval (CipConnectionObject *connection_object, const CipUdint requested_packet_interval)
void ConnectionObjectSetWatchdogTimeoutAction (CipConnectionObject *const connection_object, const CipUsint watchdog_timeout_action)
bool EqualConnectionTriad (const CipConnectionObject *const object1, const CipConnectionObject *const object2)
Macro Definition Documentation
#define CIP_CONNECTION_OBJECT_CODE 0x05
Definition at line 18 of file cipconnectionobject.h.
Typedef Documentation
typedef struct cip_connection_object CipConnectionObject
Definition at line 98 of file cipconnectionobject.h.
typedef EipStatus(* CipConnectionStateHandler)(CipConnectionObject *RESTRICT const connection_object, ConnectionObjectState new_state)
Definition at line 100 of file cipconnectionobject.h.
Enumeration Type Documentation
enum ConnectionObjectConnectionSizeType
Enumerator
kConnectionObjectConnectionSizeTypeFixed
kConnectionObjectConnectionSizeTypeVariable
Definition at line 88 of file cipconnectionobject.h.
enum ConnectionObjectConnectionType
Enumerator
kConnectionObjectConnectionTypeNull
kConnectionObjectConnectionTypeMulticast
kConnectionObjectConnectionTypePointToPoint
kConnectionObjectConnectionTypeInvalid
Definition at line 74 of file cipconnectionobject.h.
enum ConnectionObjectInstanceType
Enumerator
kConnectionObjectInstanceTypeInvalid
Invalid instance type - shall never occur!
kConnectionObjectInstanceTypeExplicitMessaging
Connection is an explicit messaging connection
kConnectionObjectInstanceTypeIO
Connection is an I/O connection
kConnectionObjectInstanceTypeIOExclusiveOwner
Also I/O connection, only for easy differentiation
kConnectionObjectInstanceTypeIOInputOnly
Also I/O connection, only for easy differentiation
kConnectionObjectInstanceTypeIOListenOnly
Also I/O connection, only for easy differentiation
kConnectionObjectInstanceTypeCipBridged
Connection is a bridged connection
Definition at line 31 of file cipconnectionobject.h.
enum ConnectionObjectPriority
Enumerator
kConnectionObjectPriorityLow
kConnectionObjectPriorityHigh
kConnectionObjectPriorityScheduled
kConnectionObjectPriorityUrgent
Definition at line 81 of file cipconnectionobject.h.
enum ConnectionObjectSocketType
Enumerator
kConnectionObjectSocketTypeProducing
kConnectionObjectSocketTypeConsuming
Definition at line 93 of file cipconnectionobject.h.
enum ConnectionObjectState
Enumerator
kConnectionObjectStateNonExistent
Connection is non existent
kConnectionObjectStateConfiguring
Waiting for both to be configured and to apply the configuration
kConnectionObjectStateWaitingForConnectionID
Only used for device net
kConnectionObjectStateEstablished
Connection is established
kConnectionObjectStateTimedOut
Connection timed out - inactivity or watchdog timer expired
kConnectionObjectStateDeferredDelete
Only used for device net
kConnectionObjectStateClosing
For CIP bridged connections - have to wait for a successful forward close
kConnectionObjectStateInvalid
An invalid state, shall never occur!
Definition at line 20 of file cipconnectionobject.h.
enum ConnectionObjectTransportClassTriggerDirection
Enumerator
kConnectionObjectTransportClassTriggerDirectionClient
Endpoint provides client behavior
kConnectionObjectTransportClassTriggerDirectionServer
Endpoint provides server behavior - production trigger bits are to be ignored
Definition at line 41 of file cipconnectionobject.h.
enum ConnectionObjectTransportClassTriggerProductionTrigger
Enumerator
kConnectionObjectTransportClassTriggerProductionTriggerInvalid
Invalid Production trigger - shall never occur!
kConnectionObjectTransportClassTriggerProductionTriggerCyclic
Transmission Trigger Timer trigger data production
kConnectionObjectTransportClassTriggerProductionTriggerChangeOfState
Production is trigger when change-of-state is detected by the Application Object
kConnectionObjectTransportClassTriggerProductionTriggerApplicationObject
The Application Object decided when production is triggered
Definition at line 46 of file cipconnectionobject.h.
enum ConnectionObjectTransportClassTriggerTransportClass
Enumerator
kConnectionObjectTransportClassTriggerTransportClassInvalid
Invalid Transport Class - shall never occur!
kConnectionObjectTransportClassTriggerTransportClass0
Class 0 producing or consuming connection, based on Direction
kConnectionObjectTransportClassTriggerTransportClass1
Class 1 producing or consuming connection, based on Direction
kConnectionObjectTransportClassTriggerTransportClass2
Class 2 producing and consuming connection, Client starts producing
kConnectionObjectTransportClassTriggerTransportClass3
Class 3 producing and consuming connection, Client starts producing
Definition at line 53 of file cipconnectionobject.h.
enum ConnectionObjectWatchdogTimeoutAction
Possible values for the watch dog time out action of a connection.
Only positive values allowed
Enumerator
kConnectionObjectWatchdogTimeoutActionTransitionToTimedOut
Default for I/O connections, invalid for Explicit Messaging
kConnectionObjectWatchdogTimeoutActionAutoDelete
Default for explicit connections
kConnectionObjectWatchdogTimeoutActionAutoReset
Invalid for explicit connections
kConnectionObjectWatchdogTimeoutActionDeferredDelete
Only for Device Net, invalid for I/O connections
kConnectionObjectWatchdogTimeoutActionInvalid
Invalid Watchdog Timeout Action - shall never occur!
Definition at line 66 of file cipconnectionobject.h.
Function Documentation
CipConnectionObject* CipConnectionObjectCreate (const CipOctet * message)
Array allocator.
Definition at line 106 of file cipconnectionobject.c.
void CipConnectionObjectDelete (CipConnectionObject ** connection_object)
Array deallocator.
DoublyLinkedListNode* CipConnectionObjectListArrayAllocator ()
Definition at line 59 of file cipconnectionobject.c.
References OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS, OPENER_CIP_NUM_EXPLICIT_CONNS, OPENER_CIP_NUM_INPUT_ONLY_CONNS, and OPENER_CIP_NUM_LISTEN_ONLY_CONNS.
Referenced by main().
void CipConnectionObjectListArrayFree (DoublyLinkedListNode ** node)
Definition at line 74 of file cipconnectionobject.c.
References OPENER_TRACE_ERR.
Referenced by main().
void ConnectionObjectDeepCopy (CipConnectionObject *RESTRICT destination, const CipConnectionObject *RESTRICT const source)
Copy the given connection data from source to destination.
Parameters
destination Destination of the copy operation
source Source of the copy operation
Definition at line 745 of file cipconnectionobject.c.
Referenced by EstablishClass3Connection(), and GetIoConnectionForConnectionData().
bool ConnectionObjectEqualOriginator (const CipConnectionObject *const object1, const CipConnectionObject *const object2)
Definition at line 800 of file cipconnectionobject.c.
References cip_connection_object::originator_serial_number, and cip_connection_object::originator_vendor_id.
Referenced by CheckForTimedOutConnectionsAndCloseTCPConnections().
void ConnectionObjectGeneralConfiguration (CipConnectionObject *const connection_object)
Generate the ConnectionIDs and set the general configuration parameter in the given connection object.
Parameters
connection_object pointer to the connection object that should be set up.
Definition at line 766 of file cipconnectionobject.c.
References ConnectionObjectGetOToTConnectionType(), ConnectionObjectGetTToOConnectionType(), ConnectionObjectResetProductionInhibitTimer(), ConnectionObjectResetSequenceCounts(), ConnectionObjectSetCipConsumedConnectionID(), ConnectionObjectSetCipProducedConnectionID(), ConnectionObjectSetWatchdogTimeoutAction(), GetConnectionId(), kConnectionObjectConnectionTypeMulticast, kConnectionObjectConnectionTypePointToPoint, kConnectionObjectWatchdogTimeoutActionInvalid, cip_connection_object::socket, and cip_connection_object::transmission_trigger_timer.
Referenced by EstablishClass3Connection(), and EstablishIoConnection().
CipUdint ConnectionObjectGetCipConsumedConnectionID (const CipConnectionObject *const connection_object)
Definition at line 433 of file cipconnectionobject.c.
References cip_connection_object::cip_consumed_connection_id.
Referenced by GetConnectedObject().
CipUdint ConnectionObjectGetCipProducedConnectionID (const CipConnectionObject *const connection_object)
Definition at line 421 of file cipconnectionobject.c.
References cip_connection_object::cip_produced_connection_id.
CipUint ConnectionObjectGetConnectionSerialNumber (const CipConnectionObject *const connection_object)
Definition at line 568 of file cipconnectionobject.c.
References cip_connection_object::connection_serial_number.
CipUsint ConnectionObjectGetConnectionTimeoutMultiplier (const CipConnectionObject *const connection_object)
Definition at line 601 of file cipconnectionobject.c.
References cip_connection_object::connection_timeout_multiplier.
CipUint ConnectionObjectGetConsumedConnectionPathLength (const CipConnectionObject *const connection_object)
Definition at line 507 of file cipconnectionobject.c.
References cip_connection_object::consumed_connection_path_length.
CipUint ConnectionObjectGetConsumedConnectionSize (const CipConnectionObject *const connection_object)
Definition at line 372 of file cipconnectionobject.c.
References cip_connection_object::consumed_connection_size.
CipUint ConnectionObjectGetExpectedPacketRate (const CipConnectionObject *const connection_object)
Definition at line 384 of file cipconnectionobject.c.
References cip_connection_object::expected_packet_rate.
Referenced by ManageConnections().
ConnectionObjectInstanceType ConnectionObjectGetInstanceType (const CipConnectionObject *const connection_object)
Definition at line 240 of file cipconnectionobject.c.
References cip_connection_object::instance_type.
Referenced by CloseIoConnection(), and HandleIoConnectionTimeOut().
CipUsint ConnectionObjectGetInstanceTypeForAttribute (const CipConnectionObject *const connection_object)
Definition at line 264 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_INSTANCE_TYPE_CIP_BRIDGED, CIP_CONNECTION_OBJECT_INSTANCE_TYPE_EXPLICIT_MESSAGING, CIP_CONNECTION_OBJECT_INSTANCE_TYPE_IO, cip_connection_object::instance_type, kConnectionObjectInstanceTypeCipBridged, kConnectionObjectInstanceTypeExplicitMessaging, kConnectionObjectInstanceTypeIO, kConnectionObjectInstanceTypeIOExclusiveOwner, kConnectionObjectInstanceTypeIOInputOnly, and kConnectionObjectInstanceTypeIOListenOnly.
CipUdint ConnectionObjectGetOriginatorSerialNumber (const CipConnectionObject *const connection_object)
Definition at line 590 of file cipconnectionobject.c.
References cip_connection_object::originator_serial_number.
CipUint ConnectionObjectGetOriginatorVendorId (const CipConnectionObject *const connection_object)
Definition at line 579 of file cipconnectionobject.c.
References cip_connection_object::originator_vendor_id.
size_t ConnectionObjectGetOToTConnectionSize (const CipConnectionObject *const connection_object)
Definition at line 733 of file cipconnectionobject.c.
References ConnectionObjectGetConnectionSize(), and cip_connection_object::o_to_t_network_connection_parameters.
Referenced by SetupIoConnectionOriginatorToTargetConnectionPoint().
ConnectionObjectConnectionSizeType ConnectionObjectGetOToTConnectionSizeType (const CipConnectionObject *const connection_object)
Definition at line 716 of file cipconnectionobject.c.
References ConnectionObjectGetConnectionSizeType(), and cip_connection_object::o_to_t_network_connection_parameters.
ConnectionObjectConnectionType ConnectionObjectGetOToTConnectionType (const CipConnectionObject *const connection_object)
Definition at line 663 of file cipconnectionobject.c.
References ConnectionObjectGetConnectionType(), and cip_connection_object::o_to_t_network_connection_parameters.
Referenced by ConnectionObjectGeneralConfiguration(), EstablishIoConnection(), ForwardOpen(), OpenCommunicationChannels(), and ParseConnectionPath().
ConnectionObjectPriority ConnectionObjectGetOToTPriority (const CipConnectionObject *const connection_object)
Definition at line 693 of file cipconnectionobject.c.
References ConnectionObjectGetPriority(), and cip_connection_object::o_to_t_network_connection_parameters.
CipUdint ConnectionObjectGetOToTRequestedPacketInterval (const CipConnectionObject *const connection_object)
Definition at line 613 of file cipconnectionobject.c.
References cip_connection_object::o_to_t_requested_packet_interval.
CipUint ConnectionObjectGetProducedConnectionPathLength (const CipConnectionObject *const connection_object)
Definition at line 494 of file cipconnectionobject.c.
References cip_connection_object::produced_connection_path_length.
CipUint ConnectionObjectGetProducedConnectionSize (const CipConnectionObject *const connection_object)
Definition at line 360 of file cipconnectionobject.c.
References cip_connection_object::produced_connection_size.
CipUint ConnectionObjectGetProductionInhibitTime (const CipConnectionObject *const connection_object)
Definition at line 520 of file cipconnectionobject.c.
References cip_connection_object::production_inhibit_time.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
CipUint ConnectionObjectGetRequestedPacketInterval (const CipConnectionObject *const connection_object)
Definition at line 389 of file cipconnectionobject.c.
References cip_connection_object::t_to_o_requested_packet_interval.
Referenced by ManageConnections().
ConnectionObjectState ConnectionObjectGetState (const CipConnectionObject *const connection_object)
Definition at line 175 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_STATE_CLOSING, CIP_CONNECTION_OBJECT_STATE_CONFIGURING, CIP_CONNECTION_OBJECT_STATE_DEFERRED_DELETE, CIP_CONNECTION_OBJECT_STATE_ESTABLISHED, CIP_CONNECTION_OBJECT_STATE_NON_EXISTENT, CIP_CONNECTION_OBJECT_STATE_TIMEOUT, CIP_CONNECTION_OBJECT_STATE_WAITING_FOR_CONNECTION_ID, kConnectionObjectStateClosing, kConnectionObjectStateConfiguring, kConnectionObjectStateDeferredDelete, kConnectionObjectStateEstablished, kConnectionObjectStateInvalid, kConnectionObjectStateNonExistent, kConnectionObjectStateTimedOut, kConnectionObjectStateWaitingForConnectionID, and cip_connection_object::state.
Referenced by CheckForExistingConnection(), CheckForTimedOutConnectionsAndCloseTCPConnections(), ForwardClose(), GetConnectedObject(), GetConnectedOutputAssembly(), GetExclusiveOwnerConnection(), GetFreeExplicitConnection(), GetInputOnlyConnection(), GetListenOnlyConnection(), GetNextNonControlMasterConnection(), and ManageConnections().
ConnectionObjectTransportClassTriggerDirection ConnectionObjectGetTransportClassTriggerDirection (const CipConnectionObject *const connection_object)
Definition at line 300 of file cipconnectionobject.c.
References kConnectionObjectTransportClassTriggerDirectionClient, kConnectionObjectTransportClassTriggerDirectionServer, and cip_connection_object::transport_class_trigger.
Referenced by ManageConnections().
ConnectionObjectTransportClassTriggerProductionTrigger ConnectionObjectGetTransportClassTriggerProductionTrigger (const CipConnectionObject *const connection_object)
Definition at line 311 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_PRODUCTION_TRIGGER_APPLICATION_OBJECT, CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_PRODUCTION_TRIGGER_CHANGE_OF_STATE, CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_PRODUCTION_TRIGGER_CYCLIC, kConnectionObjectTransportClassTriggerProductionTriggerApplicationObject, kConnectionObjectTransportClassTriggerProductionTriggerChangeOfState, kConnectionObjectTransportClassTriggerProductionTriggerCyclic, kConnectionObjectTransportClassTriggerProductionTriggerInvalid, and cip_connection_object::transport_class_trigger.
Referenced by HandleNonNullNonMatchingForwardOpenRequest(), ManageConnections(), ParseConnectionPath(), ProcessProductionInhibitTime(), SetupIoConnectionTargetToOriginatorConnectionPoint(), and TriggerConnections().
ConnectionObjectTransportClassTriggerTransportClass ConnectionObjectGetTransportClassTriggerTransportClass (const CipConnectionObject *const connection_object)
Definition at line 338 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_TRANSPORT_CLASS_0, CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_TRANSPORT_CLASS_1, CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_TRANSPORT_CLASS_2, CIP_CONNECTION_OBJECT_TRANSPORT_CLASS_TRIGGER_TRANSPORT_CLASS_3, kConnectionObjectTransportClassTriggerTransportClass0, kConnectionObjectTransportClassTriggerTransportClass1, kConnectionObjectTransportClassTriggerTransportClass2, kConnectionObjectTransportClassTriggerTransportClass3, kConnectionObjectTransportClassTriggerTransportClassInvalid, and cip_connection_object::transport_class_trigger.
Referenced by CloseClass3ConnectionBasedOnSession(), CloseConnection(), HandleReceivedIoConnectionData(), ParseConnectionPath(), SendConnectedData(), SetupIoConnectionOriginatorToTargetConnectionPoint(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
size_t ConnectionObjectGetTToOConnectionSize (const CipConnectionObject *const connection_object)
Definition at line 739 of file cipconnectionobject.c.
References ConnectionObjectGetConnectionSize(), and cip_connection_object::t_to_o_network_connection_parameters.
Referenced by SetupIoConnectionTargetToOriginatorConnectionPoint().
ConnectionObjectConnectionSizeType ConnectionObjectGetTToOConnectionSizeType (const CipConnectionObject *const connection_object)
Definition at line 722 of file cipconnectionobject.c.
References ConnectionObjectGetConnectionSizeType(), and cip_connection_object::t_to_o_network_connection_parameters.
Referenced by SetupIoConnectionTargetToOriginatorConnectionPoint().
ConnectionObjectConnectionType ConnectionObjectGetTToOConnectionType (const CipConnectionObject *const connection_object)
Definition at line 669 of file cipconnectionobject.c.
References ConnectionObjectGetConnectionType(), and cip_connection_object::t_to_o_network_connection_parameters.
Referenced by CloseIoConnection(), ConnectionObjectGeneralConfiguration(), EstablishIoConnection(), ForwardOpen(), GetExistingProducerMulticastConnection(), GetListenOnlyConnection(), GetNextNonControlMasterConnection(), HandleIoConnectionTimeOut(), OpenCommunicationChannels(), ParseConnectionPath(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
ConnectionObjectPriority ConnectionObjectGetTToOPriority (const CipConnectionObject *const connection_object)
Definition at line 699 of file cipconnectionobject.c.
References ConnectionObjectGetPriority(), and cip_connection_object::t_to_o_network_connection_parameters.
Referenced by OpenConsumingPointToPointConnection(), OpenMulticastConnection(), OpenProducingPointToPointConnection(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
CipUdint ConnectionObjectGetTToORequestedPacketInterval (const CipConnectionObject *const connection_object)
Definition at line 625 of file cipconnectionobject.c.
References cip_connection_object::t_to_o_requested_packet_interval.
Referenced by ProcessProductionInhibitTime(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
ConnectionObjectWatchdogTimeoutAction ConnectionObjectGetWatchdogTimeoutAction (const CipConnectionObject *const connection_object)
Definition at line 445 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_AUTO_DELETE, CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_AUTO_RESET, CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_DEFERRED_DELETE, CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_TRANSITION_TO_TIMED_OUT, kConnectionObjectWatchdogTimeoutActionAutoDelete, kConnectionObjectWatchdogTimeoutActionAutoReset, kConnectionObjectWatchdogTimeoutActionDeferredDelete, kConnectionObjectWatchdogTimeoutActionInvalid, kConnectionObjectWatchdogTimeoutActionTransitionToTimedOut, and cip_connection_object::watchdog_timeout_action.
void ConnectionObjectInitializeEmpty (CipConnectionObject *const connection_object)
Definition at line 97 of file cipconnectionobject.c.
References ConnectionObjectSetState(), kConnectionObjectStateNonExistent, and cip_connection_object::socket.
Referenced by CipClass3ConnectionObjectStateEstablishedHandler(), CloseCommunicationChannelsAndRemoveFromActiveConnectionsList(), and CloseConnection().
void ConnectionObjectInitializeFromMessage (const CipOctet ** message, CipConnectionObject *const connection_object)
Definition at line 111 of file cipconnectionobject.c.
References cip_connection_object::cip_consumed_connection_id, cip_connection_object::cip_produced_connection_id, cip_connection_object::connection_serial_number, ConnectionObjectSetCipConsumedConnectionID(), ConnectionObjectSetCipProducedConnectionID(), ConnectionObjectSetConnectionSerialNumber(), ConnectionObjectSetConnectionTimeoutMultiplier(), ConnectionObjectSetExpectedPacketRate(), ConnectionObjectSetInitialInactivityWatchdogTimerValue(), ConnectionObjectSetOriginatorSerialNumber(), ConnectionObjectSetOriginatorVendorId(), ConnectionObjectSetOToTRequestedPacketInterval(), ConnectionObjectSetState(), ConnectionObjectSetTToORequestedPacketInterval(), GetDintFromMessage(), GetIntFromMessage(), GetSintFromMessage(), kConnectionObjectStateNonExistent, MoveMessageNOctets(), cip_connection_object::o_to_t_network_connection_parameters, OPENER_TRACE_INFO, cip_connection_object::sequence_count_producing, cip_connection_object::t_to_o_network_connection_parameters, and cip_connection_object::transport_class_trigger.
Referenced by ForwardOpen().
bool ConnectionObjectIsOToTRedundantOwner (const CipConnectionObject *const connection_object)
Definition at line 637 of file cipconnectionobject.c.
References cip_connection_object::o_to_t_network_connection_parameters.
bool ConnectionObjectIsTToORedundantOwner (const CipConnectionObject *const connection_object)
Definition at line 643 of file cipconnectionobject.c.
References cip_connection_object::t_to_o_network_connection_parameters.
bool ConnectionObjectIsTypeIOConnection (const CipConnectionObject *const connection_object)
Definition at line 286 of file cipconnectionobject.c.
References cip_connection_object::instance_type, kConnectionObjectInstanceTypeIO, kConnectionObjectInstanceTypeIOExclusiveOwner, kConnectionObjectInstanceTypeIOInputOnly, and kConnectionObjectInstanceTypeIOListenOnly.
Referenced by GetExistingProducerMulticastConnection(), GetNextNonControlMasterConnection(), and IsConnectedOutputAssembly().
void ConnectionObjectResetInactivityWatchdogTimerValue (CipConnectionObject *const connection_object)
Definition at line 545 of file cipconnectionobject.c.
References ConnectionObjectCalculateRegularInactivityWatchdogTimerValue(), and cip_connection_object::inactivity_watchdog_timer.
Referenced by HandleReceivedConnectedData(), and NotifyConnectedCommonPacketFormat().
void ConnectionObjectResetLastPackageInactivityTimerValue (CipConnectionObject *const connection_object)
Definition at line 552 of file cipconnectionobject.c.
References ConnectionObjectCalculateRegularInactivityWatchdogTimerValue(), and cip_connection_object::last_package_watchdog_timer.
Referenced by HandleReceivedConnectedData().
void ConnectionObjectResetProductionInhibitTimer (CipConnectionObject *const connection_object)
Definition at line 760 of file cipconnectionobject.c.
References cip_connection_object::production_inhibit_time, and cip_connection_object::production_inhibit_timer.
Referenced by ConnectionObjectGeneralConfiguration(), and ManageConnections().
void ConnectionObjectSetCipConsumedConnectionID (CipConnectionObject *const connection_object, const CipUdint cip_consumed_connection_id)
Definition at line 438 of file cipconnectionobject.c.
References cip_connection_object::cip_consumed_connection_id.
Referenced by ConnectionObjectGeneralConfiguration(), and ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetCipProducedConnectionID (CipConnectionObject *const connection_object, const CipUdint cip_produced_connection_id)
Definition at line 426 of file cipconnectionobject.c.
References cip_connection_object::cip_produced_connection_id.
Referenced by ConnectionObjectGeneralConfiguration(), and ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetConnectionSerialNumber (CipConnectionObject * connection_object, const CipUint connection_serial_number)
Definition at line 573 of file cipconnectionobject.c.
References cip_connection_object::connection_serial_number.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetConnectionTimeoutMultiplier (CipConnectionObject *const connection_object, const CipUsint connection_timeout_multiplier)
Definition at line 606 of file cipconnectionobject.c.
References cip_connection_object::connection_timeout_multiplier.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetConsumedConnectionPathLength (CipConnectionObject *const connection_object, const CipUint consumed_connection_path_length)
Definition at line 512 of file cipconnectionobject.c.
References cip_connection_object::consumed_connection_path_length.
void ConnectionObjectSetConsumedConnectionSize (CipConnectionObject *const connection_object, const CipUint consumed_connection_size)
Definition at line 377 of file cipconnectionobject.c.
References cip_connection_object::consumed_connection_size.
void ConnectionObjectSetExpectedPacketRate (CipConnectionObject *const connection_object)
Sets the expected packet rate according to the rules of the CIP specification.
As this function sets the expected packet rate according to the rules of the CIP specification, it is not always the exact value entered, but rounded up to the next serviceable increment, relative to the timer resolution
Definition at line 404 of file cipconnectionobject.c.
References cip_connection_object::expected_packet_rate, and cip_connection_object::t_to_o_requested_packet_interval.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetInstanceType (CipConnectionObject *const connection_object, const ConnectionObjectInstanceType instance_type)
Definition at line 258 of file cipconnectionobject.c.
References cip_connection_object::instance_type.
Referenced by EstablishClass3Connection(), and GetIoConnectionForConnectionData().
void ConnectionObjectSetOriginatorSerialNumber (CipConnectionObject * connection_object, CipUdint originator_serial_number)
Definition at line 595 of file cipconnectionobject.c.
References cip_connection_object::originator_serial_number.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetOriginatorVendorId (CipConnectionObject * connection_object, const CipUint vendor_id)
Definition at line 584 of file cipconnectionobject.c.
References cip_connection_object::originator_vendor_id.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetOToTRequestedPacketInterval (CipConnectionObject * connection_object, const CipUdint requested_packet_interval)
Definition at line 618 of file cipconnectionobject.c.
References cip_connection_object::o_to_t_requested_packet_interval.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetProducedConnectionPathLength (CipConnectionObject *const connection_object, const CipUint produced_connection_path_length)
Definition at line 499 of file cipconnectionobject.c.
References cip_connection_object::produced_connection_path_length.
void ConnectionObjectSetProducedConnectionSize (CipConnectionObject *const connection_object, const CipUint produced_connection_size)
Definition at line 365 of file cipconnectionobject.c.
References cip_connection_object::produced_connection_size.
void ConnectionObjectSetProductionInhibitTime (CipConnectionObject *const connection_object, const CipUint production_inhibit_time)
Definition at line 525 of file cipconnectionobject.c.
References cip_connection_object::production_inhibit_time.
Referenced by ParseConnectionPath(), and ProcessProductionInhibitTime().
void ConnectionObjectSetState (CipConnectionObject *const connection_object, const ConnectionObjectState state)
Definition at line 204 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_STATE_CLOSING, CIP_CONNECTION_OBJECT_STATE_CONFIGURING, CIP_CONNECTION_OBJECT_STATE_DEFERRED_DELETE, CIP_CONNECTION_OBJECT_STATE_ESTABLISHED, CIP_CONNECTION_OBJECT_STATE_NON_EXISTENT, CIP_CONNECTION_OBJECT_STATE_TIMEOUT, CIP_CONNECTION_OBJECT_STATE_WAITING_FOR_CONNECTION_ID, kConnectionObjectStateClosing, kConnectionObjectStateConfiguring, kConnectionObjectStateDeferredDelete, kConnectionObjectStateEstablished, kConnectionObjectStateNonExistent, kConnectionObjectStateTimedOut, kConnectionObjectStateWaitingForConnectionID, OPENER_ASSERT, and cip_connection_object::state.
Referenced by AddNewActiveConnection(), AssembleForwardOpenResponse(), CipClass3ConnectionObjectStateEstablishedHandler(), CipClass3ConnectionObjectStateNonExistentHandler(), ConnectionObjectInitializeEmpty(), ConnectionObjectInitializeFromMessage(), and HandleIoConnectionTimeOut().
void ConnectionObjectSetTToORequestedPacketInterval (CipConnectionObject * connection_object, const CipUdint requested_packet_interval)
Definition at line 630 of file cipconnectionobject.c.
References cip_connection_object::t_to_o_requested_packet_interval.
Referenced by ConnectionObjectInitializeFromMessage().
void ConnectionObjectSetWatchdogTimeoutAction (CipConnectionObject *const connection_object, const CipUsint watchdog_timeout_action)
Definition at line 466 of file cipconnectionobject.c.
References CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_AUTO_DELETE, CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_AUTO_RESET, CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_DEFERRED_DELETE, CIP_CONNECTION_OBJECT_WATCHDOG_TIMEOUT_ACTION_TRANSITION_TO_TIMED_OUT, kConnectionObjectWatchdogTimeoutActionAutoDelete, kConnectionObjectWatchdogTimeoutActionAutoReset, kConnectionObjectWatchdogTimeoutActionDeferredDelete, kConnectionObjectWatchdogTimeoutActionInvalid, kConnectionObjectWatchdogTimeoutActionTransitionToTimedOut, and cip_connection_object::watchdog_timeout_action.
Referenced by ConnectionObjectGeneralConfiguration().
bool EqualConnectionTriad (const CipConnectionObject *const object1, const CipConnectionObject *const object2)
Definition at line 811 of file cipconnectionobject.c.
References cip_connection_object::connection_serial_number, cip_connection_object::originator_serial_number, and cip_connection_object::originator_vendor_id.
Referenced by CheckForExistingConnection(), GetExclusiveOwnerConnection(), GetInputOnlyConnection(), and GetListenOnlyConnection().