OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipioconnection.c File Reference
src/cip/cipioconnection.c File Reference
#include <string.h>
#include <stdbool.h>
#include "cipioconnection.h"
#include "generic_networkhandler.h"
#include "cipconnectionmanager.h"
#include "cipassembly.h"
#include "ciptcpipinterface.h"
#include "cipcommon.h"
#include "appcontype.h"
#include "cpf.h"
#include "trace.h"
#include "endianconv.h"
Enumerations
enum CipConnectionObjectTransportClassTriggerClass {
kCipConnectionObjectTransportClassTriggerClassInvalid = -1, kCipConnectionObjectTransportClassTriggerClass0 = 0, kCipConnectionObjectTransportClassTriggerClass1 = 1, kCipConnectionObjectTransportClassTriggerClass2 = 2,
kCipConnectionObjectTransportClassTriggerClass3 = 3, kCipConnectionObjectTransportClassTriggerClass4 = 4, kCipConnectionObjectTransportClassTriggerClass5 = 5, kCipConnectionObjectTransportClassTriggerClass6 = 6
}
enum CommunicationEndpointCardinality { PointToMultipoint = 1, PointToPoint = 2 }
The cardinality of a connection endpoint, either point to point or point to multipoint.
Functions
void CloseCommunicationChannelsAndRemoveFromActiveConnectionsList (ConnectionObject *connection_object)
close the communication channels of the given connection and remove it from the active connections list.
void CloseIoConnection (ConnectionObject *connection_object)
EipStatus EstablishIoConnection (ConnectionObject *RESTRICT const connection_object, EipUint16 *const extended_error)
Establishes a new IO Type 1 Connection.
CipConnectionObjectTransportClassTriggerClass GetConnectionObjectTransportClass (const ConnectionObject *const connection_object)
EipUint16 HandleConfigData (ConnectionObject *connection_object)
void HandleIoConnectionTimeOut (ConnectionObject *connection_object)
EipStatus HandleReceivedIoConnectionData (ConnectionObject *connection_object, const EipUint8 *data, EipUint16 data_length)
EipStatus OpenCommunicationChannels (ConnectionObject *connection_object)
Take the data given in the connection object structure and open the necessary communication channels.
EipStatus OpenConsumingPointToPointConnection (ConnectionObject *const connection_object, CipCommonPacketFormatData *const common_packet_format_data)
Open a Point2Point connection dependent on pa_direction.
EipStatus OpenMulticastConnection (UdpCommuncationDirection direction, ConnectionObject *connection_object, CipCommonPacketFormatData *common_packet_format_data)
EipStatus OpenProducingMulticastConnection (ConnectionObject *connection_object, CipCommonPacketFormatData *common_packet_format_data)
EipStatus OpenProducingPointToPointConnection (ConnectionObject *connection_object, CipCommonPacketFormatData *common_packet_format_data)
EipUint16 ProcessProductionInhibitTime (ConnectionObject *io_connection_object)
EipStatus SendConnectedData (ConnectionObject *connection_object)
Send the data from the produced CIP Object of the connection via the socket of the connection object on UDP.
void SetIoConnectionCallbacks (ConnectionObject *const io_connection_object)
EipUint16 SetupIoConnectionOriginatorToTargetConnectionPoint (ConnectionObject *const io_connection_object, ConnectionObject *const RESTRICT connection_object)
EipUint16 SetupIoConnectionTargetToOriginatorConnectionPoint (ConnectionObject *const io_connection_object, ConnectionObject *const RESTRICT connection_object)
Variables
EipUint8 * g_config_data_buffer = NULL
unsigned int g_config_data_length = 0
EipUint32 g_run_idle_state
const unsigned int kConnectionPointConfig = 2
const unsigned int kConnectionPointConsumer = 0
const unsigned int kConnectionPointProducer = 1
const int kOpenerEipIoUdpPort = 0x08AE
Enumeration Type Documentation
enum CipConnectionObjectTransportClassTriggerClass
Enumerator:
kCipConnectionObjectTransportClassTriggerClassInvalid
kCipConnectionObjectTransportClassTriggerClass0
kCipConnectionObjectTransportClassTriggerClass1
kCipConnectionObjectTransportClassTriggerClass2
kCipConnectionObjectTransportClassTriggerClass3
kCipConnectionObjectTransportClassTriggerClass4
kCipConnectionObjectTransportClassTriggerClass5
kCipConnectionObjectTransportClassTriggerClass6
Definition at line 22 of file cipioconnection.c.
enum CommunicationEndpointCardinality
The cardinality of a connection endpoint, either point to point or point to multipoint.
Enumerator:
PointToMultipoint
Connection is a point to multi-point connection
PointToPoint
Connection is a point to point connection
Definition at line 42 of file cipioconnection.c.
Function Documentation
void CloseCommunicationChannelsAndRemoveFromActiveConnectionsList (ConnectionObject * connection_object)
close the communication channels of the given connection and remove it from the active connections list.
Parameters:
connection_object pointer to the connection object data
Definition at line 974 of file cipioconnection.c.
References CloseUdpSocket(), kUdpCommuncationDirectionConsuming, kUdpCommuncationDirectionProducing, RemoveFromActiveConnections(), and connection_object::socket.
Referenced by CloseIoConnection().
void CloseIoConnection (ConnectionObject * connection_object)
Definition at line 701 of file cipioconnection.c.
References CheckIoConnectionEvent(), CloseAllConnectionsForInputWithSameType(), CloseCommunicationChannelsAndRemoveFromActiveConnectionsList(), connection_object::connection_path, CipConnectionPath::connection_point, connection_object::eip_level_sequence_count_producing, GetNextNonControlMasterConnection(), connection_object::instance_type, kConnectionPointConsumer, kConnectionPointProducer, kConnectionTypeIoExclusiveOwner, kConnectionTypeIoInputOnly, kConnectionTypeIoListenOnly, kForwardOpenConnectionTypeMulticastConnection, kIoConnectionEventClosed, kUdpCommuncationDirectionProducing, connection_object::remote_address, connection_object::sequence_count_producing, connection_object::socket, connection_object::t_to_o_network_connection_parameter, and connection_object::transmission_trigger_timer.
Referenced by SetIoConnectionCallbacks().
EipStatus EstablishIoConnection (ConnectionObject *RESTRICT const connection_object, EipUint16 *const extended_error)
Establishes a new IO Type 1 Connection.
Setup all data in order to establish an IO connection.
This function needs the guarantee that no Null request will be passed to it. It will generate a new IO connection based on the data parsed in the Forward Open service
Parameters:
connection_object pointer to the connection object structure holding the parsed data from the forward open request
extended_error the extended error code in case an error happened
Returns:
general status on the establishment
kEipStatusOk ... on success
On an error the general status code to be put into the response
Already handled by forward open
Definition at line 310 of file cipioconnection.c.
References AddNewActiveConnection(), CheckIoConnectionEvent(), connection_object::connection_path, CipConnectionPath::connection_point, connection_object::consumed_connection_path_length, connection_object::consuming_instance, g_config_data_buffer, GeneralConnectionConfiguration(), GetConnectionType(), GetIoConnectionForConnectionData(), HandleConfigData(), kCipErrorConnectionFailure, kConnectionManagerExtendedStatusCodeSuccess, kEipStatusOk, kForwardOpenConnectionTypeNull, kIoConnectionEventOpened, OpenCommunicationChannels(), OPENER_ASSERT, ProcessProductionInhibitTime(), connection_object::produced_connection_path_length, connection_object::producing_instance, SetIoConnectionCallbacks(), SetupIoConnectionOriginatorToTargetConnectionPoint(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
Referenced by ConnectionManagerInit().
CipConnectionObjectTransportClassTriggerClass GetConnectionObjectTransportClass (const ConnectionObject *const connection_object)
Definition at line 122 of file cipioconnection.c.
References kCipConnectionObjectTransportClassTriggerClass0, kCipConnectionObjectTransportClassTriggerClass1, kCipConnectionObjectTransportClassTriggerClass2, kCipConnectionObjectTransportClassTriggerClass3, kCipConnectionObjectTransportClassTriggerClass4, kCipConnectionObjectTransportClassTriggerClass5, kCipConnectionObjectTransportClassTriggerClass6, kCipConnectionObjectTransportClassTriggerClassInvalid, and connection_object::transport_type_class_trigger.
Referenced by SetupIoConnectionOriginatorToTargetConnectionPoint(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
EipUint16 HandleConfigData (ConnectionObject * connection_object)
Definition at line 654 of file cipioconnection.c.
References connection_object::connection_path, CipConnectionPath::connection_point, ConnectionWithSameConfigPointExists(), CipByteArray::data, CipAttributeStruct::data, g_config_data_buffer, g_config_data_length, GetCipAttribute(), GetCipClass(), GetCipInstance(), kConnectionManagerExtendedStatusCodeErrorOwnershipConflict, kConnectionManagerExtendedStatusCodeInvalidConfigurationApplicationPath, kConnectionPointConfig, kEipStatusOk, CipByteArray::length, NotifyAssemblyConnectedDataReceived(), OPENER_TRACE_INFO, and OPENER_TRACE_WARN.
Referenced by EstablishIoConnection().
void HandleIoConnectionTimeOut (ConnectionObject * connection_object)
Definition at line 750 of file cipioconnection.c.
References CheckIoConnectionEvent(), CloseAllConnectionsForInputWithSameType(), connection_object::connection_close_function, connection_object::connection_path, CipConnectionPath::connection_point, GetNextNonControlMasterConnection(), connection_object::instance_type, kConnectionTypeIoExclusiveOwner, kConnectionTypeIoInputOnly, kConnectionTypeIoListenOnly, kForwardOpenConnectionTypeMulticastConnection, kIoConnectionEventTimedOut, kUdpCommuncationDirectionProducing, OPENER_ASSERT, connection_object::socket, connection_object::t_to_o_network_connection_parameter, and connection_object::transmission_trigger_timer.
Referenced by SetIoConnectionCallbacks().
EipStatus HandleReceivedIoConnectionData (ConnectionObject * connection_object, const EipUint8 * data, EipUint16 data_length)
Definition at line 876 of file cipioconnection.c.
References connection_object::consuming_instance, g_run_idle_state, GetDintFromMessage(), GetIntFromMessage(), kEipStatusError, kEipStatusOk, NotifyAssemblyConnectedDataReceived(), RunIdleChanged(), SEQ_LEQ16, connection_object::sequence_count_consuming, and connection_object::transport_type_class_trigger.
Referenced by SetIoConnectionCallbacks().
EipStatus OpenCommunicationChannels (ConnectionObject * connection_object)
Take the data given in the connection object structure and open the necessary communication channels.
This function will use the g_stCPFDataItem!
Parameters:
connection_object pointer to the connection object data
Returns:
general status on the open process
EIP_OK ... on success
On an error the general status code to be put into the response
Definition at line 913 of file cipioconnection.c.
References g_common_packet_format_data_item, GetConnectionType(), kCipErrorConnectionFailure, kEipStatusError, kEipStatusOk, kForwardOpenConnectionTypeMulticastConnection, kForwardOpenConnectionTypePointToPointConnection, kUdpCommuncationDirectionConsuming, OpenConsumingPointToPointConnection(), OPENER_TRACE_ERR, OpenMulticastConnection(), OpenProducingMulticastConnection(), and OpenProducingPointToPointConnection().
Referenced by EstablishIoConnection().
EipStatus OpenConsumingPointToPointConnection (ConnectionObject *const connection_object, CipCommonPacketFormatData *const common_packet_format_data)
Open a Point2Point connection dependent on pa_direction.
Parameters:
connection_object Pointer to registered Object in ConnectionManager.
common_packet_format_data Index of the connection object
Returns:
kEipStatusOk on success, otherwise kEipStatusError
Definition at line 403 of file cipioconnection.c.
References CipCommonPacketFormatData::address_info_item, CreateUdpSocket(), GetConnectionObjectTToOPriority(), kCipItemIdSocketAddressInfoOriginatorToTarget, kEipStatusError, kEipStatusOk, kOpenerEipIoUdpPort, kUdpCommuncationDirectionConsuming, SocketAddressInfoItem::length, SocketAddressInfoItem::nasin_zero, OPENER_TRACE_ERR, connection_object::originator_address, SocketAddressInfoItem::sin_addr, SocketAddressInfoItem::sin_family, SocketAddressInfoItem::sin_port, connection_object::socket, and SocketAddressInfoItem::type_id.
Referenced by OpenCommunicationChannels().
EipStatus OpenMulticastConnection (UdpCommuncationDirection direction, ConnectionObject * connection_object, CipCommonPacketFormatData * common_packet_format_data)
Definition at line 553 of file cipioconnection.c.
References CipCommonPacketFormatData::address_info_item, CreateUdpSocket(), g_multicast_configuration, GetConnectionObjectTToOPriority(), kCipItemIdSocketAddressInfoOriginatorToTarget, kCipItemIdSocketAddressInfoTargetToOriginator, kEipStatusError, kEipStatusOk, kOpenerEipIoUdpPort, kUdpCommuncationDirectionConsuming, kUdpCommuncationDirectionProducing, SocketAddressInfoItem::length, SocketAddressInfoItem::nasin_zero, OPENER_TRACE_ERR, OPENER_TRACE_INFO, connection_object::originator_address, connection_object::remote_address, SocketAddressInfoItem::sin_addr, SocketAddressInfoItem::sin_family, SocketAddressInfoItem::sin_port, connection_object::socket, multicast_address_configuration::starting_multicast_address, and SocketAddressInfoItem::type_id.
Referenced by OpenCommunicationChannels(), and OpenProducingMulticastConnection().
EipStatus OpenProducingMulticastConnection (ConnectionObject * connection_object, CipCommonPacketFormatData * common_packet_format_data)
Definition at line 483 of file cipioconnection.c.
References CipCommonPacketFormatData::address_info_item, connection_object::cip_produced_connection_id, connection_object::connection_path, CipConnectionPath::connection_point, g_common_packet_format_data_item, g_multicast_configuration, GetExistingProducerMulticastConnection(), connection_object::instance_type, kCipItemIdSocketAddressInfoTargetToOriginator, kConnectionTypeIoExclusiveOwner, kEipStatusOk, kOpenerEipIoUdpPort, kUdpCommuncationDirectionProducing, SocketAddressInfoItem::length, SocketAddressInfoItem::nasin_zero, OpenMulticastConnection(), connection_object::remote_address, SocketAddressInfoItem::sin_family, SocketAddressInfoItem::sin_port, connection_object::socket, and SocketAddressInfoItem::type_id.
Referenced by OpenCommunicationChannels().
EipStatus OpenProducingPointToPointConnection (ConnectionObject * connection_object, CipCommonPacketFormatData * common_packet_format_data)
Definition at line 448 of file cipioconnection.c.
References CipCommonPacketFormatData::address_info_item, CreateUdpSocket(), GetConnectionObjectTToOPriority(), kCipErrorConnectionFailure, kCipItemIdSocketAddressInfoTargetToOriginator, kEipStatusOk, kOpenerEipIoUdpPort, kUdpCommuncationDirectionProducing, OPENER_TRACE_ERR, connection_object::remote_address, SocketAddressInfoItem::sin_port, connection_object::socket, and SocketAddressInfoItem::type_id.
Referenced by OpenCommunicationChannels().
EipUint16 ProcessProductionInhibitTime (ConnectionObject * io_connection_object)
< RPI not supported. Extended Error code deprecated
Definition at line 98 of file cipioconnection.c.
References GetProductionInhibitTime(), GetProductionTrigger(), GetTargetToOriginatorRequestedPackedInterval(), kConnectionManagerExtendedStatusCodeRpiNotSupported, kConnectionManagerExtendedStatusCodeSuccess, kProductionTriggerCyclic, OPENER_TRACE_INFO, and SetProductionInhibitTime().
Referenced by EstablishIoConnection().
EipStatus SendConnectedData (ConnectionObject * connection_object)
Send the data from the produced CIP Object of the connection via the socket of the connection object on UDP.
Parameters:
connection_object pointer to the connection object
Returns:
status EIP_OK .. success EIP_ERROR .. error
Definition at line 797 of file cipioconnection.c.
References AddDintToMessage(), AddIntToMessage(), CipCommonPacketFormatData::address_info_item, CipCommonPacketFormatData::address_item, AssembleIOMessage(), cip_instance::attributes, BeforeAssemblyDataSend(), connection_object::cip_produced_connection_id, AddressData::connection_identifier, AddressItem::data, CipByteArray::data, CipAttributeStruct::data, CipCommonPacketFormatData::data_item, connection_object::eip_level_sequence_count_producing, g_common_packet_format_data_item, g_message_data_reply_buffer, g_run_idle_state, CipCommonPacketFormatData::item_count, kCipItemIdConnectedDataItem, kCipItemIdConnectionAddress, kCipItemIdSequencedAddressItem, kUdpCommuncationDirectionProducing, AddressItem::length, DataItem::length, CipByteArray::length, connection_object::producing_instance, connection_object::remote_address, SendUdpData(), connection_object::sequence_count_producing, AddressData::sequence_number, connection_object::socket, connection_object::transport_type_class_trigger, AddressItem::type_id, DataItem::type_id, and SocketAddressInfoItem::type_id.
Referenced by SetIoConnectionCallbacks().
void SetIoConnectionCallbacks (ConnectionObject *const io_connection_object)
Definition at line 139 of file cipioconnection.c.
References CloseIoConnection(), connection_object::connection_close_function, connection_object::connection_receive_data_function, connection_object::connection_send_data_function, connection_object::connection_timeout_function, HandleIoConnectionTimeOut(), HandleReceivedIoConnectionData(), and SendConnectedData().
Referenced by EstablishIoConnection().
EipUint16 SetupIoConnectionOriginatorToTargetConnectionPoint (ConnectionObject *const io_connection_object, ConnectionObject *const RESTRICT connection_object)
Definition at line 147 of file cipioconnection.c.
References CipEpath::attribute_number, CipEpath::class_id, CipConnectionPath::class_id, connection_object::connection_path, CipConnectionPath::connection_point, connection_object::consumed_connection_path, connection_object::consumed_connection_path_length, connection_object::consumed_connection_size, connection_object::consuming_instance, CipAttributeStruct::data, GetCipAttribute(), GetCipClass(), GetCipInstance(), GetConnectionObjectTransportClass(), CipEpath::instance_number, kCipConnectionObjectTransportClassTriggerClass1, kConnectionManagerExtendedStatusCodeErrorInvalidOToTConnectionSize, kConnectionManagerExtendedStatusCodeInvalidConsumingApplicationPath, kConnectionManagerExtendedStatusCodeSuccess, kConnectionPointConsumer, OPENER_ASSERT, and CipEpath::path_size.
Referenced by EstablishIoConnection().
EipUint16 SetupIoConnectionTargetToOriginatorConnectionPoint (ConnectionObject *const io_connection_object, ConnectionObject *const RESTRICT connection_object)
Definition at line 201 of file cipioconnection.c.
References CipEpath::attribute_number, CipEpath::class_id, CipConnectionPath::class_id, connection_object::connection_path, CipConnectionPath::connection_point, CipAttributeStruct::data, g_active_connection_list, GetCipAttribute(), GetCipClass(), GetCipInstance(), GetConnectionObjectTargetToOriginatorFixedOrVariableConnectionSize(), GetConnectionObjectTransportClass(), GetConnectionObjectTToOPriority(), GetProductionInhibitTime(), GetProductionTrigger(), GetTargetToOriginatorRequestedPackedInterval(), CipEpath::instance_number, kCipConnectionObjectTransportClassTriggerClass1, kConnectionManagerExtendedStatusCodeErrorInvalidTToOConnectionSize, kConnectionManagerExtendedStatusCodeErrorRpiValuesNotAcceptable, kConnectionManagerExtendedStatusCodeInvalidProducingApplicationPath, kConnectionManagerExtendedStatusCodeMismatchedTransportClass, kConnectionManagerExtendedStatusCodeMismatchedTToONetworkConnectionFixVar, kConnectionManagerExtendedStatusCodeMismatchedTToONetworkConnectionPriority, kConnectionManagerExtendedStatusCodeMismatchedTToOProductionInhibitTimeSegment, kConnectionManagerExtendedStatusCodeMismatchedTToOProductionTrigger, kConnectionManagerExtendedStatusCodeSuccess, kConnectionPointProducer, connection_object::next_connection_object, OPENER_ASSERT, CipEpath::path_size, connection_object::produced_connection_path, connection_object::produced_connection_path_length, connection_object::produced_connection_size, and connection_object::producing_instance.
Referenced by EstablishIoConnection().
Variable Documentation
EipUint8* g_config_data_buffer = NULL
buffers for the config data coming with a forward open request.
Definition at line 93 of file cipioconnection.c.
Referenced by EstablishIoConnection(), HandleConfigData(), and ParseConnectionPath().
unsigned int g_config_data_length = 0
length of g_config_data_buffer. Initialized with 0
Definition at line 94 of file cipioconnection.c.
Referenced by HandleConfigData(), and ParseConnectionPath().
EipUint32 g_run_idle_state
buffer for holding the run idle information.
Definition at line 96 of file cipioconnection.c.
Referenced by HandleReceivedIoConnectionData(), and SendConnectedData().
const unsigned int kConnectionPointConfig = 2
Config connection point
Definition at line 36 of file cipioconnection.c.
Referenced by HandleConfigData().
const unsigned int kConnectionPointConsumer = 0
Consumer connection point
Definition at line 34 of file cipioconnection.c.
Referenced by CloseIoConnection(), and SetupIoConnectionOriginatorToTargetConnectionPoint().
const unsigned int kConnectionPointProducer = 1
Producer connection point
Definition at line 35 of file cipioconnection.c.
Referenced by CloseIoConnection(), and SetupIoConnectionTargetToOriginatorConnectionPoint().
const int kOpenerEipIoUdpPort = 0x08AE
Definition at line 48 of file cipioconnection.c.
Referenced by OpenConsumingPointToPointConnection(), OpenMulticastConnection(), OpenProducingMulticastConnection(), and OpenProducingPointToPointConnection().